/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.springframework.util.Assert.state;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;
import com.harbormaster.subscriber.*;

/**
 * <h2>NetworkProfileTest</h2>
 * <p>
 * Junit test class for entity NetworkProfile.  Handle the full lifecycle as it relates to persistence. Leverages
 * the NetworkProfileService and a NetworkProfileSubscriber to test everything under a MVC framework which includes the
 * NetworkProfileAggregate and related commands, queries, and events.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 * 		NetworkProfileService
 * 	    NetworkProfileSubscriber
 *
 * <h3>Methods</h3>
 *      <ul>
 *      <li>read</li>
 *      <li>update</li>
 *      <li>delete</li>
 *      </ul>
 *
 * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class NetworkProfileTest {

    // ------------------------------------
	// default constructor
    // ------------------------------------
	public NetworkProfileTest() {
		subscriber = new NetworkProfileSubscriber();
	}

	// test methods
	@Test
	/*
	 * Initiate NetworkProfileTest.
	 */
	public void startTest() throws Throwable {
		try {
			LOGGER.info("**********************************************************");
			LOGGER.info("Beginning test on NetworkProfile...");
			LOGGER.info("**********************************************************\n");
			
			// ---------------------------------------------
			// jumpstart process
			// ---------------------------------------------
			jumpStart();
			
		} catch (Throwable e) {
			throw e;
		} finally {
		}
	}

	/** 
	 * jumpstart the process by instantiating2 NetworkProfile
	 */
	protected void jumpStart() throws Throwable {
		LOGGER.info( "\n======== create instances to get the ball rolling  ======== ");

		networkProfileId = NetworkProfileService.getNetworkProfileInstance()
		.createNetworkProfile( generateNewCommand() )
		.get();

		// ---------------------------------------------
		// set up query subscriptions after the 1st create
		// ---------------------------------------------
		testingStep = "create";
		setUpQuerySubscriptions();

		NetworkProfileService.getNetworkProfileInstance()
				.createNetworkProfile( generateNewCommand() )
				.get();

	}

	/** 
	 * Set up query subscriptions
	 */
	protected void setUpQuerySubscriptions() throws Throwable {
		LOGGER.info( "\n======== Setting Up Query Subscriptions ======== ");
			
		try {            
			subscriber.networkProfileSubscribe().updates().subscribe(
					  successValue -> {
						  LOGGER.info(successValue.toString());
						  try {
							  LOGGER.info("GetAll update received for NetworkProfile : " + successValue.getNetworkProfileId());
							  if (successValue.getNetworkProfileId().equals(networkProfileId)) {
								  if (testingStep.equals("create")) {
									  testingStep = "update";
									  update();
								  } else if (testingStep.equals("delete")) {
									  testingStep = "complete";
									  state( getAll().size() == sizeOfNetworkProfileList - 1 , "value not deleted from list");
									  LOGGER.info("**********************************************************");
									  LOGGER.info("NetworkProfile test completed successfully...");
									  LOGGER.info("**********************************************************\n");
								  }
							  }
						  } catch( Throwable exc ) {
							  LOGGER.warning( exc.getMessage() );
						  }
					  },
					  error -> LOGGER.warning(error.getMessage()),
					  () -> LOGGER.info("Subscription on networkProfile consumed")
					);
			subscriber.networkProfileSubscribe( networkProfileId ).updates().subscribe(
					  successValue -> {
						  LOGGER.info(successValue.toString());
						  try {
							  LOGGER.info("GetOne update received for NetworkProfile : " + successValue.getNetworkProfileId() + " in step " + testingStep);
							  testingStep = "delete";
							  sizeOfNetworkProfileList = getAll().size();
							  delete();
						  } catch( Throwable exc ) {
							  LOGGER.warning( exc.getMessage() );
						  }
					  },
					  error -> LOGGER.warning(error.getMessage()),
					  () -> LOGGER.info("Subscription on networkProfile for networkProfileId consumed")

					);
			

			}
			catch (Exception e) {
				LOGGER.warning( e.getMessage() );
				throw e;
			}
		}
		
		/** 
	 * read a NetworkProfile. 
	 */
	protected NetworkProfile read() throws Throwable {
		LOGGER.info( "\n======== READ ======== ");
		LOGGER.info( "-- Reading a previously created NetworkProfile" );

		NetworkProfile entity = null;
		StringBuilder msg = new StringBuilder( "-- Failed to read NetworkProfile with primary key" );
		msg.append( networkProfileId );
		
		NetworkProfileFetchOneSummary fetchOneSummary = new NetworkProfileFetchOneSummary( networkProfileId );

		try {
			entity = NetworkProfileService.getNetworkProfileInstance().getNetworkProfile( fetchOneSummary );

			assertNotNull( entity,msg.toString() );

			LOGGER.info( "-- Successfully found NetworkProfile " + entity.toString() );
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : " + e );

			throw e;
		}
		
		return entity;
	}

	/** 
	 * updating a NetworkProfile.
	 */
	protected void update() throws Throwable {
		LOGGER.info( "\n======== UPDATE ======== ");
		LOGGER.info( "-- Attempting to update a NetworkProfile." );

		StringBuilder msg = new StringBuilder( "Failed to update a NetworkProfile : " );        
		NetworkProfile entity = read();
		UpdateNetworkProfileCommand command = generateUpdateCommand();
		command.setNetworkProfileId(entity.getNetworkProfileId());

		try {            
			assertNotNull( entity, msg.toString() );

			LOGGER.info( "-- Now updating the created NetworkProfile." );

			// for use later on...
			networkProfileId = entity.getNetworkProfileId();

			NetworkProfileService proxy = NetworkProfileService.getNetworkProfileInstance();  

			proxy.updateNetworkProfile( command ).get();

			LOGGER.info( "-- Successfully saved NetworkProfile - " + entity.toString() );
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : primarykey = " + networkProfileId + " : command -" +  command + " : " + e );

			throw e;
		}
	}

	/** 
	 * delete a NetworkProfile.
	 */
	protected void delete() throws Throwable {
		LOGGER.info( "\n======== DELETE ======== ");
		LOGGER.info( "-- Deleting a previously created NetworkProfile." );

		NetworkProfile entity = null;
		
		try{
		    entity = read(); 
			LOGGER.info( "-- Successfully read NetworkProfile with id " + networkProfileId );            
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( "-- Failed to read NetworkProfile with id " + networkProfileId );

			throw e;
		}

		try{
			NetworkProfileService.getNetworkProfileInstance().delete( new DeleteNetworkProfileCommand( entity.getNetworkProfileId() ) ).get();
			LOGGER.info( "-- Successfully deleted NetworkProfile with id " + networkProfileId );            
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( "-- Failed to delete NetworkProfile with id " + networkProfileId );

			throw e;
		}
	}

	/**
	 * get all NetworkProfiles.
	 */
	protected List<NetworkProfile> getAll() throws Throwable {    
		LOGGER.info( "======== GETALL ======== ");
		LOGGER.info( "-- Retrieving Collection of NetworkProfiles:" );

		StringBuilder msg = new StringBuilder( "-- Failed to get all NetworkProfile : " );        
		List<NetworkProfile> collection  = new ArrayList<>();

		try {
			// call the static get method on the NetworkProfileService
			collection = NetworkProfileService.getNetworkProfileInstance().getAllNetworkProfile();
			assertNotNull( collection, "An Empty collection of NetworkProfile was incorrectly returned.");
			
			// Now print out the values
			NetworkProfile entity = null;            
			Iterator<NetworkProfile> iter = collection.iterator();
			int index = 1;

			while( iter.hasNext() ) {
				// Retrieve the entity   
				entity = iter.next();

				assertNotNull( entity,"-- null entity in Collection." );
				assertNotNull( entity.getNetworkProfileId(), "-- entity in Collection has a null primary key" );        

				LOGGER.info( " - " + String.valueOf(index) + ". " + entity.toString() );
				index++;
			}
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : " + e );

			throw e;
		}
		
		return collection;			
	}

	/**
	 * Assigns a common log handler for each test class in the suite 
	 * in the event log output needs to go elsewhere
	 * 
	 * @param		handler	Handler
	 * @return		NetworkProfileTest
	 */
	protected NetworkProfileTest setHandler(Handler handler) {
		if ( handler != null )
			LOGGER.addHandler(handler); 
		return this;
	}

	/**
	 * Returns a new populated NetworkProfile
	 * 
	 * @return CreateNetworkProfileCommand alias
	 */
	protected CreateNetworkProfileCommand generateNewCommand() {
        CreateNetworkProfileCommand command = new CreateNetworkProfileCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  ConnectivityType.values()[0] );
		
		return( command );
	}

		/**
		 * Returns a new populated NetworkProfile
		 * 
		 * @return UpdateNetworkProfileCommand alias
		 */
	protected UpdateNetworkProfileCommand generateUpdateCommand() {
	        UpdateNetworkProfileCommand command = new UpdateNetworkProfileCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  null,  null,  null,  ConnectivityType.values()[0] );
			
			return( command );
		}
	//-----------------------------------------------------
	// attributes 
	//-----------------------------------------------------
	protected UUID networkProfileId = null;
	protected NetworkProfileSubscriber subscriber = null;
	private final String unexpectedErrorMsg = ":::::::::::::: Unexpected Error :::::::::::::::::";
	private final Logger LOGGER = Logger.getLogger(NetworkProfileTest.class.getName());
	private String testingStep = "";
	private Integer sizeOfNetworkProfileList = 0;
}
