/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.springframework.util.Assert.state;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;
import com.harbormaster.subscriber.*;

/**
 * <h2>SiteTest</h2>
 * <p>
 * Junit test class for entity Site.  Handle the full lifecycle as it relates to persistence. Leverages
 * the SiteService and a SiteSubscriber to test everything under a MVC framework which includes the
 * SiteAggregate and related commands, queries, and events.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 * 		SiteService
 * 	    SiteSubscriber
 *
 * <h3>Methods</h3>
 *      <ul>
 *      <li>read</li>
 *      <li>update</li>
 *      <li>delete</li>
 *      </ul>
 *
 * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class SiteTest {

    // ------------------------------------
	// default constructor
    // ------------------------------------
	public SiteTest() {
		subscriber = new SiteSubscriber();
	}

	// test methods
	@Test
	/*
	 * Initiate SiteTest.
	 */
	public void startTest() throws Throwable {
		try {
			LOGGER.info("**********************************************************");
			LOGGER.info("Beginning test on Site...");
			LOGGER.info("**********************************************************\n");
			
			// ---------------------------------------------
			// jumpstart process
			// ---------------------------------------------
			jumpStart();
			
		} catch (Throwable e) {
			throw e;
		} finally {
		}
	}

	/** 
	 * jumpstart the process by instantiating2 Site
	 */
	protected void jumpStart() throws Throwable {
		LOGGER.info( "\n======== create instances to get the ball rolling  ======== ");

		siteId = SiteService.getSiteInstance()
		.createSite( generateNewCommand() )
		.get();

		// ---------------------------------------------
		// set up query subscriptions after the 1st create
		// ---------------------------------------------
		testingStep = "create";
		setUpQuerySubscriptions();

		SiteService.getSiteInstance()
				.createSite( generateNewCommand() )
				.get();

	}

	/** 
	 * Set up query subscriptions
	 */
	protected void setUpQuerySubscriptions() throws Throwable {
		LOGGER.info( "\n======== Setting Up Query Subscriptions ======== ");
			
		try {            
			subscriber.siteSubscribe().updates().subscribe(
					  successValue -> {
						  LOGGER.info(successValue.toString());
						  try {
							  LOGGER.info("GetAll update received for Site : " + successValue.getSiteId());
							  if (successValue.getSiteId().equals(siteId)) {
								  if (testingStep.equals("create")) {
									  testingStep = "update";
									  update();
								  } else if (testingStep.equals("delete")) {
									  testingStep = "complete";
									  state( getAll().size() == sizeOfSiteList - 1 , "value not deleted from list");
									  LOGGER.info("**********************************************************");
									  LOGGER.info("Site test completed successfully...");
									  LOGGER.info("**********************************************************\n");
								  }
							  }
						  } catch( Throwable exc ) {
							  LOGGER.warning( exc.getMessage() );
						  }
					  },
					  error -> LOGGER.warning(error.getMessage()),
					  () -> LOGGER.info("Subscription on site consumed")
					);
			subscriber.siteSubscribe( siteId ).updates().subscribe(
					  successValue -> {
						  LOGGER.info(successValue.toString());
						  try {
							  LOGGER.info("GetOne update received for Site : " + successValue.getSiteId() + " in step " + testingStep);
							  testingStep = "delete";
							  sizeOfSiteList = getAll().size();
							  delete();
						  } catch( Throwable exc ) {
							  LOGGER.warning( exc.getMessage() );
						  }
					  },
					  error -> LOGGER.warning(error.getMessage()),
					  () -> LOGGER.info("Subscription on site for siteId consumed")

					);
			

			}
			catch (Exception e) {
				LOGGER.warning( e.getMessage() );
				throw e;
			}
		}
		
		/** 
	 * read a Site. 
	 */
	protected Site read() throws Throwable {
		LOGGER.info( "\n======== READ ======== ");
		LOGGER.info( "-- Reading a previously created Site" );

		Site entity = null;
		StringBuilder msg = new StringBuilder( "-- Failed to read Site with primary key" );
		msg.append( siteId );
		
		SiteFetchOneSummary fetchOneSummary = new SiteFetchOneSummary( siteId );

		try {
			entity = SiteService.getSiteInstance().getSite( fetchOneSummary );

			assertNotNull( entity,msg.toString() );

			LOGGER.info( "-- Successfully found Site " + entity.toString() );
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : " + e );

			throw e;
		}
		
		return entity;
	}

	/** 
	 * updating a Site.
	 */
	protected void update() throws Throwable {
		LOGGER.info( "\n======== UPDATE ======== ");
		LOGGER.info( "-- Attempting to update a Site." );

		StringBuilder msg = new StringBuilder( "Failed to update a Site : " );        
		Site entity = read();
		UpdateSiteCommand command = generateUpdateCommand();
		command.setSiteId(entity.getSiteId());

		try {            
			assertNotNull( entity, msg.toString() );

			LOGGER.info( "-- Now updating the created Site." );

			// for use later on...
			siteId = entity.getSiteId();

			SiteService proxy = SiteService.getSiteInstance();  

			proxy.updateSite( command ).get();

			LOGGER.info( "-- Successfully saved Site - " + entity.toString() );
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : primarykey = " + siteId + " : command -" +  command + " : " + e );

			throw e;
		}
	}

	/** 
	 * delete a Site.
	 */
	protected void delete() throws Throwable {
		LOGGER.info( "\n======== DELETE ======== ");
		LOGGER.info( "-- Deleting a previously created Site." );

		Site entity = null;
		
		try{
		    entity = read(); 
			LOGGER.info( "-- Successfully read Site with id " + siteId );            
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( "-- Failed to read Site with id " + siteId );

			throw e;
		}

		try{
			SiteService.getSiteInstance().delete( new DeleteSiteCommand( entity.getSiteId() ) ).get();
			LOGGER.info( "-- Successfully deleted Site with id " + siteId );            
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( "-- Failed to delete Site with id " + siteId );

			throw e;
		}
	}

	/**
	 * get all Sites.
	 */
	protected List<Site> getAll() throws Throwable {    
		LOGGER.info( "======== GETALL ======== ");
		LOGGER.info( "-- Retrieving Collection of Sites:" );

		StringBuilder msg = new StringBuilder( "-- Failed to get all Site : " );        
		List<Site> collection  = new ArrayList<>();

		try {
			// call the static get method on the SiteService
			collection = SiteService.getSiteInstance().getAllSite();
			assertNotNull( collection, "An Empty collection of Site was incorrectly returned.");
			
			// Now print out the values
			Site entity = null;            
			Iterator<Site> iter = collection.iterator();
			int index = 1;

			while( iter.hasNext() ) {
				// Retrieve the entity   
				entity = iter.next();

				assertNotNull( entity,"-- null entity in Collection." );
				assertNotNull( entity.getSiteId(), "-- entity in Collection has a null primary key" );        

				LOGGER.info( " - " + String.valueOf(index) + ". " + entity.toString() );
				index++;
			}
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : " + e );

			throw e;
		}
		
		return collection;			
	}

	/**
	 * Assigns a common log handler for each test class in the suite 
	 * in the event log output needs to go elsewhere
	 * 
	 * @param		handler	Handler
	 * @return		SiteTest
	 */
	protected SiteTest setHandler(Handler handler) {
		if ( handler != null )
			LOGGER.addHandler(handler); 
		return this;
	}

	/**
	 * Returns a new populated Site
	 * 
	 * @return CreateSiteCommand alias
	 */
	protected CreateSiteCommand generateNewCommand() {
        CreateSiteCommand command = new CreateSiteCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  new Address(),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  java.math.BigDecimal.ZERO,  java.math.BigDecimal.ZERO );
		
		return( command );
	}

		/**
		 * Returns a new populated Site
		 * 
		 * @return UpdateSiteCommand alias
		 */
	protected UpdateSiteCommand generateUpdateCommand() {
	        UpdateSiteCommand command = new UpdateSiteCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  new Address(),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  java.math.BigDecimal.ZERO,  java.math.BigDecimal.ZERO,  null,  new HashSet<>(),  new HashSet<>(),  new HashSet<>() );
			
			return( command );
		}
	//-----------------------------------------------------
	// attributes 
	//-----------------------------------------------------
	protected UUID siteId = null;
	protected SiteSubscriber subscriber = null;
	private final String unexpectedErrorMsg = ":::::::::::::: Unexpected Error :::::::::::::::::";
	private final Logger LOGGER = Logger.getLogger(SiteTest.class.getName());
	private String testingStep = "";
	private Integer sizeOfSiteList = 0;
}
