#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
#()
#------------------------------------------------------------------------------
# app level inclusions
#------------------------------------------------------------------------------
main.go=.bankingOnGolang
Dockerfile=.
.env=.bankingOnGolang,.internal.test

#------------------------------------------------------------------------------
# api level inclusions
#------------------------------------------------------------------------------
utils.go=.bankingOnGolang.internal.utils

BaseModel.go=.bankingOnGolang.internal.model
__classes__.go=.bankingOnGolang.internal.model
enums.go=.bankingOnGolang.internal.model
valueObjects.go=.bankingOnGolang.internal.model
ForRequestApi.go=.bankingOnGolang.internal.model

router.go=.bankingOnGolang.internal.router

__classes__DAO.go=.bankingOnGolang.internal.dao

__classes__Controller.go=.bankingOnGolang.internal.controller
PulseIndicatorController__.go=.bankingOnGolang.internal.controller

Tester_test.go=.bankingOnGolang.internal.test

json.go=.bankingOnGolang.internal.response
jsonResponseFormatter.go=.bankingOnGolang.internal.response

#------------------------------------------------------------------------------
# CI/CD Platforms
#------------------------------------------------------------------------------
#buddy.yml=

#------------------------------------------------------------------------------
# exclusions
#------------------------------------------------------------------------------ 
exclusions=mappings.properties,options.json,blueprint.json