#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
#()
#------------------------------------------------------------------------------
# app level inclusions
#------------------------------------------------------------------------------
main.go=.demo
Dockerfile=.
.env=.demo,.internal.test

#------------------------------------------------------------------------------
# api level inclusions
#------------------------------------------------------------------------------
utils.go=.demo.internal.utils
__classes__.go=.demo.internal.model
enums.go=.demo.internal.model
router.go=.demo.internal.router
__classes__DAO.go=.demo.internal.dao
__classes__Controller.go=.demo.internal.controller
PulseIndicatorController__.go=.demo.internal.controller
Tester_test.go=.demo.internal.test
json.go=.demo.internal.response
jsonResponseFormatter.go=.demo.internal.response

#------------------------------------------------------------------------------
# CI/CD Platforms
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# exclusions
#------------------------------------------------------------------------------ 
exclusions=mappings.properties,options.json,blueprint.json