
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * Insurance Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace insuranceonaspdotnet.Domain;

/// <summary>
/// ExposureStatus enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum ExposureStatus
{
    Open=1,Closed=2,Pending=3,Reserved=4
}

/// <summary>
/// Extension of capabilities for the ExposureStatus enum
/// </summary>
public static class ExposureStatusExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<ExposureStatus> GetValues()
    {
        return Enum.GetValues<ExposureStatus>().ToList();
    }

    public static ExposureStatus GetDefaultValue()
    {
        return Enum.GetValues<ExposureStatus>().First();
    }

    public static ExposureStatus WhichOne(string name)
    {
        if (Enum.TryParse<ExposureStatus>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



