
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * Insurance Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace insuranceonaspdotnet.Domain;

/// <summary>
/// UnderwritingDecisionType enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum UnderwritingDecisionType
{
    Approve=1,ConditionalApprove=2,Refer=3,Decline=4
}

/// <summary>
/// Extension of capabilities for the UnderwritingDecisionType enum
/// </summary>
public static class UnderwritingDecisionTypeExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<UnderwritingDecisionType> GetValues()
    {
        return Enum.GetValues<UnderwritingDecisionType>().ToList();
    }

    public static UnderwritingDecisionType GetDefaultValue()
    {
        return Enum.GetValues<UnderwritingDecisionType>().First();
    }

    public static UnderwritingDecisionType WhichOne(string name)
    {
        if (Enum.TryParse<UnderwritingDecisionType>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



