/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Insurance Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.springframework.stereotype.Component;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;

/**
 * Test Application class.
 *
 * @author    Harbormaster Dev Team
 */
@Component
public class ApplicationTest
{

// constructors

    public ApplicationTest(ApplicationService service)
    {
        this.service = service;
        LOGGER.setUseParentHandlers(false);	// only want to output to the provided LogHandler
    }

// test methods
    @Test
    /**
     * Full Create-Read-Update-Delete of a Application, through a ApplicationTest.
     */
    public void testCRUD() throws Throwable {
    try {
        LOGGER.info( "**********************************************************" );
        LOGGER.info( "Beginning full test on ApplicationTest..." );

        testCreate();
        testRead();
        testUpdate();
        testGetAll();
        testDelete();

        LOGGER.info( "Successfully ran a full test on ApplicationTest..." );
        LOGGER.info( "**********************************************************" );
        LOGGER.info( "" );
    }
    catch( Throwable e ) {
        throw e;
    }
    finally  {
        if ( handler != null ) {
            handler.flush();
            LOGGER.removeHandler(handler);
        }
    }
}

    /**
     * Tests creating a new Application.
     *
     * @return    Application
     */
    public Application testCreate() throws Throwable {
    Application entity = null;

    LOGGER.info( "ApplicationTest:testCreate()" );
    LOGGER.info( "-- Attempting to create a Application");

    StringBuilder msg = new StringBuilder( "-- Failed to create a Application" );

    try {
        entity = service.createApplication( generateNewCommand() );
        assertNotNull( entity, msg.toString() );

        theId = entity.getApplicationId();
        assertNotNull( theId, msg.toString() + " Contains a null primary key" );

        LOGGER.info( "-- Successfully created a Application with primary key" + theId );
    }
    catch (Exception e)  {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() + entity );

        throw e;
    }
    return entity;
}

    /**
     * Tests reading a Application.
     *
     * @return    Application
     */
    public Application testRead() throws Throwable {
    LOGGER.info( "ApplicationTest:testRead()" );
    LOGGER.info( "-- Reading a previously created Application" );

    Application entity = null;
    StringBuilder msg = new StringBuilder( "-- Failed to read Application with primary key" );
    msg.append( theId );

    try {
        entity = service.getApplication( new ApplicationFetchOneSummary(theId) );

        assertNotNull( entity,msg.toString() );

        // for use later
        theId = entity.getApplicationId();

        LOGGER.info( "-- Successfully found Application " + entity.toString() );
    }
    catch ( Throwable e ) {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() + " : " + e );

        throw e;
    }

    return( entity );
}

    /**
     * Tests updating a Application.
     *
     * @return    Application
     */
    public Application testUpdate() throws Throwable {
    LOGGER.info( "ApplicationTest:testUpdate()" );
    LOGGER.info( "-- Attempting to update a Application." );

    StringBuilder msg = new StringBuilder( "Failed to update a Application : " );
    Application entity = null;

    try {
        UpdateApplicationCommand updateCommand = this.generateUpdateCommand();

        // apply the current id as to update the fields of the current entity
        updateCommand.setApplicationId( theId );

        assertNotNull( updateCommand, msg.toString() );

        LOGGER.info( "-- Now updating the created Application." );

        entity = service.updateApplication( updateCommand );

        assertNotNull( entity, msg.toString()  );

        LOGGER.info( "-- Successfully saved Application - " + entity.toString() );
    }
    catch ( Throwable e ) {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() + " : primarykey-" + theId + " : entity-" +  entity + " : " + e );

        throw e;
    }

    return( entity );
}

    /**
     * Tests deleting a Application.
     */
    public void testDelete() throws Throwable {
    LOGGER.info( "ApplicationTest:testDelete()" );
    LOGGER.info( "-- Deleting a previously created Application." );

    try {
        DeleteApplicationCommand deleteCommand = new DeleteApplicationCommand( theId );

        service.delete( deleteCommand );

        LOGGER.info( "-- Successfully deleted Application with primary key " + theId );
    }
    catch ( Throwable e ) {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( "-- Failed to delete Application with primary key " + theId );

        throw e;
    }
}

    /**
     * Tests getting all Applications.
     *
     * @return    Collection
     */
    public List<Application> testGetAll() throws Throwable {
    LOGGER.info( "ApplicationTest:testGetAll() - Retrieving Collection of Applications:" );

    StringBuilder msg = new StringBuilder( "-- Failed to get all Application : " );
    List<Application> collection  = null;

    try {
        // call the static get method on the ApplicationService
        collection = service.getAllApplication();

        if ( collection == null || collection.size() == 0 ) {
            LOGGER.warning( unexpectedErrorMsg );
            LOGGER.warning( "-- " + msg.toString() + " Empty collection returned."  );
        }
        else {
            // Now print out the values
            Application currEntity  = null;
            Iterator<Application> iter = collection.iterator();

            while( iter.hasNext() ) {
                // Retrieve the entity
                currEntity = iter.next();

                assertNotNull( currEntity,"-- null value object in Collection." );
                assertNotNull( currEntity.getApplicationId(), "-- value object in Collection has a null primary key" );

                LOGGER.info( " - " + currEntity.toString() );
            }
        }
    }
    catch ( Throwable e ){
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() );

        throw e;
    }

    return( collection );
}

    public ApplicationTest setHandler( Handler handler ) {
    this.handler = handler;
    LOGGER.addHandler(handler);	// assign so the LOGGER can only output results to the Handler
    return this;
}


    /**
     * Returns a new populated Application
     *
     * @return CreateApplicationCommand alias
     */
	protected CreateApplicationCommand generateNewCommand() {
    CreateApplicationCommand command = new CreateApplicationCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),   new Date(),  ApplicationStatus.values()[0] );

    return( command );
}

    /**
     * Returns a new populated Application
     *
     * @return UpdateApplicationCommand alias
     */
	protected UpdateApplicationCommand generateUpdateCommand() {
    UpdateApplicationCommand command = new UpdateApplicationCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),   new Date(),  null,  null,  null,  new HashSet<>(),  null,  ApplicationStatus.values()[0] );

    return( command );
}
    //----

// attributes

    protected UUID theId  = null;
    protected ApplicationService service = null;
    private Handler handler = null;
    private String unexpectedErrorMsg = ":::::::::::::: Unexpected Error :::::::::::::::::";
    private final Logger LOGGER = Logger.getLogger(Application.class.getName());

}
