
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.springframework.stereotype.Component;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;

/**
 * Test ConnectivityPlan class.
 *
 * @author    Harbormaster Dev Team
 */
@Component
public class ConnectivityPlanTest
{

// constructors

    public ConnectivityPlanTest(ConnectivityPlanService service)
    {
        this.service = service;
        LOGGER.setUseParentHandlers(false);	// only want to output to the provided LogHandler
    }

// test methods
    @Test
    /**
     * Full Create-Read-Update-Delete of a ConnectivityPlan, through a ConnectivityPlanTest.
     */
    public void testCRUD() throws Throwable {
    try {
        LOGGER.info( "**********************************************************" );
        LOGGER.info( "Beginning full test on ConnectivityPlanTest..." );

        testCreate();
        testRead();
        testUpdate();
        testGetAll();
        testDelete();

        LOGGER.info( "Successfully ran a full test on ConnectivityPlanTest..." );
        LOGGER.info( "**********************************************************" );
        LOGGER.info( "" );
    }
    catch( Throwable e ) {
        throw e;
    }
    finally  {
        if ( handler != null ) {
            handler.flush();
            LOGGER.removeHandler(handler);
        }
    }
}

    /**
     * Tests creating a new ConnectivityPlan.
     *
     * @return    ConnectivityPlan
     */
    public ConnectivityPlan testCreate() throws Throwable {
    ConnectivityPlan entity = null;

    LOGGER.info( "ConnectivityPlanTest:testCreate()" );
    LOGGER.info( "-- Attempting to create a ConnectivityPlan");

    StringBuilder msg = new StringBuilder( "-- Failed to create a ConnectivityPlan" );

    try {
        entity = service.createConnectivityPlan( generateNewCommand() );
        assertNotNull( entity, msg.toString() );

        theId = entity.getConnectivityPlanId();
        assertNotNull( theId, msg.toString() + " Contains a null primary key" );

        LOGGER.info( "-- Successfully created a ConnectivityPlan with primary key" + theId );
    }
    catch (Exception e)  {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() + entity );

        throw e;
    }
    return entity;
}

    /**
     * Tests reading a ConnectivityPlan.
     *
     * @return    ConnectivityPlan
     */
    public ConnectivityPlan testRead() throws Throwable {
    LOGGER.info( "ConnectivityPlanTest:testRead()" );
    LOGGER.info( "-- Reading a previously created ConnectivityPlan" );

    ConnectivityPlan entity = null;
    StringBuilder msg = new StringBuilder( "-- Failed to read ConnectivityPlan with primary key" );
    msg.append( theId );

    try {
        entity = service.getConnectivityPlan( new ConnectivityPlanFetchOneSummary(theId) );

        assertNotNull( entity,msg.toString() );

        // for use later
        theId = entity.getConnectivityPlanId();

        LOGGER.info( "-- Successfully found ConnectivityPlan " + entity.toString() );
    }
    catch ( Throwable e ) {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() + " : " + e );

        throw e;
    }

    return( entity );
}

    /**
     * Tests updating a ConnectivityPlan.
     *
     * @return    ConnectivityPlan
     */
    public ConnectivityPlan testUpdate() throws Throwable {
    LOGGER.info( "ConnectivityPlanTest:testUpdate()" );
    LOGGER.info( "-- Attempting to update a ConnectivityPlan." );

    StringBuilder msg = new StringBuilder( "Failed to update a ConnectivityPlan : " );
    ConnectivityPlan entity = null;

    try {
        UpdateConnectivityPlanCommand updateCommand = this.generateUpdateCommand();

        // apply the current id as to update the fields of the current entity
        updateCommand.setConnectivityPlanId( theId );

        assertNotNull( updateCommand, msg.toString() );

        LOGGER.info( "-- Now updating the created ConnectivityPlan." );

        entity = service.updateConnectivityPlan( updateCommand );

        assertNotNull( entity, msg.toString()  );

        LOGGER.info( "-- Successfully saved ConnectivityPlan - " + entity.toString() );
    }
    catch ( Throwable e ) {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() + " : primarykey-" + theId + " : entity-" +  entity + " : " + e );

        throw e;
    }

    return( entity );
}

    /**
     * Tests deleting a ConnectivityPlan.
     */
    public void testDelete() throws Throwable {
    LOGGER.info( "ConnectivityPlanTest:testDelete()" );
    LOGGER.info( "-- Deleting a previously created ConnectivityPlan." );

    try {
        DeleteConnectivityPlanCommand deleteCommand = new DeleteConnectivityPlanCommand( theId );

        service.delete( deleteCommand );

        LOGGER.info( "-- Successfully deleted ConnectivityPlan with primary key " + theId );
    }
    catch ( Throwable e ) {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( "-- Failed to delete ConnectivityPlan with primary key " + theId );

        throw e;
    }
}

    /**
     * Tests getting all ConnectivityPlans.
     *
     * @return    Collection
     */
    public List<ConnectivityPlan> testGetAll() throws Throwable {
    LOGGER.info( "ConnectivityPlanTest:testGetAll() - Retrieving Collection of ConnectivityPlans:" );

    StringBuilder msg = new StringBuilder( "-- Failed to get all ConnectivityPlan : " );
    List<ConnectivityPlan> collection  = null;

    try {
        // call the static get method on the ConnectivityPlanService
        collection = service.getAllConnectivityPlan();

        if ( collection == null || collection.size() == 0 ) {
            LOGGER.warning( unexpectedErrorMsg );
            LOGGER.warning( "-- " + msg.toString() + " Empty collection returned."  );
        }
        else {
            // Now print out the values
            ConnectivityPlan currEntity  = null;
            Iterator<ConnectivityPlan> iter = collection.iterator();

            while( iter.hasNext() ) {
                // Retrieve the entity
                currEntity = iter.next();

                assertNotNull( currEntity,"-- null value object in Collection." );
                assertNotNull( currEntity.getConnectivityPlanId(), "-- value object in Collection has a null primary key" );

                LOGGER.info( " - " + currEntity.toString() );
            }
        }
    }
    catch ( Throwable e ){
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() );

        throw e;
    }

    return( collection );
}

    public ConnectivityPlanTest setHandler( Handler handler ) {
    this.handler = handler;
    LOGGER.addHandler(handler);	// assign so the LOGGER can only output results to the Handler
    return this;
}


    /**
     * Returns a new populated ConnectivityPlan
     *
     * @return CreateConnectivityPlanCommand alias
     */
	protected CreateConnectivityPlanCommand generateNewCommand() {
    CreateConnectivityPlanCommand command = new CreateConnectivityPlanCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  0,  0 );

    return( command );
}

    /**
     * Returns a new populated ConnectivityPlan
     *
     * @return UpdateConnectivityPlanCommand alias
     */
	protected UpdateConnectivityPlanCommand generateUpdateCommand() {
    UpdateConnectivityPlanCommand command = new UpdateConnectivityPlanCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  0,  0,  new HashSet<>(),  null );

    return( command );
}
    //----

// attributes

    protected UUID theId  = null;
    protected ConnectivityPlanService service = null;
    private Handler handler = null;
    private String unexpectedErrorMsg = ":::::::::::::: Unexpected Error :::::::::::::::::";
    private final Logger LOGGER = Logger.getLogger(ConnectivityPlan.class.getName());

}
