/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.springframework.stereotype.Component;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;

/**
 * Test FundsTransfer class.
 *
 * @author    Harbormaster Dev Team
 */
@Component
public class FundsTransferTest
{

// constructors

    public FundsTransferTest(FundsTransferService service)
    {
        this.service = service;
        LOGGER.setUseParentHandlers(false);	// only want to output to the provided LogHandler
    }

// test methods
    @Test
    /**
     * Full Create-Read-Update-Delete of a FundsTransfer, through a FundsTransferTest.
     */
    public void testCRUD() throws Throwable {
    try {
        LOGGER.info( "**********************************************************" );
        LOGGER.info( "Beginning full test on FundsTransferTest..." );

        testCreate();
        testRead();
        testUpdate();
        testGetAll();
        testDelete();

        LOGGER.info( "Successfully ran a full test on FundsTransferTest..." );
        LOGGER.info( "**********************************************************" );
        LOGGER.info( "" );
    }
    catch( Throwable e ) {
        throw e;
    }
    finally  {
        if ( handler != null ) {
            handler.flush();
            LOGGER.removeHandler(handler);
        }
    }
}

    /**
     * Tests creating a new FundsTransfer.
     *
     * @return    FundsTransfer
     */
    public FundsTransfer testCreate() throws Throwable {
    FundsTransfer entity = null;

    LOGGER.info( "FundsTransferTest:testCreate()" );
    LOGGER.info( "-- Attempting to create a FundsTransfer");

    StringBuilder msg = new StringBuilder( "-- Failed to create a FundsTransfer" );

    try {
        entity = service.createFundsTransfer( generateNewCommand() );
        assertNotNull( entity, msg.toString() );

        theId = entity.getFundsTransferId();
        assertNotNull( theId, msg.toString() + " Contains a null primary key" );

        LOGGER.info( "-- Successfully created a FundsTransfer with primary key" + theId );
    }
    catch (Exception e)  {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() + entity );

        throw e;
    }
    return entity;
}

    /**
     * Tests reading a FundsTransfer.
     *
     * @return    FundsTransfer
     */
    public FundsTransfer testRead() throws Throwable {
    LOGGER.info( "FundsTransferTest:testRead()" );
    LOGGER.info( "-- Reading a previously created FundsTransfer" );

    FundsTransfer entity = null;
    StringBuilder msg = new StringBuilder( "-- Failed to read FundsTransfer with primary key" );
    msg.append( theId );

    try {
        entity = service.getFundsTransfer( new FundsTransferFetchOneSummary(theId) );

        assertNotNull( entity,msg.toString() );

        // for use later
        theId = entity.getFundsTransferId();

        LOGGER.info( "-- Successfully found FundsTransfer " + entity.toString() );
    }
    catch ( Throwable e ) {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() + " : " + e );

        throw e;
    }

    return( entity );
}

    /**
     * Tests updating a FundsTransfer.
     *
     * @return    FundsTransfer
     */
    public FundsTransfer testUpdate() throws Throwable {
    LOGGER.info( "FundsTransferTest:testUpdate()" );
    LOGGER.info( "-- Attempting to update a FundsTransfer." );

    StringBuilder msg = new StringBuilder( "Failed to update a FundsTransfer : " );
    FundsTransfer entity = null;

    try {
        UpdateFundsTransferCommand updateCommand = this.generateUpdateCommand();

        // apply the current id as to update the fields of the current entity
        updateCommand.setFundsTransferId( theId );

        assertNotNull( updateCommand, msg.toString() );

        LOGGER.info( "-- Now updating the created FundsTransfer." );

        entity = service.updateFundsTransfer( updateCommand );

        assertNotNull( entity, msg.toString()  );

        LOGGER.info( "-- Successfully saved FundsTransfer - " + entity.toString() );
    }
    catch ( Throwable e ) {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() + " : primarykey-" + theId + " : entity-" +  entity + " : " + e );

        throw e;
    }

    return( entity );
}

    /**
     * Tests deleting a FundsTransfer.
     */
    public void testDelete() throws Throwable {
    LOGGER.info( "FundsTransferTest:testDelete()" );
    LOGGER.info( "-- Deleting a previously created FundsTransfer." );

    try {
        DeleteFundsTransferCommand deleteCommand = new DeleteFundsTransferCommand( theId );

        service.delete( deleteCommand );

        LOGGER.info( "-- Successfully deleted FundsTransfer with primary key " + theId );
    }
    catch ( Throwable e ) {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( "-- Failed to delete FundsTransfer with primary key " + theId );

        throw e;
    }
}

    /**
     * Tests getting all FundsTransfers.
     *
     * @return    Collection
     */
    public List<FundsTransfer> testGetAll() throws Throwable {
    LOGGER.info( "FundsTransferTest:testGetAll() - Retrieving Collection of FundsTransfers:" );

    StringBuilder msg = new StringBuilder( "-- Failed to get all FundsTransfer : " );
    List<FundsTransfer> collection  = null;

    try {
        // call the static get method on the FundsTransferService
        collection = service.getAllFundsTransfer();

        if ( collection == null || collection.size() == 0 ) {
            LOGGER.warning( unexpectedErrorMsg );
            LOGGER.warning( "-- " + msg.toString() + " Empty collection returned."  );
        }
        else {
            // Now print out the values
            FundsTransfer currEntity  = null;
            Iterator<FundsTransfer> iter = collection.iterator();

            while( iter.hasNext() ) {
                // Retrieve the entity
                currEntity = iter.next();

                assertNotNull( currEntity,"-- null value object in Collection." );
                assertNotNull( currEntity.getFundsTransferId(), "-- value object in Collection has a null primary key" );

                LOGGER.info( " - " + currEntity.toString() );
            }
        }
    }
    catch ( Throwable e ){
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() );

        throw e;
    }

    return( collection );
}

    public FundsTransferTest setHandler( Handler handler ) {
    this.handler = handler;
    LOGGER.addHandler(handler);	// assign so the LOGGER can only output results to the Handler
    return this;
}


    /**
     * Returns a new populated FundsTransfer
     *
     * @return CreateFundsTransferCommand alias
     */
	protected CreateFundsTransferCommand generateNewCommand() {
    CreateFundsTransferCommand command = new CreateFundsTransferCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  new Money(),   new Date(),   new Date(),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  new Money(),  PaymentMethod.values()[0],  PaymentStatus.values()[0] );

    return( command );
}

    /**
     * Returns a new populated FundsTransfer
     *
     * @return UpdateFundsTransferCommand alias
     */
	protected UpdateFundsTransferCommand generateUpdateCommand() {
    UpdateFundsTransferCommand command = new UpdateFundsTransferCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  new Money(),   new Date(),   new Date(),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  new Money(),  null,  null,  null,  null,  new HashSet<>(),  PaymentMethod.values()[0],  PaymentStatus.values()[0] );

    return( command );
}
    //----

// attributes

    protected UUID theId  = null;
    protected FundsTransferService service = null;
    private Handler handler = null;
    private String unexpectedErrorMsg = ":::::::::::::: Unexpected Error :::::::::::::::::";
    private final Logger LOGGER = Logger.getLogger(FundsTransfer.class.getName());

}
