
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.springframework.stereotype.Component;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;

/**
 * Test SoftwareUpdateCampaign class.
 *
 * @author    Harbormaster Dev Team
 */
@Component
public class SoftwareUpdateCampaignTest
{

// constructors

    public SoftwareUpdateCampaignTest(SoftwareUpdateCampaignService service)
    {
        this.service = service;
        LOGGER.setUseParentHandlers(false);	// only want to output to the provided LogHandler
    }

// test methods
    @Test
    /**
     * Full Create-Read-Update-Delete of a SoftwareUpdateCampaign, through a SoftwareUpdateCampaignTest.
     */
    public void testCRUD() throws Throwable {
    try {
        LOGGER.info( "**********************************************************" );
        LOGGER.info( "Beginning full test on SoftwareUpdateCampaignTest..." );

        testCreate();
        testRead();
        testUpdate();
        testGetAll();
        testDelete();

        LOGGER.info( "Successfully ran a full test on SoftwareUpdateCampaignTest..." );
        LOGGER.info( "**********************************************************" );
        LOGGER.info( "" );
    }
    catch( Throwable e ) {
        throw e;
    }
    finally  {
        if ( handler != null ) {
            handler.flush();
            LOGGER.removeHandler(handler);
        }
    }
}

    /**
     * Tests creating a new SoftwareUpdateCampaign.
     *
     * @return    SoftwareUpdateCampaign
     */
    public SoftwareUpdateCampaign testCreate() throws Throwable {
    SoftwareUpdateCampaign entity = null;

    LOGGER.info( "SoftwareUpdateCampaignTest:testCreate()" );
    LOGGER.info( "-- Attempting to create a SoftwareUpdateCampaign");

    StringBuilder msg = new StringBuilder( "-- Failed to create a SoftwareUpdateCampaign" );

    try {
        entity = service.createSoftwareUpdateCampaign( generateNewCommand() );
        assertNotNull( entity, msg.toString() );

        theId = entity.getSoftwareUpdateCampaignId();
        assertNotNull( theId, msg.toString() + " Contains a null primary key" );

        LOGGER.info( "-- Successfully created a SoftwareUpdateCampaign with primary key" + theId );
    }
    catch (Exception e)  {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() + entity );

        throw e;
    }
    return entity;
}

    /**
     * Tests reading a SoftwareUpdateCampaign.
     *
     * @return    SoftwareUpdateCampaign
     */
    public SoftwareUpdateCampaign testRead() throws Throwable {
    LOGGER.info( "SoftwareUpdateCampaignTest:testRead()" );
    LOGGER.info( "-- Reading a previously created SoftwareUpdateCampaign" );

    SoftwareUpdateCampaign entity = null;
    StringBuilder msg = new StringBuilder( "-- Failed to read SoftwareUpdateCampaign with primary key" );
    msg.append( theId );

    try {
        entity = service.getSoftwareUpdateCampaign( new SoftwareUpdateCampaignFetchOneSummary(theId) );

        assertNotNull( entity,msg.toString() );

        // for use later
        theId = entity.getSoftwareUpdateCampaignId();

        LOGGER.info( "-- Successfully found SoftwareUpdateCampaign " + entity.toString() );
    }
    catch ( Throwable e ) {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() + " : " + e );

        throw e;
    }

    return( entity );
}

    /**
     * Tests updating a SoftwareUpdateCampaign.
     *
     * @return    SoftwareUpdateCampaign
     */
    public SoftwareUpdateCampaign testUpdate() throws Throwable {
    LOGGER.info( "SoftwareUpdateCampaignTest:testUpdate()" );
    LOGGER.info( "-- Attempting to update a SoftwareUpdateCampaign." );

    StringBuilder msg = new StringBuilder( "Failed to update a SoftwareUpdateCampaign : " );
    SoftwareUpdateCampaign entity = null;

    try {
        UpdateSoftwareUpdateCampaignCommand updateCommand = this.generateUpdateCommand();

        // apply the current id as to update the fields of the current entity
        updateCommand.setSoftwareUpdateCampaignId( theId );

        assertNotNull( updateCommand, msg.toString() );

        LOGGER.info( "-- Now updating the created SoftwareUpdateCampaign." );

        entity = service.updateSoftwareUpdateCampaign( updateCommand );

        assertNotNull( entity, msg.toString()  );

        LOGGER.info( "-- Successfully saved SoftwareUpdateCampaign - " + entity.toString() );
    }
    catch ( Throwable e ) {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() + " : primarykey-" + theId + " : entity-" +  entity + " : " + e );

        throw e;
    }

    return( entity );
}

    /**
     * Tests deleting a SoftwareUpdateCampaign.
     */
    public void testDelete() throws Throwable {
    LOGGER.info( "SoftwareUpdateCampaignTest:testDelete()" );
    LOGGER.info( "-- Deleting a previously created SoftwareUpdateCampaign." );

    try {
        DeleteSoftwareUpdateCampaignCommand deleteCommand = new DeleteSoftwareUpdateCampaignCommand( theId );

        service.delete( deleteCommand );

        LOGGER.info( "-- Successfully deleted SoftwareUpdateCampaign with primary key " + theId );
    }
    catch ( Throwable e ) {
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( "-- Failed to delete SoftwareUpdateCampaign with primary key " + theId );

        throw e;
    }
}

    /**
     * Tests getting all SoftwareUpdateCampaigns.
     *
     * @return    Collection
     */
    public List<SoftwareUpdateCampaign> testGetAll() throws Throwable {
    LOGGER.info( "SoftwareUpdateCampaignTest:testGetAll() - Retrieving Collection of SoftwareUpdateCampaigns:" );

    StringBuilder msg = new StringBuilder( "-- Failed to get all SoftwareUpdateCampaign : " );
    List<SoftwareUpdateCampaign> collection  = null;

    try {
        // call the static get method on the SoftwareUpdateCampaignService
        collection = service.getAllSoftwareUpdateCampaign();

        if ( collection == null || collection.size() == 0 ) {
            LOGGER.warning( unexpectedErrorMsg );
            LOGGER.warning( "-- " + msg.toString() + " Empty collection returned."  );
        }
        else {
            // Now print out the values
            SoftwareUpdateCampaign currEntity  = null;
            Iterator<SoftwareUpdateCampaign> iter = collection.iterator();

            while( iter.hasNext() ) {
                // Retrieve the entity
                currEntity = iter.next();

                assertNotNull( currEntity,"-- null value object in Collection." );
                assertNotNull( currEntity.getSoftwareUpdateCampaignId(), "-- value object in Collection has a null primary key" );

                LOGGER.info( " - " + currEntity.toString() );
            }
        }
    }
    catch ( Throwable e ){
        LOGGER.warning( unexpectedErrorMsg );
        LOGGER.warning( msg.toString() );

        throw e;
    }

    return( collection );
}

    public SoftwareUpdateCampaignTest setHandler( Handler handler ) {
    this.handler = handler;
    LOGGER.addHandler(handler);	// assign so the LOGGER can only output results to the Handler
    return this;
}


    /**
     * Returns a new populated SoftwareUpdateCampaign
     *
     * @return CreateSoftwareUpdateCampaignCommand alias
     */
	protected CreateSoftwareUpdateCampaignCommand generateNewCommand() {
    CreateSoftwareUpdateCampaignCommand command = new CreateSoftwareUpdateCampaignCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),   new Date(),   new Date(),  UpdateCampaignStatus.values()[0] );

    return( command );
}

    /**
     * Returns a new populated SoftwareUpdateCampaign
     *
     * @return UpdateSoftwareUpdateCampaignCommand alias
     */
	protected UpdateSoftwareUpdateCampaignCommand generateUpdateCommand() {
    UpdateSoftwareUpdateCampaignCommand command = new UpdateSoftwareUpdateCampaignCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),   new Date(),   new Date(),  null,  null,  new HashSet<>(),  UpdateCampaignStatus.values()[0] );

    return( command );
}
    //----

// attributes

    protected UUID theId  = null;
    protected SoftwareUpdateCampaignService service = null;
    private Handler handler = null;
    private String unexpectedErrorMsg = ":::::::::::::: Unexpected Error :::::::::::::::::";
    private final Logger LOGGER = Logger.getLogger(SoftwareUpdateCampaign.class.getName());

}
