
package com.harbormaster.command;

import java.util.*;

import org.axonframework.modelling.command.Repository;

import org.axonframework.commandhandling.CommandHandler;
import org.springframework.stereotype.Component;

import com.harbormaster.aggregate.*;
import com.harbormaster.api.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;

/**
 * Command handler for DeviceCertificate as outlined for the CQRS pattern.  All creates, updates, deletes and other writes 
 * related to DeviceCertificate are handled here as external events are delegated to an associated Aggregate.
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * Services Used
 *
 *  	Repository<DeviceCertificateAggregate>
 *
 * Produces
 *
 *      application/json
 *
 * Commands Accepted
 *
 *      CreateDeviceCertificateCommand
 *      UpdateDeviceCertificateCommand
 *      DeleteDeviceCertificateCommand
 *
 * @author Harbormaster Dev Team
 *
 */
@Component
class DeviceCertificateCommandHandler {

    public DeviceCertificateCommandHandler( Repository<DeviceCertificateAggregate> repository ) {
    	super();
    	this.aggregateRepository = repository;	
    }
    
    @CommandHandler
    public void handle(CreateDeviceCertificateCommand command) throws Exception {
    	
    	// --------------------------------------
    	// validate the create command
    	// --------------------------------------    	
		DeviceCertificateValidator.getInstance().validate( command );
		
    	// --------------------------------------
    	// delegate to the aggregate
    	// -------------------------------------- 
    	aggregateRepository.newInstance(() -> new DeviceCertificateAggregate(command));
    }


    @CommandHandler
    public void handle(UpdateDeviceCertificateCommand command) throws Exception {
    	// --------------------------------------
    	// validate the update command
    	// --------------------------------------    	
		DeviceCertificateValidator.getInstance().validate( command );

    	// --------------------------------------
    	// delegate to the aggregate
    	// --------------------------------------
    	aggregateRepository.newInstance(() -> new DeviceCertificateAggregate(command));
    }

    
    @CommandHandler
    public void handle(DeleteDeviceCertificateCommand command) throws Exception {
    	// --------------------------------------
    	// validate the delete command
    	// --------------------------------------    	
		DeviceCertificateValidator.getInstance().validate( command );    
		
    	// --------------------------------------
    	// delegate to the aggregate
    	// --------------------------------------
    	aggregateRepository.newInstance(() -> new DeviceCertificateAggregate(command));
    }
    
    // attributes
    private final Repository<DeviceCertificateAggregate> aggregateRepository;
}