/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.api;

// --------------------------------------------
// enum declarations
// --------------------------------------------

// --------------------------------------------
// enum ConnectivityType
// --------------------------------------------
enum class ConnectivityType {
    WiFi, Ethernet, LTE, FiveG, NBIoT, LoRaWAN, Zigbee, BLE, Satellite
}


// --------------------------------------------
// enum DeviceStatus
// --------------------------------------------
enum class DeviceStatus {
    Provisioning, Active, Suspended, Offline, Decommissioned
}


// --------------------------------------------
// enum TelemetryEncoding
// --------------------------------------------
enum class TelemetryEncoding {
    JSON, CBOR, Protobuf, Avro, Binary
}


// --------------------------------------------
// enum MessageQoS
// --------------------------------------------
enum class MessageQoS {
    AtMostOnce, AtLeastOnce, ExactlyOnce
}


// --------------------------------------------
// enum CertificateType
// --------------------------------------------
enum class CertificateType {
    X509, X509_CA, X509_SelfSigned
}


// --------------------------------------------
// enum ProvisioningMethod
// --------------------------------------------
enum class ProvisioningMethod {
    Manual, JITP, JITR, Bulk, ZeroTouch
}


// --------------------------------------------
// enum ProvisioningStatus
// --------------------------------------------
enum class ProvisioningStatus {
    Pending, Enrolled, Failed, Revoked
}


// --------------------------------------------
// enum SensorType
// --------------------------------------------
enum class SensorType {
    Temperature, Humidity, Pressure, Accelerometer, Gyroscope, GPS, Light, CO2, VOC, Current, Voltage
}


// --------------------------------------------
// enum ActuatorType
// --------------------------------------------
enum class ActuatorType {
    Relay, Motor, Valve, LED, Buzzer, Display
}


// --------------------------------------------
// enum AlertSeverity
// --------------------------------------------
enum class AlertSeverity {
    Info, Warning, Critical
}


// --------------------------------------------
// enum AlertStatus
// --------------------------------------------
enum class AlertStatus {
    Open, Acknowledged, Resolved, Suppressed
}


// --------------------------------------------
// enum UserRole
// --------------------------------------------
enum class UserRole {
    Admin, Operator, Viewer, Integrator
}


// --------------------------------------------
// enum TenantType
// --------------------------------------------
enum class TenantType {
    Enterprise, SMB, ISV, SystemIntegrator, Government
}


// --------------------------------------------
// enum MessagingProtocol
// --------------------------------------------
enum class MessagingProtocol {
    MQTT, AMQP, HTTP, CoAP, WebSocket
}


// --------------------------------------------
// enum SimStatus
// --------------------------------------------
enum class SimStatus {
    Active, Suspended, Retired
}


// --------------------------------------------
// enum CommandStatus
// --------------------------------------------
enum class CommandStatus {
    Queued, Sent, Succeeded, Failed, TimedOut, Cancelled
}


// --------------------------------------------
// enum UpdateCampaignStatus
// --------------------------------------------
enum class UpdateCampaignStatus {
    Planned, InProgress, Paused, Completed, Cancelled
}


// --------------------------------------------
// enum UpdateStatus
// --------------------------------------------
enum class UpdateStatus {
    Downloading, Installing, Rebooting, Success, Failure, Deferred
}


// --------------------------------------------
// enum TwinChangeType
// --------------------------------------------
enum class TwinChangeType {
    DesiredUpdated, ReportedUpdated, TagUpdated
}


// --------------------------------------------
// enum MaintenancePriority
// --------------------------------------------
enum class MaintenancePriority {
    Low, Medium, High, Urgent
}


// --------------------------------------------
// enum MaintenanceStatus
// --------------------------------------------
enum class MaintenanceStatus {
    Open, InProgress, WaitingOnParts, Closed
}


// --------------------------------------------
// enum DeploymentStatus
// --------------------------------------------
enum class DeploymentStatus {
    Pending, Deploying, Running, Failed, Stopped
}


// --------------------------------------------
// enum PowerSource
// --------------------------------------------
enum class PowerSource {
    Battery, Mains, PoE, EnergyHarvesting, Solar
}


// --------------------------------------------
// enum ModuleType
// --------------------------------------------
enum class ModuleType {
    RFModule, MCU, SensorChipset, PowerManagement, Storage, Other
}


