# ============================================================
# Standard Spring Boot properties to set up persistence
# =============================================================
# The name of this app:
spring.application.name=bankingonspringboot
server.port=8080

# =============================================================
# Logging on
# =============================================================
logging.level.com.harbormaster=debug

# =============================================================
# The default profiles are "all of them"
# =============================================================
spring.profiles.active=null

 
# =============================================================
# spring jpa/hibernate params
# =============================================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.url=jdbc:mysql://localhost:3306/banking-on-spring-boot
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=null
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=false

# =============================================================
# enable security support - jwt, form-login, oauth2,  apikey
# =============================================================
hm.security.authentication=none


logging.structured.format.console=logstash

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false