/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.globalbank.controller.query;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.globalbank.api.*;
import com.globalbank.service.*;
import com.globalbank.entity.*;
import com.globalbank.exception.*;
import com.globalbank.projector.*;

import com.globalbank.controller.*;
/**
 * <h2>AccountQueryRestController as REST API</h2>
 * <p>
 * Implements Spring Controller query CQRS processing for entity Account.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/12/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	AccountService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateAccountCommand</li>
 *      <li></li>UpdateAccountCommand</li>
 *      <liDeleteAccountCommand</li>
 *      </ul>
 *
 * <p>@author your_name_here</p>
 */
@CrossOrigin
@RestController
@RequestMapping("/AccountQuery")
public class AccountQueryRestController extends BaseSpringRestController {
	
	public AccountQueryRestController( AccountService service ) {
        this.service = service;
    }
    
    /**
     * Handles loading a Account using a UUID
     * @param		UUID accountId
     * @return		Account
     */    
    @GetMapping("/load")
    public Account load( @RequestParam(required=true) UUID accountId ) {
    	Account entity = null;

    	try {  
    		entity = service.getAccount( new AccountFetchOneSummary( accountId ) );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Account using Id " + accountId );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Account business objects
     * @return		Set<Account>
     */
    @GetMapping("/")
    public List<Account> loadAll() {                
    	List<Account> accountList = null;
        
    	try {
            // load the Account
            accountList = service.getAllAccount();
            
            if ( accountList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Accounts" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Accounts ", exc );
        	return null;
        }

        return accountList;
                            
    }



//************************************************************************    
// Attributes
//************************************************************************
    protected Account account = null;
    protected AccountService service = null;
    private static final Logger LOGGER = Logger.getLogger(AccountQueryRestController.class.getName());
    
}
