
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * ECommerce Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ecommerceonaspdotnet.Domain;

/// <summary>
/// OrderStatus enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum OrderStatus
{
    Pending=1,Confirmed=2,Paid=3,PartiallyShipped=4,Shipped=5,Delivered=6,Cancelled=7,Refunded=8,PartiallyRefunded=9
}

/// <summary>
/// Extension of capabilities for the OrderStatus enum
/// </summary>
public static class OrderStatusExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<OrderStatus> GetValues()
    {
        return Enum.GetValues<OrderStatus>().ToList();
    }

    public static OrderStatus GetDefaultValue()
    {
        return Enum.GetValues<OrderStatus>().First();
    }

    public static OrderStatus WhichOne(string name)
    {
        if (Enum.TryParse<OrderStatus>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



