/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.entity;

import java.util.*

import jakarta.persistence.*

import com.harbormaster.api.*;

// --------------------------------------------
// Entity Definitions
// --------------------------------------------
@Entity
data class Bank(
    @Id var bankId: UUID? = null,
    var name: String? = null,
    var legalName: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "swiftBic_value"))
    )
    var swiftBic: BIC? = null,
    var headquartersCountry: String? = null,
    var website: String? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "branches") var branches:  Set<Branch>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "products") var products:  Set<BankingProduct>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "customers") var customers:  Set<Customer>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "accounts") var accounts:  Set<Account>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "paymentCards") var paymentCards:  Set<PaymentCard>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "loanAccounts") var loanAccounts:  Set<LoanAccount>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "exchangeRates") var exchangeRates:  Set<ExchangeRate>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "consents") var consents:  Set<Consent>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "thirdPartyProviders") var thirdPartyProviders:  Set<ThirdPartyProvider>? = null
)

@Entity
data class Branch(
    @Id var branchId: UUID? = null,
    var name: String? = null,
    var branchCode: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "street", column = Column(name = "address_street")),
      AttributeOverride( name = "city", column = Column(name = "address_city")),
      AttributeOverride( name = "state", column = Column(name = "address_state")),
      AttributeOverride( name = "postalCode", column = Column(name = "address_postalCode")),
      AttributeOverride( name = "country", column = Column(name = "address_country"))
    )
    var address: Address? = null,
    var phone: String? = null,
    var openingHours: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "bank") var bank: Bank? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "accounts") var accounts:  Set<Account>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "loanAccounts") var loanAccounts:  Set<LoanAccount>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "atms") var atms:  Set<ATM>? = null
)

@Entity
data class ATM(
    @Id var aTMId: UUID? = null,
    var terminalId: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "street", column = Column(name = "location_street")),
      AttributeOverride( name = "city", column = Column(name = "location_city")),
      AttributeOverride( name = "state", column = Column(name = "location_state")),
      AttributeOverride( name = "postalCode", column = Column(name = "location_postalCode")),
      AttributeOverride( name = "country", column = Column(name = "location_country"))
    )
    var location: Address? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "branch") var branch: Branch? = null,
    @Enumerated(EnumType.STRING) var status: ATMStatus? = null
)

@Entity
data class Customer(
    @Id var customerId: UUID? = null,
    var firstName: String? = null,
    var lastName: String? = null,
    var legalName: String? = null,
    var dateOfBirth:  Date? = null,
    var taxId: String? = null,
    var email: String? = null,
    var phone: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "street", column = Column(name = "address_street")),
      AttributeOverride( name = "city", column = Column(name = "address_city")),
      AttributeOverride( name = "state", column = Column(name = "address_state")),
      AttributeOverride( name = "postalCode", column = Column(name = "address_postalCode")),
      AttributeOverride( name = "country", column = Column(name = "address_country"))
    )
    var address: Address? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "bank") var bank: Bank? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "accounts") var accounts:  Set<Account>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "loanAccounts") var loanAccounts:  Set<LoanAccount>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "paymentCards") var paymentCards:  Set<PaymentCard>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "externalAccounts") var externalAccounts:  Set<ExternalAccount>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "fundsTransfers") var fundsTransfers:  Set<FundsTransfer>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "disputes") var disputes:  Set<Dispute>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "kycProfiles") var kycProfiles:  Set<KycProfile>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "consents") var consents:  Set<Consent>? = null,
    @Enumerated(EnumType.STRING) var customerType: CustomerType? = null,
    @Enumerated(EnumType.STRING) var riskRating: RiskRating? = null,
    @Enumerated(EnumType.STRING) var kycStatus: KycStatus? = null
)

@Entity
data class KycProfile(
    @Id var kycProfileId: UUID? = null,
    var profileId: String? = null,
    var lastReviewedOn:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "customer") var customer: Customer? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "identityDocuments") var identityDocuments:  Set<IdentityDocument>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "riskAssessments") var riskAssessments:  Set<RiskAssessment>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "screenings") var screenings:  Set<ScreeningResult>? = null,
    @Enumerated(EnumType.STRING) var status: KycStatus? = null
)

@Entity
data class IdentityDocument(
    @Id var identityDocumentId: UUID? = null,
    var documentNumber: String? = null,
    var issuingCountry: String? = null,
    var expirationDate:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "kycProfile") var kycProfile: KycProfile? = null,
    @Enumerated(EnumType.STRING) var documentType: IdentityDocumentType? = null
)

@Entity
data class RiskAssessment(
    @Id var riskAssessmentId: UUID? = null,
    var score: Int? = null,
    var assessedOn:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "kycProfile") var kycProfile: KycProfile? = null,
    @Enumerated(EnumType.STRING) var rating: RiskRating? = null
)

@Entity
data class ScreeningResult(
    @Id var screeningResultId: UUID? = null,
    var screeningDate:  Date? = null,
    var provider: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "kycProfile") var kycProfile: KycProfile? = null,
    @Enumerated(EnumType.STRING) var outcome: ScreeningOutcome? = null
)

@Entity
data class BankingProduct(
    @Id var bankingProductId: UUID? = null,
    var productCode: String? = null,
    var name: String? = null,
    var description: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "bank") var bank: Bank? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "accounts") var accounts:  Set<Account>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "loanAccounts") var loanAccounts:  Set<LoanAccount>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "paymentCards") var paymentCards:  Set<PaymentCard>? = null,
    @Enumerated(EnumType.STRING) var productCategory: ProductCategory? = null
)

@Entity
data class Account(
    @Id var accountId: UUID? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "accountNumber_value"))
    )
    var accountNumber: AccountNumber? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "iban_value"))
    )
    var iban: IBAN? = null,
    var accountName: String? = null,
    var currency: String? = null,
    var openedOn:  Date? = null,
    var closedOn:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "bank") var bank: Bank? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "branch") var branch: Branch? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "product") var product: BankingProduct? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "owners") var owners:  Set<Customer>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "transactions") var transactions:  Set<Transaction>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "statements") var statements:  Set<AccountStatement>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "standingInstructions") var standingInstructions:  Set<StandingInstruction>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "feeCharges") var feeCharges:  Set<FeeCharge>? = null,
    @Enumerated(EnumType.STRING) var accountType: AccountType? = null,
    @Enumerated(EnumType.STRING) var ownershipType: AccountOwnershipType? = null,
    @Enumerated(EnumType.STRING) var status: AccountStatus? = null
)

@Entity
data class AccountStatement(
    @Id var accountStatementId: UUID? = null,
    var statementNumber: String? = null,
    var periodStart:  Date? = null,
    var periodEnd:  Date? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "openingBalance_amount")),
      AttributeOverride( name = "currency", column = Column(name = "openingBalance_currency"))
    )
    var openingBalance: Money? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "closingBalance_amount")),
      AttributeOverride( name = "currency", column = Column(name = "closingBalance_currency"))
    )
    var closingBalance: Money? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "account") var account: Account? = null,
    @Enumerated(EnumType.STRING) var deliveryMethod: StatementDeliveryMethod? = null
)

@Entity
data class Transaction(
    @Id var transactionId: UUID? = null,
    var bookingDate:  Date? = null,
    var valueDate:  Date? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "amount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "amount_currency"))
    )
    var amount: Money? = null,
    var description: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "account") var account: Account? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "externalCounterparty") var externalCounterparty: ExternalAccount? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "paymentCard") var paymentCard: PaymentCard? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "fundsTransfer") var fundsTransfer: FundsTransfer? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "fxTrade") var fxTrade: FXTrade? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "dispute") var dispute: Dispute? = null,
    @Enumerated(EnumType.STRING) var direction: TransactionDirection? = null,
    @Enumerated(EnumType.STRING) var transactionType: TransactionType? = null,
    @Enumerated(EnumType.STRING) var status: TransactionStatus? = null,
    @Enumerated(EnumType.STRING) var channel: ChannelType? = null
)

@Entity
data class ExternalAccount(
    @Id var externalAccountId: UUID? = null,
    var name: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "iban_value"))
    )
    var iban: IBAN? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "accountNumber_value"))
    )
    var accountNumber: AccountNumber? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "bic_value"))
    )
    var bic: BIC? = null,
    var bankName: String? = null,
    var country: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "customer") var customer: Customer? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "transactions") var transactions:  Set<Transaction>? = null
)

@Entity
data class FundsTransfer(
    @Id var fundsTransferId: UUID? = null,
    var transferReference: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "amount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "amount_currency"))
    )
    var amount: Money? = null,
    var requestedDate:  Date? = null,
    var executionDate:  Date? = null,
    var purpose: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "feeAmount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "feeAmount_currency"))
    )
    var feeAmount: Money? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "sourceAccount") var sourceAccount: Account? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "destinationAccount") var destinationAccount: Account? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "externalBeneficiary") var externalBeneficiary: ExternalAccount? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "initiatedBy") var initiatedBy: Customer? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "transactions") var transactions:  Set<Transaction>? = null,
    @Enumerated(EnumType.STRING) var method: PaymentMethod? = null,
    @Enumerated(EnumType.STRING) var status: PaymentStatus? = null
)

@Entity
data class StandingInstruction(
    @Id var standingInstructionId: UUID? = null,
    var instructionId: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "amount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "amount_currency"))
    )
    var amount: Money? = null,
    var nextExecutionDate:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "account") var account: Account? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "beneficiary") var beneficiary: ExternalAccount? = null,
    @Enumerated(EnumType.STRING) var frequency: StandingInstructionFrequency? = null,
    @Enumerated(EnumType.STRING) var status: StandingInstructionStatus? = null
)

@Entity
data class PaymentCard(
    @Id var paymentCardId: UUID? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "cardNumber_value"))
    )
    var cardNumber: CardPAN? = null,
    var embossedName: String? = null,
    var expiryMonth: Int? = null,
    var expiryYear: Int? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "bank") var bank: Bank? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "account") var account: Account? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "customer") var customer: Customer? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "transactions") var transactions:  Set<Transaction>? = null,
    @Enumerated(EnumType.STRING) var cardType: CardType? = null,
    @Enumerated(EnumType.STRING) var cardStatus: CardStatus? = null,
    @Enumerated(EnumType.STRING) var network: CardNetwork? = null
)

@Entity
data class LoanAccount(
    @Id var loanAccountId: UUID? = null,
    var loanNumber: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "principalAmount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "principalAmount_currency"))
    )
    var principalAmount: Money? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "outstandingPrincipal_amount")),
      AttributeOverride( name = "currency", column = Column(name = "outstandingPrincipal_currency"))
    )
    var outstandingPrincipal: Money? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "interestRate_value"))
    )
    var interestRate: Percentage? = null,
    var originationDate:  Date? = null,
    var maturityDate:  Date? = null,
    var paymentDayOfMonth: Int? = null,
    var currency: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "bank") var bank: Bank? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "branch") var branch: Branch? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "product") var product: BankingProduct? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "borrowers") var borrowers:  Set<Customer>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "repaymentSchedule") var repaymentSchedule:  Set<RepaymentSchedule>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "payments") var payments:  Set<LoanPayment>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "collateral") var collateral:  Set<Collateral>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "feeCharges") var feeCharges:  Set<FeeCharge>? = null,
    @Enumerated(EnumType.STRING) var loanType: LoanType? = null,
    @Enumerated(EnumType.STRING) var rateType: RateType? = null,
    @Enumerated(EnumType.STRING) var compounding: InterestCompounding? = null,
    @Enumerated(EnumType.STRING) var status: LoanStatus? = null
)

@Entity
data class RepaymentSchedule(
    @Id var repaymentScheduleId: UUID? = null,
    var installmentNumber: Int? = null,
    var dueDate:  Date? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "principalDue_amount")),
      AttributeOverride( name = "currency", column = Column(name = "principalDue_currency"))
    )
    var principalDue: Money? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "interestDue_amount")),
      AttributeOverride( name = "currency", column = Column(name = "interestDue_currency"))
    )
    var interestDue: Money? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "totalDue_amount")),
      AttributeOverride( name = "currency", column = Column(name = "totalDue_currency"))
    )
    var totalDue: Money? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "loanAccount") var loanAccount: LoanAccount? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "payment") var payment: LoanPayment? = null,
    @Enumerated(EnumType.STRING) var status: InstallmentStatus? = null
)

@Entity
data class LoanPayment(
    @Id var loanPaymentId: UUID? = null,
    var paymentReference: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "amount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "amount_currency"))
    )
    var amount: Money? = null,
    var paymentDate:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "loanAccount") var loanAccount: LoanAccount? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "transaction") var transaction: Transaction? = null,
    @Enumerated(EnumType.STRING) var method: PaymentMethod? = null,
    @Enumerated(EnumType.STRING) var status: PaymentStatus? = null
)

@Entity
data class Collateral(
    @Id var collateralId: UUID? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "appraisedValue_amount")),
      AttributeOverride( name = "currency", column = Column(name = "appraisedValue_currency"))
    )
    var appraisedValue: Money? = null,
    var description: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "street", column = Column(name = "location_street")),
      AttributeOverride( name = "city", column = Column(name = "location_city")),
      AttributeOverride( name = "state", column = Column(name = "location_state")),
      AttributeOverride( name = "postalCode", column = Column(name = "location_postalCode")),
      AttributeOverride( name = "country", column = Column(name = "location_country"))
    )
    var location: Address? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "loanAccount") var loanAccount: LoanAccount? = null,
    @Enumerated(EnumType.STRING) var collateralType: CollateralType? = null
)

@Entity
data class FeeCharge(
    @Id var feeChargeId: UUID? = null,
    var feeCode: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "amount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "amount_currency"))
    )
    var amount: Money? = null,
    var appliedOn:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "account") var account: Account? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "loanAccount") var loanAccount: LoanAccount? = null,
    @Enumerated(EnumType.STRING) var feeType: FeeType? = null
)

@Entity
data class ExchangeRate(
    @Id var exchangeRateId: UUID? = null,
    var baseCurrency: String? = null,
    var counterCurrency: String? = null,
    var rate: java.math.BigDecimal? = null,
    var asOf:  Date? = null,
    var source: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "bank") var bank: Bank? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "fxTrades") var fxTrades:  Set<FXTrade>? = null
)

@Entity
data class FXTrade(
    @Id var fXTradeId: UUID? = null,
    var tradeReference: String? = null,
    var tradeDate:  Date? = null,
    var settlementDate:  Date? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "amountSold_amount")),
      AttributeOverride( name = "currency", column = Column(name = "amountSold_currency"))
    )
    var amountSold: Money? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "amountBought_amount")),
      AttributeOverride( name = "currency", column = Column(name = "amountBought_currency"))
    )
    var amountBought: Money? = null,
    var rate: java.math.BigDecimal? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "customer") var customer: Customer? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "bank") var bank: Bank? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "exchangeRate") var exchangeRate: ExchangeRate? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "sourceAccount") var sourceAccount: Account? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "destinationAccount") var destinationAccount: Account? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "transaction") var transaction: Transaction? = null,
    @Enumerated(EnumType.STRING) var status: TradeStatus? = null
)

@Entity
data class Dispute(
    @Id var disputeId: UUID? = null,
    var disputeReference: String? = null,
    var raisedOn:  Date? = null,
    var reason: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "transaction") var transaction: Transaction? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "customer") var customer: Customer? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "account") var account: Account? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "paymentCard") var paymentCard: PaymentCard? = null,
    @Enumerated(EnumType.STRING) var status: DisputeStatus? = null
)

@Entity
data class Consent(
    @Id var consentId: UUID? = null,
    var grantedOn:  Date? = null,
    var expiresOn:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "customer") var customer: Customer? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "bank") var bank: Bank? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "authorizedAccounts") var authorizedAccounts:  Set<Account>? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "thirdPartyProvider") var thirdPartyProvider: ThirdPartyProvider? = null,
    @Enumerated(EnumType.STRING) var consentType: ConsentType? = null,
    @Enumerated(EnumType.STRING) var status: ConsentStatus? = null
)

@Entity
data class ThirdPartyProvider(
    @Id var thirdPartyProviderId: UUID? = null,
    var name: String? = null,
    var registrationId: String? = null,
    var website: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "bank") var bank: Bank? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "consents") var consents:  Set<Consent>? = null
)

