/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;

/**
 * Test IoTDevice class.
 *
 * @author Harbormaster Dev Team
 */
public class IoTDeviceTest{

        // ------------------------------------
		// default constructor
	    // ------------------------------------
		public IoTDeviceTest() {
			LOGGER.setUseParentHandlers(false);	// only want to output to the provided LogHandler
		}

		// test methods
		@Test
		/**
		 * Full Create-Read-Update-Delete of a IoTDevice, through a
		 * IoTDeviceTest.
		 */
		public void testCRUD() throws Throwable {
			try {
				LOGGER.info("**********************************************************");
				LOGGER.info("Beginning full CRUD test on IoTDevice...");

				testCreate();
//				testRead();
//				testUpdate();
				testGetAll();
//				testDelete();

				LOGGER.info("Successfully ran a full test on IoTDeviceTest...");
				LOGGER.info("**********************************************************");
				LOGGER.info("");
			} catch (Throwable e) {
				throw e;
			} finally {
				if (handler != null) {
					handler.flush();
					LOGGER.removeHandler(handler);
				}
			}
		}

		/** 
		 * Tests creating a new IoTDevice.
		 */
		public void testCreate() throws Throwable {
			LOGGER.info( "\n======== CREATE ======== ");
			LOGGER.info( "-- Attempting to create a IoTDevice");

			StringBuilder msg = new StringBuilder( "-- Failed to create a IoTDevice" );

			try {            
				IoTDevice entity = IoTDeviceService.getIoTDeviceInstance().createIoTDevice( generateNewEntity() );
				thePrimaryKey = entity.getIoTDeviceId();
				LOGGER.info( "-- Successfully created a IoTDevice with primary key" + thePrimaryKey );
			}
			catch (Exception e) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
		}

		/** 
		 * Tests reading a IoTDevice. 
		 */
		public IoTDevice testRead() throws Throwable {
			LOGGER.info( "\n======== READ ======== ");
			LOGGER.info( "-- Reading a previously created IoTDevice" );

			IoTDevice entity = null;
			StringBuilder msg = new StringBuilder( "-- Failed to read IoTDevice with primary key" );
			msg.append( thePrimaryKey );
			
			IoTDeviceFetchOneSummary fetchOneSummary = new IoTDeviceFetchOneSummary( thePrimaryKey );

			try {
				entity = IoTDeviceService.getIoTDeviceInstance().getIoTDevice( fetchOneSummary );

				assertNotNull( entity,msg.toString() );

				LOGGER.info( "-- Successfully found IoTDevice " + entity.toString() );
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
			
			return entity;
		}

		/** 
		 * Tests updating a IoTDevice.
		 */
		public void testUpdate() throws Throwable {
			LOGGER.info( "\n======== UPDATE ======== ");
			LOGGER.info( "-- Attempting to update a IoTDevice." );

			StringBuilder msg = new StringBuilder( "Failed to update a IoTDevice : " );        
			IoTDevice entity = null;

			try {            
				entity = testRead();

				assertNotNull( entity, msg.toString() );

				LOGGER.info( "-- Now updating the created IoTDevice." );

				// for use later on...
				thePrimaryKey = entity.getIoTDeviceId();

				IoTDeviceService proxy = IoTDeviceService.getIoTDeviceInstance();            
				proxy.updateIoTDevice( entity );   

				LOGGER.info( "-- Successfully saved IoTDevice - " + entity.toString() );
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : primarykey = " + thePrimaryKey + " : entity-" +  entity + " : " + e );

				throw e;
			}
		}

		/** 
		 * Tests deleting a IoTDevice.
		 */
		public void testDelete() throws Throwable {
			LOGGER.info( "\n======== DELETE ======== ");
			LOGGER.info( "-- Deleting a previously created IoTDevice." );

			try{
			    IoTDevice entity = testRead(); 
				IoTDeviceService.getIoTDeviceInstance().delete( entity );

				LOGGER.info( "-- Successfully deleted IoTDevice with primary key " + thePrimaryKey );            
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( "-- Failed to delete IoTDevice with primary key " + thePrimaryKey );

				throw e;
			}
		}

		/**
		 * Tests getting all IoTDevices.
		 */
		public void testGetAll() throws Throwable {    
			LOGGER.info( "======== GETALL ======== ");
			LOGGER.info( "-- Retrieving Collection of IoTDevices:" );

			StringBuilder msg = new StringBuilder( "-- Failed to get all IoTDevice : " );        
			List<IoTDevice> collection  = null;

			try {
				// call the static get method on the IoTDeviceService
				collection = IoTDeviceService.getIoTDeviceInstance().getAllIoTDevice();

				if ( collection == null || collection.size() == 0 ) {
					LOGGER.warning( unexpectedErrorMsg );
					LOGGER.warning( msg.toString() + " Empty collection returned."  );
				}
				else {
					// Now print out the values
					IoTDevice entity = null;            
					Iterator<IoTDevice> iter = collection.iterator();
					int index = 1;

					while( iter.hasNext() ) {
						// Retrieve the entity   
						entity = iter.next();

						assertNotNull( entity,"-- null entity in Collection." );
						assertNotNull( entity.getIoTDeviceId(), "-- entity in Collection has a null primary key" );        

						LOGGER.info( " - " + String.valueOf(index) + ". " + entity.toString() );
						index++;
					}
				}
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
		}

		/**
		 * Assigns a common log handler for each test class in the suite
		 * @param		handler	Handler
		 * @return		IoTDeviceTest
		 */
		public IoTDeviceTest setHandler(Handler handler) {
			this.handler = handler;
			LOGGER.addHandler(handler); // assign so the LOGGER can only output results to the Handler
			return this;
		}

		/**
		 * Returns a new populated IoTDevice
		 * 
		 * @return IoTDevice
		 */
		protected IoTDevice generateNewEntity() {
			IoTDevice entity = new IoTDevice( null,  new DeviceId(),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),   new Date(),  new FirmwareVersion(),  null,  null,  null,  null,  null,  new HashSet<>(),  new HashSet<>(),  new HashSet<>(),  null,  new HashSet<>(),  new HashSet<>(),  new HashSet<>(),  null,  new HashSet<>(),  new HashSet<>(),  DeviceStatus.values()[0],  PowerSource.values()[0] );
			
			return( entity );
		}

		//-----------------------------------------------------
		// attributes 
		//-----------------------------------------------------
		protected UUID thePrimaryKey 						= null;
		private final Logger LOGGER 						= Logger.getLogger(IoTDeviceTest.class.getName());
		private Handler handler 							= null;
		private String unexpectedErrorMsg 					= ":::::::::::::: Unexpected Error :::::::::::::::::";
	}
