/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.globalbank.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.springframework.util.Assert.state;

import com.globalbank.service.*;
import com.globalbank.entity.*;
import com.globalbank.api.*;
import com.globalbank.subscriber.*;

/**
 * <h2>AccountStatementTest</h2>
 * <p>
 * Junit test class for entity AccountStatement.  Handle the full lifecycle as it relates to persistence. Leverages
 * the AccountStatementService and a AccountStatementSubscriber to test everything under a MVC framework which includes the
 * AccountStatementAggregate and related commands, queries, and events.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/12/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 * 		AccountStatementService
 * 	    AccountStatementSubscriber
 *
 * <h3>Methods</h3>
 *      <ul>
 *      <li>read</li>
 *      <li>update</li>
 *      <li>delete</li>
 *      </ul>
 *
 * <p>
 * @author your_name_here
 * </p>
 */
public class AccountStatementTest {

    // ------------------------------------
	// default constructor
    // ------------------------------------
	public AccountStatementTest() {
		subscriber = new AccountStatementSubscriber();
	}

	// test methods
	@Test
	/*
	 * Initiate AccountStatementTest.
	 */
	public void startTest() throws Throwable {
		try {
			LOGGER.info("**********************************************************");
			LOGGER.info("Beginning test on AccountStatement...");
			LOGGER.info("**********************************************************\n");
			
			// ---------------------------------------------
			// jumpstart process
			// ---------------------------------------------
			jumpStart();
			
		} catch (Throwable e) {
			throw e;
		} finally {
		}
	}

	/** 
	 * jumpstart the process by instantiating2 AccountStatement
	 */
	protected void jumpStart() throws Throwable {
		LOGGER.info( "\n======== create instances to get the ball rolling  ======== ");

		accountStatementId = AccountStatementService.getAccountStatementInstance()
		.createAccountStatement( generateNewCommand() )
		.get();

		// ---------------------------------------------
		// set up query subscriptions after the 1st create
		// ---------------------------------------------
		testingStep = "create";
		setUpQuerySubscriptions();

		AccountStatementService.getAccountStatementInstance()
				.createAccountStatement( generateNewCommand() )
				.get();

	}

	/** 
	 * Set up query subscriptions
	 */
	protected void setUpQuerySubscriptions() throws Throwable {
		LOGGER.info( "\n======== Setting Up Query Subscriptions ======== ");
			
		try {            
			subscriber.accountStatementSubscribe().updates().subscribe(
					  successValue -> {
						  LOGGER.info(successValue.toString());
						  try {
							  LOGGER.info("GetAll update received for AccountStatement : " + successValue.getAccountStatementId());
							  if (successValue.getAccountStatementId().equals(accountStatementId)) {
								  if (testingStep.equals("create")) {
									  testingStep = "update";
									  update();
								  } else if (testingStep.equals("delete")) {
									  testingStep = "complete";
									  state( getAll().size() == sizeOfAccountStatementList - 1 , "value not deleted from list");
									  LOGGER.info("**********************************************************");
									  LOGGER.info("AccountStatement test completed successfully...");
									  LOGGER.info("**********************************************************\n");
								  }
							  }
						  } catch( Throwable exc ) {
							  LOGGER.warning( exc.getMessage() );
						  }
					  },
					  error -> LOGGER.warning(error.getMessage()),
					  () -> LOGGER.info("Subscription on accountStatement consumed")
					);
			subscriber.accountStatementSubscribe( accountStatementId ).updates().subscribe(
					  successValue -> {
						  LOGGER.info(successValue.toString());
						  try {
							  LOGGER.info("GetOne update received for AccountStatement : " + successValue.getAccountStatementId() + " in step " + testingStep);
							  testingStep = "delete";
							  sizeOfAccountStatementList = getAll().size();
							  delete();
						  } catch( Throwable exc ) {
							  LOGGER.warning( exc.getMessage() );
						  }
					  },
					  error -> LOGGER.warning(error.getMessage()),
					  () -> LOGGER.info("Subscription on accountStatement for accountStatementId consumed")

					);
			

			}
			catch (Exception e) {
				LOGGER.warning( e.getMessage() );
				throw e;
			}
		}
		
		/** 
	 * read a AccountStatement. 
	 */
	protected AccountStatement read() throws Throwable {
		LOGGER.info( "\n======== READ ======== ");
		LOGGER.info( "-- Reading a previously created AccountStatement" );

		AccountStatement entity = null;
		StringBuilder msg = new StringBuilder( "-- Failed to read AccountStatement with primary key" );
		msg.append( accountStatementId );
		
		AccountStatementFetchOneSummary fetchOneSummary = new AccountStatementFetchOneSummary( accountStatementId );

		try {
			entity = AccountStatementService.getAccountStatementInstance().getAccountStatement( fetchOneSummary );

			assertNotNull( entity,msg.toString() );

			LOGGER.info( "-- Successfully found AccountStatement " + entity.toString() );
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : " + e );

			throw e;
		}
		
		return entity;
	}

	/** 
	 * updating a AccountStatement.
	 */
	protected void update() throws Throwable {
		LOGGER.info( "\n======== UPDATE ======== ");
		LOGGER.info( "-- Attempting to update a AccountStatement." );

		StringBuilder msg = new StringBuilder( "Failed to update a AccountStatement : " );        
		AccountStatement entity = read();
		UpdateAccountStatementCommand command = generateUpdateCommand();
		command.setAccountStatementId(entity.getAccountStatementId());

		try {            
			assertNotNull( entity, msg.toString() );

			LOGGER.info( "-- Now updating the created AccountStatement." );

			// for use later on...
			accountStatementId = entity.getAccountStatementId();

			AccountStatementService proxy = AccountStatementService.getAccountStatementInstance();  

			proxy.updateAccountStatement( command ).get();

			LOGGER.info( "-- Successfully saved AccountStatement - " + entity.toString() );
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : primarykey = " + accountStatementId + " : command -" +  command + " : " + e );

			throw e;
		}
	}

	/** 
	 * delete a AccountStatement.
	 */
	protected void delete() throws Throwable {
		LOGGER.info( "\n======== DELETE ======== ");
		LOGGER.info( "-- Deleting a previously created AccountStatement." );

		AccountStatement entity = null;
		
		try{
		    entity = read(); 
			LOGGER.info( "-- Successfully read AccountStatement with id " + accountStatementId );            
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( "-- Failed to read AccountStatement with id " + accountStatementId );

			throw e;
		}

		try{
			AccountStatementService.getAccountStatementInstance().delete( new DeleteAccountStatementCommand( entity.getAccountStatementId() ) ).get();
			LOGGER.info( "-- Successfully deleted AccountStatement with id " + accountStatementId );            
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( "-- Failed to delete AccountStatement with id " + accountStatementId );

			throw e;
		}
	}

	/**
	 * get all AccountStatements.
	 */
	protected List<AccountStatement> getAll() throws Throwable {    
		LOGGER.info( "======== GETALL ======== ");
		LOGGER.info( "-- Retrieving Collection of AccountStatements:" );

		StringBuilder msg = new StringBuilder( "-- Failed to get all AccountStatement : " );        
		List<AccountStatement> collection  = new ArrayList<>();

		try {
			// call the static get method on the AccountStatementService
			collection = AccountStatementService.getAccountStatementInstance().getAllAccountStatement();
			assertNotNull( collection, "An Empty collection of AccountStatement was incorrectly returned.");
			
			// Now print out the values
			AccountStatement entity = null;            
			Iterator<AccountStatement> iter = collection.iterator();
			int index = 1;

			while( iter.hasNext() ) {
				// Retrieve the entity   
				entity = iter.next();

				assertNotNull( entity,"-- null entity in Collection." );
				assertNotNull( entity.getAccountStatementId(), "-- entity in Collection has a null primary key" );        

				LOGGER.info( " - " + String.valueOf(index) + ". " + entity.toString() );
				index++;
			}
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : " + e );

			throw e;
		}
		
		return collection;			
	}

	/**
	 * Assigns a common log handler for each test class in the suite 
	 * in the event log output needs to go elsewhere
	 * 
	 * @param		handler	Handler
	 * @return		AccountStatementTest
	 */
	protected AccountStatementTest setHandler(Handler handler) {
		if ( handler != null )
			LOGGER.addHandler(handler); 
		return this;
	}

	/**
	 * Returns a new populated AccountStatement
	 * 
	 * @return CreateAccountStatementCommand alias
	 */
	protected CreateAccountStatementCommand generateNewCommand() {
        CreateAccountStatementCommand command = new CreateAccountStatementCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),   new Date(),   new Date(),  new Money(),  new Money(),  StatementDeliveryMethod.values()[0] );
		
		return( command );
	}

		/**
		 * Returns a new populated AccountStatement
		 * 
		 * @return UpdateAccountStatementCommand alias
		 */
	protected UpdateAccountStatementCommand generateUpdateCommand() {
	        UpdateAccountStatementCommand command = new UpdateAccountStatementCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),   new Date(),   new Date(),  new Money(),  new Money(),  null,  StatementDeliveryMethod.values()[0] );
			
			return( command );
		}
	//-----------------------------------------------------
	// attributes 
	//-----------------------------------------------------
	protected UUID accountStatementId = null;
	protected AccountStatementSubscriber subscriber = null;
	private final String unexpectedErrorMsg = ":::::::::::::: Unexpected Error :::::::::::::::::";
	private final Logger LOGGER = Logger.getLogger(AccountStatementTest.class.getName());
	private String testingStep = "";
	private Integer sizeOfAccountStatementList = 0;
}
