
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace iotonaspdotnet.Domain;

/// <summary>
/// ConnectivityType enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum ConnectivityType
{
    WiFi=1,Ethernet=2,LTE=3,FiveG=4,NBIoT=5,LoRaWAN=6,Zigbee=7,BLE=8,Satellite=9
}

/// <summary>
/// Extension of capabilities for the ConnectivityType enum
/// </summary>
public static class ConnectivityTypeExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<ConnectivityType> GetValues()
    {
        return Enum.GetValues<ConnectivityType>().ToList();
    }

    public static ConnectivityType GetDefaultValue()
    {
        return Enum.GetValues<ConnectivityType>().First();
    }

    public static ConnectivityType WhichOne(string name)
    {
        if (Enum.TryParse<ConnectivityType>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



