
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace iotonaspdotnet.Domain;

/// <summary>
/// DeviceStatus enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum DeviceStatus
{
    Provisioning = 1, Active = 2, Suspended = 3, Offline = 4, Decommissioned = 5
}

/// <summary>
/// Extension of capabilities for the DeviceStatus enum
/// </summary>
public static class DeviceStatusExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<DeviceStatus> GetValues()
    {
        return Enum.GetValues<DeviceStatus>().ToList();
    }

    public static DeviceStatus GetDefaultValue()
    {
        return Enum.GetValues<DeviceStatus>().First();
    }

    public static DeviceStatus WhichOne(string name)
    {
        if (Enum.TryParse<DeviceStatus>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



