
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace iotonaspdotnet.Domain;

/// <summary>
/// MessagingProtocol enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum MessagingProtocol
{
    MQTT = 1, AMQP = 2, HTTP = 3, CoAP = 4, WebSocket = 5
}

/// <summary>
/// Extension of capabilities for the MessagingProtocol enum
/// </summary>
public static class MessagingProtocolExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<MessagingProtocol> GetValues()
    {
        return Enum.GetValues<MessagingProtocol>().ToList();
    }

    public static MessagingProtocol GetDefaultValue()
    {
        return Enum.GetValues<MessagingProtocol>().First();
    }

    public static MessagingProtocol WhichOne(string name)
    {
        if (Enum.TryParse<MessagingProtocol>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



