
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller.command;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.projector.*;

import com.harbormaster.controller.*;

/**
 * <h2>BuildingCommandRestController as REST API</h2>
 * <p>
 * Implements Spring Controller command CQRS processing for entity Building.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	BuildingService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateBuildingCommand</li>
 *      <li>UpdateBuildingCommand</li>
 *      <liDeleteBuildingCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */

@CrossOrigin
@RestController
@RequestMapping("/BuildingCommand")
public class BuildingCommandRestController extends BaseSpringRestController {

	public BuildingCommandRestController( BuildingService service ) {
		this.service = service;
	}
	
    /**
     * Handles create a Building.
     * @param		Building	building
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateBuildingCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {
			completableFuture = service.createBuilding( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a Building.  if no key provided, calls create, otherwise calls save
     * @param		Building building
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateBuildingCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateBuildingCommand
			// -----------------------------------------------
			completableFuture = service.updateBuilding(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "BuildingController:update() - successfully update Building - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a Building entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestParam(required=true) UUID buildingId  ) {
    	CompletableFuture<Void> completableFuture = null;
		DeleteBuildingCommand command = new DeleteBuildingCommand( buildingId );

    	try {
        	completableFuture = service.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Building with key " + command.getBuildingId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	

    /**
     * save Site on Building
     * @param		command AssignSiteToBuildingCommand
     */     
	@PutMapping("/assignSite")
	public void assignSite( @RequestBody AssignSiteToBuildingCommand command ) {
		try {
			service.assignSite( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Site", exc );
        }
	}

    /**
     * unassign Site on Building
     * @param		 command UnAssignSiteFromBuildingCommand
     */     
	@PutMapping("/unAssignSite")
	public void unAssignSite( @RequestBody(required=true)  UnAssignSiteFromBuildingCommand command ) {
		try {
			service.unAssignSite( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Site", exc );
		}
	}
	

    /**
     * save Floors on Building
     * @param		command AssignFloorsToBuildingCommand
     */     
	@PutMapping("/addToFloors")
	public void addToFloors( @RequestBody(required=true) AssignFloorsToBuildingCommand command ) {
		try {
			service.addToFloors( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Floors", exc );
		}
	}

    /**
     * remove Floors on Building
     * @param		command RemoveFloorsFromBuildingCommand
     */     	
	@PutMapping("/removeFromFloors")
	public void removeFromFloors( 	@RequestBody(required=true) RemoveFloorsFromBuildingCommand command )
	{		
		try {
			service.removeFromFloors( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Floors", exc );
		}
	}


//************************************************************************    
// Attributes
//************************************************************************
    protected Building building = null;
	protected BuildingService service = null;
    private static final Logger LOGGER = Logger.getLogger(BuildingCommandRestController.class.getName());
    
}
