
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller.command;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.projector.*;

import com.harbormaster.controller.*;

/**
 * <h2>TelemetrySchemaCommandRestController as REST API</h2>
 * <p>
 * Implements Spring Controller command CQRS processing for entity TelemetrySchema.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	TelemetrySchemaService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateTelemetrySchemaCommand</li>
 *      <li>UpdateTelemetrySchemaCommand</li>
 *      <liDeleteTelemetrySchemaCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */

@CrossOrigin
@RestController
@RequestMapping("/TelemetrySchemaCommand")
public class TelemetrySchemaCommandRestController extends BaseSpringRestController {

	public TelemetrySchemaCommandRestController( TelemetrySchemaService service ) {
		this.service = service;
	}
	
    /**
     * Handles create a TelemetrySchema.
     * @param		TelemetrySchema	telemetrySchema
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateTelemetrySchemaCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {
			completableFuture = service.createTelemetrySchema( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a TelemetrySchema.  if no key provided, calls create, otherwise calls save
     * @param		TelemetrySchema telemetrySchema
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateTelemetrySchemaCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateTelemetrySchemaCommand
			// -----------------------------------------------
			completableFuture = service.updateTelemetrySchema(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "TelemetrySchemaController:update() - successfully update TelemetrySchema - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a TelemetrySchema entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestParam(required=true) UUID telemetrySchemaId  ) {
    	CompletableFuture<Void> completableFuture = null;
		DeleteTelemetrySchemaCommand command = new DeleteTelemetrySchemaCommand( telemetrySchemaId );

    	try {
        	completableFuture = service.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted TelemetrySchema with key " + command.getTelemetrySchemaId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	


    /**
     * save Streams on TelemetrySchema
     * @param		command AssignStreamsToTelemetrySchemaCommand
     */     
	@PutMapping("/addToStreams")
	public void addToStreams( @RequestBody(required=true) AssignStreamsToTelemetrySchemaCommand command ) {
		try {
			service.addToStreams( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Streams", exc );
		}
	}

    /**
     * remove Streams on TelemetrySchema
     * @param		command RemoveStreamsFromTelemetrySchemaCommand
     */     	
	@PutMapping("/removeFromStreams")
	public void removeFromStreams( 	@RequestBody(required=true) RemoveStreamsFromTelemetrySchemaCommand command )
	{		
		try {
			service.removeFromStreams( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Streams", exc );
		}
	}


//************************************************************************    
// Attributes
//************************************************************************
    protected TelemetrySchema telemetrySchema = null;
	protected TelemetrySchemaService service = null;
    private static final Logger LOGGER = Logger.getLogger(TelemetrySchemaCommandRestController.class.getName());
    
}
