/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace bankingonaspdotnet.Domain;

/// <summary>
/// TransactionStatus enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum TransactionStatus
{
    Pending = 1, Posted = 2, Reversed = 3, Failed = 4, Cancelled = 5
}

/// <summary>
/// Extension of capabilities for the TransactionStatus enum
/// </summary>
public static class TransactionStatusExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<TransactionStatus> GetValues()
    {
        return Enum.GetValues<TransactionStatus>().ToList();
    }

    public static TransactionStatus GetDefaultValue()
    {
        return Enum.GetValues<TransactionStatus>().First();
    }

    public static TransactionStatus WhichOne(string name)
    {
        if (Enum.TryParse<TransactionStatus>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



