/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>CorporateActionEntity Projector</h2>
 * <p>
 * The CorporateAction Entity Projector is responsible for maintaining the write model for
 * CorporateAction entities. It subscribes to domain events published by the CorporateAction
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/05/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>CorporateActionRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("corporateAction-entity-projector")
public class CorporateActionEntityProjector implements EntityProjector<CorporateAction>{
		
	// core constructor
	public CorporateActionEntityProjector(ProjectorRegistry registry,
										CorporateActionRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<CorporateAction> getEntityClass() {
		return CorporateAction.class;
	}

    /*
	 * Insert a CorporateAction
	 * 
     * @param	entity CorporateAction
     */
    public CorporateAction create( CorporateAction entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a CorporateAction
	 * 
     * @param	entity CorporateAction
     */
    public CorporateAction update( CorporateAction entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a CorporateAction
	 * 
     * @param	id		UUID
     */
    public CorporateAction delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    CorporateAction entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Security
     * 
     * @param	parentId	UUID
     * @param	assignment 	Security 
     * @return	CorporateAction
     */
    public CorporateAction assignSecurity( UUID parentId, Security assignment ) {
	    LOGGER.info("assigning Security as " + assignment.toString() );

	    CorporateAction parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Security.class, assignment.getSecurityId());

	    // ------------------------------------------
		// assign the Security to the parent entity
		// ------------------------------------------ 
	    parentEntity.setSecurity( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Security
	 * 
	 * @param	parentId		UUID
	 * @return	CorporateAction
	 */
	public CorporateAction unAssignSecurity( UUID parentId ) {
		CorporateAction parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Security on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Security on the parent entithy
		// ------------------------------------------     
	    parentEntity.setSecurity(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the Dividends
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	CorporateAction
     */
    public CorporateAction addToDividends( UUID parentId, Dividend addTo ) {
	    LOGGER.info("handling AssignDividendsToCorporateActionEvent - " );
	    
	    CorporateAction parentEntity = repository.findById(parentId).get();
	    Dividend child = registry.project( Dividend.class, addTo.getDividendId());
	    
	    parentEntity.getDividends().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Dividends
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	CorporateAction
     */
	public CorporateAction removeFromDividends( UUID parentId, Dividend removeFrom ) {
	    LOGGER.info("handling RemoveDividendsFromCorporateActionEvent " );
	
	    CorporateAction parentEntity = repository.findById(parentId).get();
	    Dividend child = registry.project( Dividend.class, removeFrom.getDividendId());
	    
	    parentEntity.getDividends().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the CorporateAction via an FindCorporateActionQuery
     * @return 	query	FindCorporateActionQuery
     */
    @SuppressWarnings("unused")
    public CorporateAction find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a CorporateAction - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all CorporateActions
     *
     * @param	query	FindAllCorporateActionQuery 
     * @return 	List<CorporateAction> 
     */
    @SuppressWarnings("unused")
    public List<CorporateAction> findAll( FindAllCorporateActionQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all CorporateAction - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final CorporateActionRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(CorporateActionEntityProjector.class.getName());

}
