
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>TelemetryStreamEntity Projector</h2>
 * <p>
 * The TelemetryStream Entity Projector is responsible for maintaining the read model for
 * TelemetryStream entities. It subscribes to domain events published by the TelemetryStream
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>TelemetryStreamRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("telemetryStream-entity-projector")
public class TelemetryStreamEntityProjector implements EntityProjector<TelemetryStream>{
		
	// core constructor
	public TelemetryStreamEntityProjector(ProjectorRegistry registry,
										TelemetryStreamRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<TelemetryStream> getEntityClass() {
		return TelemetryStream.class;
	}

    /*
	 * Insert a TelemetryStream
	 * 
     * @param	entity TelemetryStream
     */
    public TelemetryStream create( TelemetryStream entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a TelemetryStream
	 * 
     * @param	entity TelemetryStream
     */
    public TelemetryStream update( TelemetryStream entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a TelemetryStream
	 * 
     * @param	id		UUID
     */
    public TelemetryStream delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    TelemetryStream entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Device
     * 
     * @param	parentId	UUID
     * @param	childId		UUID
     * @return	TelemetryStream
     */
    public TelemetryStream assignDevice( UUID parentId, UUID childId ) {
	    LOGGER.info("assigning Device as " + assignment.toString() );

	    TelemetryStream parentEntity = repository.findById( parentId ).get();
		IoTDevice assignment = registry.project( IoTDevice.class, childId);

	    // ------------------------------------------
		// assign the Device to the parent entity
		// ------------------------------------------ 
	    parentEntity.setDevice( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Device
	 * 
	 * @param	parentId		UUID
	 * @return	TelemetryStream
	 */
	public TelemetryStream unAssignDevice( UUID parentId ) {
		TelemetryStream parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Device on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Device on the parent entithy
		// ------------------------------------------     
	    parentEntity.setDevice(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a Sensor
     * 
     * @param	parentId	UUID
     * @param	childId		UUID
     * @return	TelemetryStream
     */
    public TelemetryStream assignSensor( UUID parentId, UUID childId ) {
	    LOGGER.info("assigning Sensor as " + assignment.toString() );

	    TelemetryStream parentEntity = repository.findById( parentId ).get();
		SensorInstance assignment = registry.project( SensorInstance.class, childId);

	    // ------------------------------------------
		// assign the Sensor to the parent entity
		// ------------------------------------------ 
	    parentEntity.setSensor( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Sensor
	 * 
	 * @param	parentId		UUID
	 * @return	TelemetryStream
	 */
	public TelemetryStream unAssignSensor( UUID parentId ) {
		TelemetryStream parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Sensor on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Sensor on the parent entithy
		// ------------------------------------------     
	    parentEntity.setSensor(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a Schema
     * 
     * @param	parentId	UUID
     * @param	childId		UUID
     * @return	TelemetryStream
     */
    public TelemetryStream assignSchema( UUID parentId, UUID childId ) {
	    LOGGER.info("assigning Schema as " + assignment.toString() );

	    TelemetryStream parentEntity = repository.findById( parentId ).get();
		TelemetrySchema assignment = registry.project( TelemetrySchema.class, childId);

	    // ------------------------------------------
		// assign the Schema to the parent entity
		// ------------------------------------------ 
	    parentEntity.setSchema( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Schema
	 * 
	 * @param	parentId		UUID
	 * @return	TelemetryStream
	 */
	public TelemetryStream unAssignSchema( UUID parentId ) {
		TelemetryStream parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Schema on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Schema on the parent entithy
		// ------------------------------------------     
	    parentEntity.setSchema(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a MessagingEndpoint
     * 
     * @param	parentId	UUID
     * @param	childId		UUID
     * @return	TelemetryStream
     */
    public TelemetryStream assignMessagingEndpoint( UUID parentId, UUID childId ) {
	    LOGGER.info("assigning MessagingEndpoint as " + assignment.toString() );

	    TelemetryStream parentEntity = repository.findById( parentId ).get();
		MessagingEndpoint assignment = registry.project( MessagingEndpoint.class, childId);

	    // ------------------------------------------
		// assign the MessagingEndpoint to the parent entity
		// ------------------------------------------ 
	    parentEntity.setMessagingEndpoint( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the MessagingEndpoint
	 * 
	 * @param	parentId		UUID
	 * @return	TelemetryStream
	 */
	public TelemetryStream unAssignMessagingEndpoint( UUID parentId ) {
		TelemetryStream parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning MessagingEndpoint on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the MessagingEndpoint on the parent entithy
		// ------------------------------------------     
	    parentEntity.setMessagingEndpoint(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a RetentionPolicy
     * 
     * @param	parentId	UUID
     * @param	childId		UUID
     * @return	TelemetryStream
     */
    public TelemetryStream assignRetentionPolicy( UUID parentId, UUID childId ) {
	    LOGGER.info("assigning RetentionPolicy as " + assignment.toString() );

	    TelemetryStream parentEntity = repository.findById( parentId ).get();
		DataRetentionPolicy assignment = registry.project( DataRetentionPolicy.class, childId);

	    // ------------------------------------------
		// assign the RetentionPolicy to the parent entity
		// ------------------------------------------ 
	    parentEntity.setRetentionPolicy( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the RetentionPolicy
	 * 
	 * @param	parentId		UUID
	 * @return	TelemetryStream
	 */
	public TelemetryStream unAssignRetentionPolicy( UUID parentId ) {
		TelemetryStream parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning RetentionPolicy on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the RetentionPolicy on the parent entithy
		// ------------------------------------------     
	    parentEntity.setRetentionPolicy(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}




    /**
     * Method to retrieve the TelemetryStream via an FindTelemetryStreamQuery
     * @return 	query	FindTelemetryStreamQuery
     */
    @SuppressWarnings("unused")
    public TelemetryStream find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a TelemetryStream - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all TelemetryStreams
     *
     * @param	query	FindAllTelemetryStreamQuery 
     * @return 	List<TelemetryStream> 
     */
    @SuppressWarnings("unused")
    public List<TelemetryStream> findAll( FindAllTelemetryStreamQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all TelemetryStream - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final TelemetryStreamRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(TelemetryStreamEntityProjector.class.getName());

}
