/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import org.axonframework.config.ProcessingGroup;
import org.axonframework.eventhandling.EventHandler;
import org.axonframework.queryhandling.QueryHandler;
import org.axonframework.queryhandling.QueryUpdateEmitter;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>TwinChangeEventProjector</h2>
 * <p>
 * The TwinChangeEvent Projector is responsible for maintaining the read model for
 * TwinChangeEvent entities. It subscribes to domain events published by the TwinChangeEvent
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul><li>QueryGateway</li></ul>
 *
 * <h3>Queries Handled</h3>
 *		<ul>
 *      <li>FindTwinChangeEventQuery</li>
 *      <li>FindAllTwinChangeEventQuery</li>
 *		</ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
//@ProcessingGroup("twinChangeEvent")
@Component("twinChangeEvent-projector")
public class TwinChangeEventProjector extends TwinChangeEventEntityProjector {
		
	// core constructor
	public TwinChangeEventProjector(ProjectorRegistry registry,
									TwinChangeEventRepository repository,
									QueryUpdateEmitter queryUpdateEmitter ) {
        super(registry, repository);
        this.queryUpdateEmitter = queryUpdateEmitter;
    }	

	/*
     * @param	event CreateTwinChangeEventEvent
     */
    @EventHandler( payloadType=CreateTwinChangeEventEvent.class )
    public void handle( CreateTwinChangeEventEvent event) {
	    LOGGER.info("handling CreateTwinChangeEventEvent - " + event );
	    TwinChangeEvent entity = new TwinChangeEvent();
            entity.setTwinChangeEventId( event.getTwinChangeEventId() );
            entity.setEventId( event.getEventId() );
            entity.setOccurredAt( event.getOccurredAt() );
            entity.setChangeType( event.getChangeType() );
	    
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    create(entity);
        
        // ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllTwinChangeEvent( entity );
    }

    /*
     * @param	event UpdateTwinChangeEventEvent
     */
    @EventHandler( payloadType=UpdateTwinChangeEventEvent.class )
    public void handle( UpdateTwinChangeEventEvent event) {
    	LOGGER.info("handling UpdateTwinChangeEventEvent - " + event );
    	
	    TwinChangeEvent entity = new TwinChangeEvent();
            entity.setTwinChangeEventId( event.getTwinChangeEventId() );
            entity.setEventId( event.getEventId() );
            entity.setOccurredAt( event.getOccurredAt() );
            entity.setTwin( event.getTwin() );
            entity.setChangeType( event.getChangeType() );
 
    	// ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		update(entity);

    	// ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindTwinChangeEvent( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllTwinChangeEvent( entity );        
    }
    
    /*
     * @param	event DeleteTwinChangeEventEvent
     */
    @EventHandler( payloadType=DeleteTwinChangeEventEvent.class )
    public void handle( DeleteTwinChangeEventEvent event) {
    	LOGGER.info("handling DeleteTwinChangeEventEvent - " + event );
    	
    	// ------------------------------------------
    	// delete delegation
    	// ------------------------------------------
    	TwinChangeEvent entity = delete( event.getTwinChangeEventId() );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllTwinChangeEvent( entity );

    }    

    /*
     * @param	event AssignTwinToTwinChangeEventEvent
     */
    @EventHandler( payloadType=AssignTwinToTwinChangeEventEvent.class)
    public void handle( AssignTwinToTwinChangeEventEvent event) {
	    LOGGER.info("handling AssignTwinToTwinChangeEventEvent - " + event );

	    // ------------------------------------------
	    // delegate to assignTo
	    // ------------------------------------------
	    TwinChangeEvent entity = assignTwin( event.getChildId(), event.getAssignment() );

	    // ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindTwinChangeEvent( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllTwinChangeEvent( entity );
    }
    

	/*
	 * @param	event UnAssignTwinFromTwinChangeEventEvent
	 */
	@EventHandler( payloadType=UnAssignTwinFromTwinChangeEventEvent.class)
	public void handle( UnAssignTwinFromTwinChangeEventEvent event) {
	    LOGGER.info("handling UnAssignTwinFromTwinChangeEventEvent - " + event );

	    // ------------------------------------------
	    // delegate to unAssignFrom
	    // ------------------------------------------
	    TwinChangeEvent entity = unAssignTwin( event.getChildId() );

		// ------------------------------------------
		// emit to subscribers that find one
		// ------------------------------------------    	
	    emitFindTwinChangeEvent( entity );
	
		// ------------------------------------------
		// emit to subscribers that find all
		// ------------------------------------------    	
	    emitFindAllTwinChangeEvent( entity );
	}




    /**
     * Method to retrieve the TwinChangeEvent via an TwinChangeEventPrimaryKey.
     * @param 	id Long
     * @return 	TwinChangeEvent
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    @SuppressWarnings("unused")
    @QueryHandler
    public TwinChangeEvent handle( FindTwinChangeEventQuery query ) 
    throws ProcessingException, IllegalArgumentException {
    	return find( query.getFilter().getTwinChangeEventId() );
    }
    
    /**
     * Method to retrieve a collection of all TwinChangeEvents
     *
     * @param	query	FindAllTwinChangeEventQuery 
     * @return 	List<TwinChangeEvent> 
     * @exception ProcessingException Thrown if any problems
     */
    @SuppressWarnings("unused")
    @QueryHandler
    public List<TwinChangeEvent> handle( FindAllTwinChangeEventQuery query ) throws ProcessingException {
    	return findAll( query );
    }



/**
 * emit to subscription queries of type FindTwinChangeEvent,
 * but only if the id matches
 *
 * @param		entity	TwinChangeEvent
 */
	protected void emitFindTwinChangeEvent( TwinChangeEvent entity ) {
		LOGGER.info("handling emitFindTwinChangeEvent" );
		
	    queryUpdateEmitter.emit(FindTwinChangeEventQuery.class,
	                            query -> query.getFilter().getTwinChangeEventId().equals(entity.getTwinChangeEventId()),
	                            entity);
	}
	
	/**
	 * unconditionally emit to subscription queries of type FindAllTwinChangeEvent
	 * 
	 * @param		entity	TwinChangeEvent
	 */
	protected void emitFindAllTwinChangeEvent( TwinChangeEvent entity ) {
		LOGGER.info("handling emitFindAllTwinChangeEvent" );
		
	    queryUpdateEmitter.emit(FindAllTwinChangeEventQuery.class,
	                            query -> true,
	                            entity);
	}

	//--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
	private final QueryUpdateEmitter queryUpdateEmitter;
    private static final Logger LOGGER 	= Logger.getLogger(TwinChangeEventProjector.class.getName());

}
