
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * Healthcare Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace healthcareonaspdotnet.Domain;

/// <summary>
/// AdministrativeSex enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum AdministrativeSex
{
    Male=1,Female=2,Unknown=3
}

/// <summary>
/// Extension of capabilities for the AdministrativeSex enum
/// </summary>
public static class AdministrativeSexExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<AdministrativeSex> GetValues()
    {
        return Enum.GetValues<AdministrativeSex>().ToList();
    }

    public static AdministrativeSex GetDefaultValue()
    {
        return Enum.GetValues<AdministrativeSex>().First();
    }

    public static AdministrativeSex WhichOne(string name)
    {
        if (Enum.TryParse<AdministrativeSex>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



