
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * Healthcare Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace healthcareonaspdotnet.Domain;

/// <summary>
/// ResultStatus enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum ResultStatus
{
    Registered=1,Partial=2,Final=3,Corrected=4,Cancelled=5
}

/// <summary>
/// Extension of capabilities for the ResultStatus enum
/// </summary>
public static class ResultStatusExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<ResultStatus> GetValues()
    {
        return Enum.GetValues<ResultStatus>().ToList();
    }

    public static ResultStatus GetDefaultValue()
    {
        return Enum.GetValues<ResultStatus>().First();
    }

    public static ResultStatus WhichOne(string name)
    {
        if (Enum.TryParse<ResultStatus>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



