/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>ApiKeyValidation</h2>
 * <p>
 * The ApiKey Validation  handles state validation of a ApiKey include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateApiKeyCommand</li>
 *      <li>UpdateApiKeyCommand</li>
 *      <li>DeleteApiKeyCommand</li>
 *set( false = false )
  *       <li>AssignAccessPolicyToApiKeyCommand</li>
 *       <li>UnAssignAccessPolicyFromApiKeyCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class ApiKeyValidator {

	/**
	 * default constructor
	 */
	protected ApiKeyValidator() {
	}


	/**
	 * handles creation validation for a ApiKey
	 */
	public void validate( CreateApiKeyCommand apiKey )throws ValidationException {
		if ( apiKey == null )
		throw new ValidationException( "ApiKey", "validating CreateApiKeyCommand" );
		if ( apiKey.getKeyId() == null )
		throw new ValidationException( "ApiKey", "validating access on getKeyId" );
		if ( apiKey.getHashedSecret() == null )
		throw new ValidationException( "ApiKey", "validating access on getHashedSecret" );
		if ( apiKey.getCreatedAt() == null )
		throw new ValidationException( "ApiKey", "validating access on getCreatedAt" );
		if ( apiKey.getLastUsedAt() == null )
		throw new ValidationException( "ApiKey", "validating access on getLastUsedAt" );
	}

	/**
	 * handles update validation for a ApiKey
	 */
	public void validate( UpdateApiKeyCommand apiKey ) throws ValidationException {
		if ( apiKey == null )
		throw new ValidationException( "ApiKey", "validating UpdateApiKeyCommand" );
		if ( apiKey.getKeyId() == null )
		throw new ValidationException( "ApiKey", "validating method getKeyId" );
		if ( apiKey.getHashedSecret() == null )
		throw new ValidationException( "ApiKey", "validating method getHashedSecret" );
		if ( apiKey.getCreatedAt() == null )
		throw new ValidationException( "ApiKey", "validating method getCreatedAt" );
		if ( apiKey.getLastUsedAt() == null )
		throw new ValidationException( "ApiKey", "validating method getLastUsedAt" );
	}

/**
 * handles delete validation for a ApiKey
 */
	public void validate( DeleteApiKeyCommand apiKey ) throws ValidationException {
		if ( apiKey == null )
			throw new ValidationException( "ApiKey", "validating DeleteApiKeyCommand" );
	}

/**
 * handles fetchOne validation for a ApiKey
 */
	public void validate( ApiKeyFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "ApiKey", "validating summary" );
	}

	/**
	 * handles assign AccessPolicy validation for a ApiKey
	 *
	 * @param	command AssignAccessPolicyToApiKeyCommand
	 */
	public void validate( AssignAccessPolicyToApiKeyCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "ApiKey", "validating AssignAccessPolicyToApiKeyCommand" );

		if ( command.getApiKeyId() == null )
		throw new ValidationException( "ApiKey", "validating identifier on AssignAccessPolicyToApiKeyCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "ApiKey", "validating assignment" );
	}

	/**
	 * handles unassign AccessPolicy validation for a ApiKey
	 *
	 * @param	command UnAssignAccessPolicyFromApiKeyCommand
	 */
	public void validate( UnAssignAccessPolicyFromApiKeyCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "ApiKey", "validating UnAssignAccessPolicyFromApiKeyCommand" );

		if ( command.getApiKeyId() == null )
		throw new ValidationException( "ApiKey", "validating identity on UnAssignAccessPolicyFromApiKeyCommand" );
	}


}
