/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>BuildingValidation</h2>
 * <p>
 * The Building Validation  handles state validation of a Building include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateBuildingCommand</li>
 *      <li>UpdateBuildingCommand</li>
 *      <li>DeleteBuildingCommand</li>
 *set( false = false )
  *       <li>AssignSiteToBuildingCommand</li>
 *       <li>UnAssignSiteFromBuildingCommand</li>
   *       <li>AssignFloorsToBuildingCommand</li>
 *       <li>RemoveFloorsFromBuildingCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class BuildingValidator {

	/**
	 * default constructor
	 */
	protected BuildingValidator() {
	}


	/**
	 * handles creation validation for a Building
	 */
	public void validate( CreateBuildingCommand building )throws ValidationException {
		if ( building == null )
		throw new ValidationException( "Building", "validating CreateBuildingCommand" );
		if ( building.getName() == null )
		throw new ValidationException( "Building", "validating access on getName" );
	}

	/**
	 * handles update validation for a Building
	 */
	public void validate( UpdateBuildingCommand building ) throws ValidationException {
		if ( building == null )
		throw new ValidationException( "Building", "validating UpdateBuildingCommand" );
		if ( building.getName() == null )
		throw new ValidationException( "Building", "validating method getName" );
	}

/**
 * handles delete validation for a Building
 */
	public void validate( DeleteBuildingCommand building ) throws ValidationException {
		if ( building == null )
			throw new ValidationException( "Building", "validating DeleteBuildingCommand" );
	}

/**
 * handles fetchOne validation for a Building
 */
	public void validate( BuildingFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Building", "validating summary" );
	}

	/**
	 * handles assign Site validation for a Building
	 *
	 * @param	command AssignSiteToBuildingCommand
	 */
	public void validate( AssignSiteToBuildingCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Building", "validating AssignSiteToBuildingCommand" );

		if ( command.getBuildingId() == null )
		throw new ValidationException( "Building", "validating identifier on AssignSiteToBuildingCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "Building", "validating assignment" );
	}

	/**
	 * handles unassign Site validation for a Building
	 *
	 * @param	command UnAssignSiteFromBuildingCommand
	 */
	public void validate( UnAssignSiteFromBuildingCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Building", "validating UnAssignSiteFromBuildingCommand" );

		if ( command.getBuildingId() == null )
		throw new ValidationException( "Building", "validating identity on UnAssignSiteFromBuildingCommand" );
	}

	/**
	 * handles add to Floors validation for a Building
	 *
	 * @param	command AssignFloorsToBuildingCommand
	 */
	public void validate( AssignFloorsToBuildingCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Building", "validating AssignFloorsToBuildingCommand" );

		if ( command.getBuildingId() == null )
		throw new ValidationException( "Building", "validating identity on AssignFloorsToBuildingCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Building", "validating addTo attribute on AssignFloorsToBuildingCommand" );

	}

	/**
	 * handles remove from Floors validation for a Building
	 *
	 * @param	command RemoveFloorsFromBuildingCommand
	 */
	public void validate( RemoveFloorsFromBuildingCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Building", "validating RemoveFloorsFromBuildingCommand" );

		if( command.getBuildingId() == null )
			throw new ValidationException("Building", "validating id on RemoveFloorsFromBuildingCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Building", "validating remove from RemoveFloorsFromBuildingCommand" );

		if( command.getRemoveFrom().getFloorId() == null )
			throw new ValidationException("Building", "validating id on remove from RemoveFloorsFromBuildingCommand" );
	}


}
