/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>DeviceGroupValidation</h2>
 * <p>
 * The DeviceGroup Validation  handles state validation of a DeviceGroup include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateDeviceGroupCommand</li>
 *      <li>UpdateDeviceGroupCommand</li>
 *      <li>DeleteDeviceGroupCommand</li>
 *set( false = false )
  *       <li>AssignTenantToDeviceGroupCommand</li>
 *       <li>UnAssignTenantFromDeviceGroupCommand</li>
   *       <li>AssignDevicesToDeviceGroupCommand</li>
 *       <li>RemoveDevicesFromDeviceGroupCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class DeviceGroupValidator {

	/**
	 * default constructor
	 */
	protected DeviceGroupValidator() {
	}


	/**
	 * handles creation validation for a DeviceGroup
	 */
	public void validate( CreateDeviceGroupCommand deviceGroup )throws ValidationException {
		if ( deviceGroup == null )
		throw new ValidationException( "DeviceGroup", "validating CreateDeviceGroupCommand" );
		if ( deviceGroup.getName() == null )
		throw new ValidationException( "DeviceGroup", "validating access on getName" );
		if ( deviceGroup.getCriteria() == null )
		throw new ValidationException( "DeviceGroup", "validating access on getCriteria" );
	}

	/**
	 * handles update validation for a DeviceGroup
	 */
	public void validate( UpdateDeviceGroupCommand deviceGroup ) throws ValidationException {
		if ( deviceGroup == null )
		throw new ValidationException( "DeviceGroup", "validating UpdateDeviceGroupCommand" );
		if ( deviceGroup.getName() == null )
		throw new ValidationException( "DeviceGroup", "validating method getName" );
		if ( deviceGroup.getCriteria() == null )
		throw new ValidationException( "DeviceGroup", "validating method getCriteria" );
	}

/**
 * handles delete validation for a DeviceGroup
 */
	public void validate( DeleteDeviceGroupCommand deviceGroup ) throws ValidationException {
		if ( deviceGroup == null )
			throw new ValidationException( "DeviceGroup", "validating DeleteDeviceGroupCommand" );
	}

/**
 * handles fetchOne validation for a DeviceGroup
 */
	public void validate( DeviceGroupFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "DeviceGroup", "validating summary" );
	}

	/**
	 * handles assign Tenant validation for a DeviceGroup
	 *
	 * @param	command AssignTenantToDeviceGroupCommand
	 */
	public void validate( AssignTenantToDeviceGroupCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "DeviceGroup", "validating AssignTenantToDeviceGroupCommand" );

		if ( command.getDeviceGroupId() == null )
		throw new ValidationException( "DeviceGroup", "validating identifier on AssignTenantToDeviceGroupCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "DeviceGroup", "validating assignment" );
	}

	/**
	 * handles unassign Tenant validation for a DeviceGroup
	 *
	 * @param	command UnAssignTenantFromDeviceGroupCommand
	 */
	public void validate( UnAssignTenantFromDeviceGroupCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "DeviceGroup", "validating UnAssignTenantFromDeviceGroupCommand" );

		if ( command.getDeviceGroupId() == null )
		throw new ValidationException( "DeviceGroup", "validating identity on UnAssignTenantFromDeviceGroupCommand" );
	}

	/**
	 * handles add to Devices validation for a DeviceGroup
	 *
	 * @param	command AssignDevicesToDeviceGroupCommand
	 */
	public void validate( AssignDevicesToDeviceGroupCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "DeviceGroup", "validating AssignDevicesToDeviceGroupCommand" );

		if ( command.getDeviceGroupId() == null )
		throw new ValidationException( "DeviceGroup", "validating identity on AssignDevicesToDeviceGroupCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "DeviceGroup", "validating addTo attribute on AssignDevicesToDeviceGroupCommand" );

	}

	/**
	 * handles remove from Devices validation for a DeviceGroup
	 *
	 * @param	command RemoveDevicesFromDeviceGroupCommand
	 */
	public void validate( RemoveDevicesFromDeviceGroupCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("DeviceGroup", "validating RemoveDevicesFromDeviceGroupCommand" );

		if( command.getDeviceGroupId() == null )
			throw new ValidationException("DeviceGroup", "validating id on RemoveDevicesFromDeviceGroupCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("DeviceGroup", "validating remove from RemoveDevicesFromDeviceGroupCommand" );

		if( command.getRemoveFrom().getIoTDeviceId() == null )
			throw new ValidationException("DeviceGroup", "validating id on remove from RemoveDevicesFromDeviceGroupCommand" );
	}


}
