/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Insurance Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>InsurerValidation</h2>
 * <p>
 * The Insurer Validation  handles state validation of a Insurer include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Insurance Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core insurance product, underwriting, policy, billing, claims, and reinsurance capabilities.</td></tr>
 *          <tr><td>industry</td><td>Insurance</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateInsurerCommand</li>
 *      <li>UpdateInsurerCommand</li>
 *      <li>DeleteInsurerCommand</li>
 *set( false = false )
   *       <li>AssignProductsToInsurerCommand</li>
 *       <li>RemoveProductsFromInsurerCommand</li>
 *   </ul>
 *
  *       <li>AssignDistributionPartnersToInsurerCommand</li>
 *       <li>RemoveDistributionPartnersFromInsurerCommand</li>
 *   </ul>
 *
  *       <li>AssignPoliciesToInsurerCommand</li>
 *       <li>RemovePoliciesFromInsurerCommand</li>
 *   </ul>
 *
  *       <li>AssignClaimsToInsurerCommand</li>
 *       <li>RemoveClaimsFromInsurerCommand</li>
 *   </ul>
 *
  *       <li>AssignReinsuranceAgreementsToInsurerCommand</li>
 *       <li>RemoveReinsuranceAgreementsFromInsurerCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class InsurerValidator {

	/**
	 * default constructor
	 */
	protected InsurerValidator() {
	}


	/**
	 * handles creation validation for a Insurer
	 */
	public void validate( CreateInsurerCommand insurer )throws ValidationException {
		if ( insurer == null )
		throw new ValidationException( "Insurer", "validating CreateInsurerCommand" );
		if ( insurer.getName() == null )
		throw new ValidationException( "Insurer", "validating access on getName" );
		if ( insurer.getLegalName() == null )
		throw new ValidationException( "Insurer", "validating access on getLegalName" );
		if ( insurer.getDomicileCountry() == null )
		throw new ValidationException( "Insurer", "validating access on getDomicileCountry" );
		if ( insurer.getNaicNumber() == null )
		throw new ValidationException( "Insurer", "validating access on getNaicNumber" );
		if ( insurer.getWebsite() == null )
		throw new ValidationException( "Insurer", "validating access on getWebsite" );
	}

	/**
	 * handles update validation for a Insurer
	 */
	public void validate( UpdateInsurerCommand insurer ) throws ValidationException {
		if ( insurer == null )
		throw new ValidationException( "Insurer", "validating UpdateInsurerCommand" );
		if ( insurer.getName() == null )
		throw new ValidationException( "Insurer", "validating method getName" );
		if ( insurer.getLegalName() == null )
		throw new ValidationException( "Insurer", "validating method getLegalName" );
		if ( insurer.getDomicileCountry() == null )
		throw new ValidationException( "Insurer", "validating method getDomicileCountry" );
		if ( insurer.getNaicNumber() == null )
		throw new ValidationException( "Insurer", "validating method getNaicNumber" );
		if ( insurer.getWebsite() == null )
		throw new ValidationException( "Insurer", "validating method getWebsite" );
	}

/**
 * handles delete validation for a Insurer
 */
	public void validate( DeleteInsurerCommand insurer ) throws ValidationException {
		if ( insurer == null )
			throw new ValidationException( "Insurer", "validating DeleteInsurerCommand" );
	}

/**
 * handles fetchOne validation for a Insurer
 */
	public void validate( InsurerFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Insurer", "validating summary" );
	}


	/**
	 * handles add to Products validation for a Insurer
	 *
	 * @param	command AssignProductsToInsurerCommand
	 */
	public void validate( AssignProductsToInsurerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Insurer", "validating AssignProductsToInsurerCommand" );

		if ( command.getInsurerId() == null )
		throw new ValidationException( "Insurer", "validating identity on AssignProductsToInsurerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Insurer", "validating addTo attribute on AssignProductsToInsurerCommand" );

	}

	/**
	 * handles remove from Products validation for a Insurer
	 *
	 * @param	command RemoveProductsFromInsurerCommand
	 */
	public void validate( RemoveProductsFromInsurerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Insurer", "validating RemoveProductsFromInsurerCommand" );

		if( command.getInsurerId() == null )
			throw new ValidationException("Insurer", "validating id on RemoveProductsFromInsurerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Insurer", "validating remove from RemoveProductsFromInsurerCommand" );

		if( command.getRemoveFrom().getInsuranceProductId() == null )
			throw new ValidationException("Insurer", "validating id on remove from RemoveProductsFromInsurerCommand" );
	}

	/**
	 * handles add to DistributionPartners validation for a Insurer
	 *
	 * @param	command AssignDistributionPartnersToInsurerCommand
	 */
	public void validate( AssignDistributionPartnersToInsurerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Insurer", "validating AssignDistributionPartnersToInsurerCommand" );

		if ( command.getInsurerId() == null )
		throw new ValidationException( "Insurer", "validating identity on AssignDistributionPartnersToInsurerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Insurer", "validating addTo attribute on AssignDistributionPartnersToInsurerCommand" );

	}

	/**
	 * handles remove from DistributionPartners validation for a Insurer
	 *
	 * @param	command RemoveDistributionPartnersFromInsurerCommand
	 */
	public void validate( RemoveDistributionPartnersFromInsurerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Insurer", "validating RemoveDistributionPartnersFromInsurerCommand" );

		if( command.getInsurerId() == null )
			throw new ValidationException("Insurer", "validating id on RemoveDistributionPartnersFromInsurerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Insurer", "validating remove from RemoveDistributionPartnersFromInsurerCommand" );

		if( command.getRemoveFrom().getDistributorId() == null )
			throw new ValidationException("Insurer", "validating id on remove from RemoveDistributionPartnersFromInsurerCommand" );
	}

	/**
	 * handles add to Policies validation for a Insurer
	 *
	 * @param	command AssignPoliciesToInsurerCommand
	 */
	public void validate( AssignPoliciesToInsurerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Insurer", "validating AssignPoliciesToInsurerCommand" );

		if ( command.getInsurerId() == null )
		throw new ValidationException( "Insurer", "validating identity on AssignPoliciesToInsurerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Insurer", "validating addTo attribute on AssignPoliciesToInsurerCommand" );

	}

	/**
	 * handles remove from Policies validation for a Insurer
	 *
	 * @param	command RemovePoliciesFromInsurerCommand
	 */
	public void validate( RemovePoliciesFromInsurerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Insurer", "validating RemovePoliciesFromInsurerCommand" );

		if( command.getInsurerId() == null )
			throw new ValidationException("Insurer", "validating id on RemovePoliciesFromInsurerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Insurer", "validating remove from RemovePoliciesFromInsurerCommand" );

		if( command.getRemoveFrom().getPolicyId() == null )
			throw new ValidationException("Insurer", "validating id on remove from RemovePoliciesFromInsurerCommand" );
	}

	/**
	 * handles add to Claims validation for a Insurer
	 *
	 * @param	command AssignClaimsToInsurerCommand
	 */
	public void validate( AssignClaimsToInsurerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Insurer", "validating AssignClaimsToInsurerCommand" );

		if ( command.getInsurerId() == null )
		throw new ValidationException( "Insurer", "validating identity on AssignClaimsToInsurerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Insurer", "validating addTo attribute on AssignClaimsToInsurerCommand" );

	}

	/**
	 * handles remove from Claims validation for a Insurer
	 *
	 * @param	command RemoveClaimsFromInsurerCommand
	 */
	public void validate( RemoveClaimsFromInsurerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Insurer", "validating RemoveClaimsFromInsurerCommand" );

		if( command.getInsurerId() == null )
			throw new ValidationException("Insurer", "validating id on RemoveClaimsFromInsurerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Insurer", "validating remove from RemoveClaimsFromInsurerCommand" );

		if( command.getRemoveFrom().getClaimId() == null )
			throw new ValidationException("Insurer", "validating id on remove from RemoveClaimsFromInsurerCommand" );
	}

	/**
	 * handles add to ReinsuranceAgreements validation for a Insurer
	 *
	 * @param	command AssignReinsuranceAgreementsToInsurerCommand
	 */
	public void validate( AssignReinsuranceAgreementsToInsurerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Insurer", "validating AssignReinsuranceAgreementsToInsurerCommand" );

		if ( command.getInsurerId() == null )
		throw new ValidationException( "Insurer", "validating identity on AssignReinsuranceAgreementsToInsurerCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Insurer", "validating addTo attribute on AssignReinsuranceAgreementsToInsurerCommand" );

	}

	/**
	 * handles remove from ReinsuranceAgreements validation for a Insurer
	 *
	 * @param	command RemoveReinsuranceAgreementsFromInsurerCommand
	 */
	public void validate( RemoveReinsuranceAgreementsFromInsurerCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Insurer", "validating RemoveReinsuranceAgreementsFromInsurerCommand" );

		if( command.getInsurerId() == null )
			throw new ValidationException("Insurer", "validating id on RemoveReinsuranceAgreementsFromInsurerCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Insurer", "validating remove from RemoveReinsuranceAgreementsFromInsurerCommand" );

		if( command.getRemoveFrom().getReinsuranceAgreementId() == null )
			throw new ValidationException("Insurer", "validating id on remove from RemoveReinsuranceAgreementsFromInsurerCommand" );
	}


}
