/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>OfficeValidation</h2>
 * <p>
 * The Office Validation  handles state validation of a Office include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/05/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateOfficeCommand</li>
 *      <li>UpdateOfficeCommand</li>
 *      <li>DeleteOfficeCommand</li>
 *set( false = false )
  *       <li>AssignFirmToOfficeCommand</li>
 *       <li>UnAssignFirmFromOfficeCommand</li>
   *       <li>AssignAdvisorsToOfficeCommand</li>
 *       <li>RemoveAdvisorsFromOfficeCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class OfficeValidator {

	/**
	 * default constructor
	 */
	protected OfficeValidator() {
	}


	/**
	 * handles creation validation for a Office
	 */
	public void validate( CreateOfficeCommand office )throws ValidationException {
		if ( office == null )
		throw new ValidationException( "Office", "validating CreateOfficeCommand" );
		if ( office.getName() == null )
		throw new ValidationException( "Office", "validating access on getName" );
		if ( office.getAddress() == null )
		throw new ValidationException( "Office", "validating access on getAddress" );
	}

	/**
	 * handles update validation for a Office
	 */
	public void validate( UpdateOfficeCommand office ) throws ValidationException {
		if ( office == null )
		throw new ValidationException( "Office", "validating UpdateOfficeCommand" );
		if ( office.getName() == null )
		throw new ValidationException( "Office", "validating method getName" );
		if ( office.getAddress() == null )
		throw new ValidationException( "Office", "validating method getAddress" );
	}

/**
 * handles delete validation for a Office
 */
	public void validate( DeleteOfficeCommand office ) throws ValidationException {
		if ( office == null )
			throw new ValidationException( "Office", "validating DeleteOfficeCommand" );
	}

/**
 * handles fetchOne validation for a Office
 */
	public void validate( OfficeFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Office", "validating summary" );
	}

	/**
	 * handles assign Firm validation for a Office
	 *
	 * @param	command AssignFirmToOfficeCommand
	 */
	public void validate( AssignFirmToOfficeCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Office", "validating AssignFirmToOfficeCommand" );

		if ( command.getOfficeId() == null )
		throw new ValidationException( "Office", "validating identifier on AssignFirmToOfficeCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "Office", "validating assignment" );
	}

	/**
	 * handles unassign Firm validation for a Office
	 *
	 * @param	command UnAssignFirmFromOfficeCommand
	 */
	public void validate( UnAssignFirmFromOfficeCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Office", "validating UnAssignFirmFromOfficeCommand" );

		if ( command.getOfficeId() == null )
		throw new ValidationException( "Office", "validating identity on UnAssignFirmFromOfficeCommand" );
	}

	/**
	 * handles add to Advisors validation for a Office
	 *
	 * @param	command AssignAdvisorsToOfficeCommand
	 */
	public void validate( AssignAdvisorsToOfficeCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Office", "validating AssignAdvisorsToOfficeCommand" );

		if ( command.getOfficeId() == null )
		throw new ValidationException( "Office", "validating identity on AssignAdvisorsToOfficeCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Office", "validating addTo attribute on AssignAdvisorsToOfficeCommand" );

	}

	/**
	 * handles remove from Advisors validation for a Office
	 *
	 * @param	command RemoveAdvisorsFromOfficeCommand
	 */
	public void validate( RemoveAdvisorsFromOfficeCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Office", "validating RemoveAdvisorsFromOfficeCommand" );

		if( command.getOfficeId() == null )
			throw new ValidationException("Office", "validating id on RemoveAdvisorsFromOfficeCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Office", "validating remove from RemoveAdvisorsFromOfficeCommand" );

		if( command.getRemoveFrom().getAdvisorId() == null )
			throw new ValidationException("Office", "validating id on remove from RemoveAdvisorsFromOfficeCommand" );
	}


}
