
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * Manufacturing Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace manufacturingonaspdotnet.Domain;

/// <summary>
/// ReceiptStatus enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum ReceiptStatus
{
    Open=1,PartiallyProcessed=2,Completed=3,Rejected=4
}

/// <summary>
/// Extension of capabilities for the ReceiptStatus enum
/// </summary>
public static class ReceiptStatusExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<ReceiptStatus> GetValues()
    {
        return Enum.GetValues<ReceiptStatus>().ToList();
    }

    public static ReceiptStatus GetDefaultValue()
    {
        return Enum.GetValues<ReceiptStatus>().First();
    }

    public static ReceiptStatus WhichOne(string name)
    {
        if (Enum.TryParse<ReceiptStatus>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



