package com.globalbank.aggregate;

import com.globalbank.api.*;
import com.globalbank.entity.*;
import com.globalbank.exception.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.axonframework.commandhandling.CommandHandler;
import org.axonframework.modelling.command.AggregateMember;
import org.axonframework.eventsourcing.EventSourcingHandler;
import org.axonframework.modelling.command.AggregateIdentifier;
import static org.axonframework.modelling.command.AggregateLifecycle.apply;
import org.axonframework.spring.stereotype.Aggregate;
import org.springframework.context.annotation.Profile;

/**
 * <h2>FXTradeAggregate</h2>
 * <p>
 * The FXTrade aggregate is the authoritative consistency boundary for all
 * branch-related operations. It validates incoming commands, enforces
 * business rules, maintains the integrity of the FXTrade domain, and emits
 * immutable domain events representing state changes.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/12/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateFXTradeCommand</li>
 *      <li>UpdateFXTradeCommand</li>
 *      <li>DeleteFXTradeCommand</li>
 *      </ul>
 *
 * <h3>Associations</h3>
 * <ul>
 *       <li>AssignCustomerToFXTradeCommand</li>
 *       <li>UnAssignCustomerFromFXTradeCommand</li>
 *       <li>AssignBankToFXTradeCommand</li>
 *       <li>UnAssignBankFromFXTradeCommand</li>
 *       <li>AssignExchangeRateToFXTradeCommand</li>
 *       <li>UnAssignExchangeRateFromFXTradeCommand</li>
 *       <li>AssignSourceAccountToFXTradeCommand</li>
 *       <li>UnAssignSourceAccountFromFXTradeCommand</li>
 *       <li>AssignDestinationAccountToFXTradeCommand</li>
 *       <li>UnAssignDestinationAccountFromFXTradeCommand</li>
 *       <li>AssignTransactionToFXTradeCommand</li>
 *       <li>UnAssignTransactionFromFXTradeCommand</li>
 *  </ul>
 *  <ul>
 *
 *
 * <h3>Events Emitted</h3>
 *      <ul>
 *      <li>CreateFXTradeEvent</li>
 *      <li>UpdateFXTradeEvent</li>
 *      <li>DeleteFXTradeEvent</li>
   *       <li>AssignCustomerToFXTradeEvent</li>
 *       <li>UnAssignCustomerFromFXTradeEvent</li>
  *       <li>AssignBankToFXTradeEvent</li>
 *       <li>UnAssignBankFromFXTradeEvent</li>
  *       <li>AssignExchangeRateToFXTradeEvent</li>
 *       <li>UnAssignExchangeRateFromFXTradeEvent</li>
  *       <li>AssignSourceAccountToFXTradeEvent</li>
 *       <li>UnAssignSourceAccountFromFXTradeEvent</li>
  *       <li>AssignDestinationAccountToFXTradeEvent</li>
 *       <li>UnAssignDestinationAccountFromFXTradeEvent</li>
  *       <li>AssignTransactionToFXTradeEvent</li>
 *       <li>UnAssignTransactionFromFXTradeEvent</li>
   *        </ul>
 *
 * <p>@author your_name_here</p>
 */
@Aggregate
public class FXTradeAggregate {  

	// -----------------------------------------
	// Axon requires an empty constructor
    // -----------------------------------------
    public FXTradeAggregate() {
    }

	// ----------------------------------------------
	// intrinsic command handlers
	// ----------------------------------------------
    @CommandHandler
    public FXTradeAggregate(CreateFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command CreateFXTradeCommand" );
    	CreateFXTradeEvent event = new CreateFXTradeEvent(command.getFXTradeId(), command.getTradeReference(), command.getTradeDate(), command.getSettlementDate(), command.getAmountSold(), command.getAmountBought(), command.getRate(), command.getStatus());
    	
        apply(event);
    }

    @CommandHandler
    public void handle(UpdateFXTradeCommand command) throws Exception {
    	LOGGER.info( "handling command UpdateFXTradeCommand" );
    	UpdateFXTradeEvent event = new UpdateFXTradeEvent(command.getFXTradeId(), command.getTradeReference(), command.getTradeDate(), command.getSettlementDate(), command.getAmountSold(), command.getAmountBought(), command.getRate(), command.getCustomer(), command.getBank(), command.getExchangeRate(), command.getSourceAccount(), command.getDestinationAccount(), command.getTransaction(), command.getStatus());        
    	
        apply(event);
    }

    @CommandHandler
    public void handle(DeleteFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command DeleteFXTradeCommand" );
        apply(new DeleteFXTradeEvent(command.getFXTradeId()));
    }

	// ----------------------------------------------
	// association command handlers
	// ----------------------------------------------

    // single association commands
    @CommandHandler
    public void handle(AssignCustomerToFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignCustomerToFXTradeCommand" );
    	
    	if (  customer != null && customer.getCustomerId() == command.getAssignment().getCustomerId() )
    		throw new ProcessingException( "Customer already assigned with id " + command.getAssignment().getCustomerId() );  
    		
        apply(new AssignCustomerToFXTradeEvent(command.getFXTradeId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignCustomerFromFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command UnAssignCustomerFromFXTradeCommand" );

    	if (  customer == null )
    		throw new ProcessingException( "Customer already has nothing assigned." );  

    	apply(new UnAssignCustomerFromFXTradeEvent(command.getFXTradeId()));
    }
    @CommandHandler
    public void handle(AssignBankToFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignBankToFXTradeCommand" );
    	
    	if (  bank != null && bank.getBankId() == command.getAssignment().getBankId() )
    		throw new ProcessingException( "Bank already assigned with id " + command.getAssignment().getBankId() );  
    		
        apply(new AssignBankToFXTradeEvent(command.getFXTradeId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignBankFromFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command UnAssignBankFromFXTradeCommand" );

    	if (  bank == null )
    		throw new ProcessingException( "Bank already has nothing assigned." );  

    	apply(new UnAssignBankFromFXTradeEvent(command.getFXTradeId()));
    }
    @CommandHandler
    public void handle(AssignExchangeRateToFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignExchangeRateToFXTradeCommand" );
    	
    	if (  exchangeRate != null && exchangeRate.getExchangeRateId() == command.getAssignment().getExchangeRateId() )
    		throw new ProcessingException( "ExchangeRate already assigned with id " + command.getAssignment().getExchangeRateId() );  
    		
        apply(new AssignExchangeRateToFXTradeEvent(command.getFXTradeId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignExchangeRateFromFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command UnAssignExchangeRateFromFXTradeCommand" );

    	if (  exchangeRate == null )
    		throw new ProcessingException( "ExchangeRate already has nothing assigned." );  

    	apply(new UnAssignExchangeRateFromFXTradeEvent(command.getFXTradeId()));
    }
    @CommandHandler
    public void handle(AssignSourceAccountToFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignSourceAccountToFXTradeCommand" );
    	
    	if (  sourceAccount != null && sourceAccount.getAccountId() == command.getAssignment().getAccountId() )
    		throw new ProcessingException( "SourceAccount already assigned with id " + command.getAssignment().getAccountId() );  
    		
        apply(new AssignSourceAccountToFXTradeEvent(command.getFXTradeId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignSourceAccountFromFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command UnAssignSourceAccountFromFXTradeCommand" );

    	if (  sourceAccount == null )
    		throw new ProcessingException( "SourceAccount already has nothing assigned." );  

    	apply(new UnAssignSourceAccountFromFXTradeEvent(command.getFXTradeId()));
    }
    @CommandHandler
    public void handle(AssignDestinationAccountToFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignDestinationAccountToFXTradeCommand" );
    	
    	if (  destinationAccount != null && destinationAccount.getAccountId() == command.getAssignment().getAccountId() )
    		throw new ProcessingException( "DestinationAccount already assigned with id " + command.getAssignment().getAccountId() );  
    		
        apply(new AssignDestinationAccountToFXTradeEvent(command.getFXTradeId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignDestinationAccountFromFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command UnAssignDestinationAccountFromFXTradeCommand" );

    	if (  destinationAccount == null )
    		throw new ProcessingException( "DestinationAccount already has nothing assigned." );  

    	apply(new UnAssignDestinationAccountFromFXTradeEvent(command.getFXTradeId()));
    }
    @CommandHandler
    public void handle(AssignTransactionToFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignTransactionToFXTradeCommand" );
    	
    	if (  transaction != null && transaction.getTransactionId() == command.getAssignment().getTransactionId() )
    		throw new ProcessingException( "Transaction already assigned with id " + command.getAssignment().getTransactionId() );  
    		
        apply(new AssignTransactionToFXTradeEvent(command.getFXTradeId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignTransactionFromFXTradeCommand command) throws Exception {
    	LOGGER.info( "Handling command UnAssignTransactionFromFXTradeCommand" );

    	if (  transaction == null )
    		throw new ProcessingException( "Transaction already has nothing assigned." );  

    	apply(new UnAssignTransactionFromFXTradeEvent(command.getFXTradeId()));
    }

    // multiple association commands

	// ----------------------------------------------
	// intrinsic event source handlers
	// ----------------------------------------------
    @EventSourcingHandler
    void on(CreateFXTradeEvent event) {	
    	LOGGER.info( "Event sourcing CreateFXTradeEvent" );
    	this.fXTradeId = event.getFXTradeId();
        this.tradeReference = event.getTradeReference();
        this.tradeDate = event.getTradeDate();
        this.settlementDate = event.getSettlementDate();
        this.amountSold = event.getAmountSold();
        this.amountBought = event.getAmountBought();
        this.rate = event.getRate();
        this.status = event.getStatus();
    }
    
    @EventSourcingHandler
    void on(UpdateFXTradeEvent event) {
    	LOGGER.info( "Event sourcing classObject.getUpdateEventAlias()}" );
        this.tradeReference = event.getTradeReference();
        this.tradeDate = event.getTradeDate();
        this.settlementDate = event.getSettlementDate();
        this.amountSold = event.getAmountSold();
        this.amountBought = event.getAmountBought();
        this.rate = event.getRate();
        this.customer = event.getCustomer();
        this.bank = event.getBank();
        this.exchangeRate = event.getExchangeRate();
        this.sourceAccount = event.getSourceAccount();
        this.destinationAccount = event.getDestinationAccount();
        this.transaction = event.getTransaction();
        this.status = event.getStatus();
    }   

	// ----------------------------------------------
	// association event source handlers
	// ----------------------------------------------
	// single associations
    @EventSourcingHandler
    void on(AssignCustomerToFXTradeEvent event ) {	
    	LOGGER.info( "Event sourcing AssignCustomerToFXTradeEvent" );
    	this.customer = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignCustomerFromFXTradeEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignCustomerFromFXTradeEvent" );
		this.customer = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignBankToFXTradeEvent event ) {	
    	LOGGER.info( "Event sourcing AssignBankToFXTradeEvent" );
    	this.bank = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignBankFromFXTradeEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignBankFromFXTradeEvent" );
		this.bank = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignExchangeRateToFXTradeEvent event ) {	
    	LOGGER.info( "Event sourcing AssignExchangeRateToFXTradeEvent" );
    	this.exchangeRate = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignExchangeRateFromFXTradeEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignExchangeRateFromFXTradeEvent" );
		this.exchangeRate = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignSourceAccountToFXTradeEvent event ) {	
    	LOGGER.info( "Event sourcing AssignSourceAccountToFXTradeEvent" );
    	this.sourceAccount = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignSourceAccountFromFXTradeEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignSourceAccountFromFXTradeEvent" );
		this.sourceAccount = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignDestinationAccountToFXTradeEvent event ) {	
    	LOGGER.info( "Event sourcing AssignDestinationAccountToFXTradeEvent" );
    	this.destinationAccount = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignDestinationAccountFromFXTradeEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignDestinationAccountFromFXTradeEvent" );
		this.destinationAccount = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignTransactionToFXTradeEvent event ) {	
    	LOGGER.info( "Event sourcing AssignTransactionToFXTradeEvent" );
    	this.transaction = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignTransactionFromFXTradeEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignTransactionFromFXTradeEvent" );
		this.transaction = null;
	}


    // ------------------------------------------
    // attributes
    // ------------------------------------------
	
    @AggregateIdentifier
    private UUID fXTradeId;
    
    private String tradeReference;
    private  Date tradeDate;
    private  Date settlementDate;
    private Money amountSold;
    private Money amountBought;
    private java.math.BigDecimal rate;
    private TradeStatus status;
    private Customer customer = null;
    private Bank bank = null;
    private ExchangeRate exchangeRate = null;
    private Account sourceAccount = null;
    private Account destinationAccount = null;
    private Transaction transaction = null;

    private static final Logger LOGGER 	= Logger.getLogger(FXTradeAggregate.class.getName());
}
