
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * Human Resources Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace hronaspdotnet.Domain;

/// <summary>
/// PayFrequency enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum PayFrequency
{
    Weekly = 1, Biweekly = 2, Semimonthly = 3, Monthly = 4, Quarterly = 5
}

/// <summary>
/// Extension of capabilities for the PayFrequency enum
/// </summary>
public static class PayFrequencyExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<PayFrequency> GetValues()
    {
        return Enum.GetValues<PayFrequency>().ToList();
    }

    public static PayFrequency GetDefaultValue()
    {
        return Enum.GetValues<PayFrequency>().First();
    }

    public static PayFrequency WhichOne(string name)
    {
        if (Enum.TryParse<PayFrequency>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



