
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * BuildingRestController as REST API
 *
 * <p>Exposes REST endpoints for the Building entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	BuildingService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateBuildingCommand</li>
 *      <li></li>UpdateBuildingCommand</li>
 *      <liDeleteBuildingCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Building")
public class BuildingRestController extends BaseSpringRestController {

	public BuildingRestController( BuildingService service ) {
		this.service = service;
	}
    /**
     * Handles create a Building.  if not key provided, calls create, otherwise calls save
     * @param		Building	building
     * @return		Building 
     */
	@PostMapping("/create")
    public Building create( @RequestBody(required=true) CreateBuildingCommand command ) {
    	Building entity = null;

		entity = service.createBuilding( command );
		LOGGER.info( "Successfully created Building with Id " + entity.getBuildingId()  );

		return entity;
    }

    /**
     * Handles updating a Building.  if no key provided, calls create, otherwise calls save
     * @param		Building building
     * @return		Building
     */
	@PutMapping("/update")
    public Building update( @RequestBody(required=true) UpdateBuildingCommand command ) {
		Building entity = null;

		entity = service.updateBuilding(command);
		LOGGER.info( "Successfully updated Building with Id " + command.getBuildingId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Building entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteBuildingCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Building with Id " + command.getBuildingId()  );
	}
	
    /**
     * Handles loading a Building using a UUID
     * @param		UUID uuid 
     * @return		Building
     */    
    @GetMapping("/get")
    public Building get( @RequestParam(required=true) UUID uuid ) {
    	Building entity = service.getBuilding( new BuildingFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded Building with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all Building business objects
     * @return		List<Building>
     */
    @GetMapping("/")
    public List<Building> getAll() {
    	List<Building> buildingList = null;

		buildingList = service.getAllBuilding();
		LOGGER.info( "successfully loaded all Buildings" );

        return buildingList;
                            
    }

	/**
	 * Handles loading all Site} business objects
	 * @return		List<Building>

    @GetMapping("/Site")
    public List<Building> Site(UUID parentId) {
		List<Building> buildingList = load(parentId).getSite;
		return buildingList;
	}
	 */
    /**
     * save Site on Building
     * @param		command AssignSiteToBuildingCommand
     */     
	@PutMapping("/assignSite")
	public void assignSite( @RequestBody AssignSiteToBuildingCommand command ) {
		service.assignSite( command );
		LOGGER.info( "Successfully assigned Site with Id " + command.getBuildingId()  );
	}

    /**
     * unassign Site on Building
     * @param		 command UnAssignSiteFromBuildingCommand
     */     
	@PutMapping("/unassignSite")
	public void unAssignSite( @RequestBody(required=true)  UnAssignSiteFromBuildingCommand command ) {
		service.unAssignSite( command );
		LOGGER.info( "Successfully unassigned Site with Id " + command.getBuildingId()  );
	}
	

	/**
	 * Handles loading all Floors} business objects
	 * @return		List<Building>

    @GetMapping("/Floors")
    public List<Building> Floors(UUID parentId) {
		List<Building> buildingList = load(parentId).getFloors;
		return buildingList;
	}

    /**
     * save Floors on Building
     * @param		command AssignFloorsToBuildingCommand
     */     
	@PutMapping("/addToFloors")
	public void addToFloors( @RequestBody(required=true) AssignFloorsToBuildingCommand command ) {
		service.addToFloors( command );
		LOGGER.info( "Successfully added Floors with Id " + command.getBuildingId()  );
	}

    /**
     * remove Floors on Building
     * @param		command RemoveFloorsFromBuildingCommand
     */     	
	@PutMapping("/removeFromFloors")
	public void removeFromFloors( 	@RequestBody(required=true) RemoveFloorsFromBuildingCommand command )
	{		
		service.removeFromFloors( command );
		LOGGER.info( "Successfully removed Floors with Id " + command.getBuildingId()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Building building = null;
	protected BuildingService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(BuildingRestController.class.getName());
    
}
