/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * MessagingEndpointRestController as REST API
 *
 * <p>Exposes REST endpoints for the MessagingEndpoint entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	MessagingEndpointBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateMessagingEndpointCommand</li>
 *      <li></li>UpdateMessagingEndpointCommand</li>
 *      <liDeleteMessagingEndpointCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/MessagingEndpoint")
public class MessagingEndpointRestController extends BaseSpringRestController {

	public MessagingEndpointRestController( MessagingEndpointService service ) {
		this.service = service;
	}
	
    /**
     * Handles create a MessagingEndpoint.  if not key provided, calls create, otherwise calls save
     * @param		MessagingEndpoint	messagingEndpoint
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateMessagingEndpointCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = service.createMessagingEndpoint( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a MessagingEndpoint.  if no key provided, calls create, otherwise calls save
     * @param		MessagingEndpoint messagingEndpoint
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateMessagingEndpointCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateMessagingEndpointCommand
			// -----------------------------------------------
			completableFuture = service.updateMessagingEndpoint(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "MessagingEndpointController:update() - successfully update MessagingEndpoint - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a MessagingEndpoint entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteMessagingEndpointCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	MessagingEndpointService delegate = service;

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted MessagingEndpoint with key " + command.getMessagingEndpointId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a MessagingEndpoint using a UUID
     * @param		UUID uuid 
     * @return		MessagingEndpoint
     */    
    @GetMapping("/load")
    public MessagingEndpoint load( @RequestParam(required=true) UUID uuid ) {    	
    	MessagingEndpoint entity = null;

    	try {  
    		entity = service.getMessagingEndpoint( new MessagingEndpointFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load MessagingEndpoint using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all MessagingEndpoint business objects
     * @return		Set<MessagingEndpoint>
     */
    @GetMapping("/")
    public List<MessagingEndpoint> loadAll() {                
    	List<MessagingEndpoint> messagingEndpointList = null;
        
    	try {
            // load the MessagingEndpoint
            messagingEndpointList = service.getAllMessagingEndpoint();
            
            if ( messagingEndpointList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all MessagingEndpoints" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all MessagingEndpoints ", exc );
        	return null;
        }

        return messagingEndpointList;
                            
    }

    /**
     * save Tenant on MessagingEndpoint
     * @param		command AssignTenantToMessagingEndpointCommand
     */     
	@PutMapping("/assignTenant")
	public void assignTenant( @RequestBody AssignTenantToMessagingEndpointCommand command ) {
		try {
			service.assignTenant( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Tenant", exc );
        }
	}

    /**
     * unassign Tenant on MessagingEndpoint
     * @param		 command UnAssignTenantFromMessagingEndpointCommand
     */     
	@PutMapping("/unAssignTenant")
	public void unAssignTenant( @RequestBody(required=true)  UnAssignTenantFromMessagingEndpointCommand command ) {
		try {
			service.unAssignTenant( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Tenant", exc );
		}
	}
	

    /**
     * save Streams on MessagingEndpoint
     * @param		command AssignStreamsToMessagingEndpointCommand
     */     
	@PutMapping("/addToStreams")
	public void addToStreams( @RequestBody(required=true) AssignStreamsToMessagingEndpointCommand command ) {
		try {
			service.addToStreams( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Streams", exc );
		}
	}

    /**
     * remove Streams on MessagingEndpoint
     * @param		command RemoveStreamsFromMessagingEndpointCommand
     */     	
	@PutMapping("/removeFromStreams")
	public void removeFromStreams( 	@RequestBody(required=true) RemoveStreamsFromMessagingEndpointCommand command )
	{		
		try {
			service.removeFromStreams( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Streams", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected MessagingEndpoint messagingEndpoint = null;
	protected MessagingEndpointService service = null;
	private static final Logger LOGGER = Logger.getLogger(MessagingEndpointRestController.class.getName());
    
}
