
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * ProvisioningRecordRestController as REST API
 *
 * <p>Exposes REST endpoints for the ProvisioningRecord entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	ProvisioningRecordService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateProvisioningRecordCommand</li>
 *      <li></li>UpdateProvisioningRecordCommand</li>
 *      <liDeleteProvisioningRecordCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/ProvisioningRecord")
public class ProvisioningRecordRestController extends BaseSpringRestController {

	public ProvisioningRecordRestController( ProvisioningRecordService service ) {
		this.service = service;
	}
    /**
     * Handles create a ProvisioningRecord.  if not key provided, calls create, otherwise calls save
     * @param		ProvisioningRecord	provisioningRecord
     * @return		ProvisioningRecord 
     */
	@PostMapping("/create")
    public ProvisioningRecord create( @RequestBody(required=true) CreateProvisioningRecordCommand command ) {
    	ProvisioningRecord entity = null;

		entity = service.createProvisioningRecord( command );
		LOGGER.info( "Successfully created ProvisioningRecord with Id " + entity.getProvisioningRecordId()  );

		return entity;
    }

    /**
     * Handles updating a ProvisioningRecord.  if no key provided, calls create, otherwise calls save
     * @param		ProvisioningRecord provisioningRecord
     * @return		ProvisioningRecord
     */
	@PutMapping("/update")
    public ProvisioningRecord update( @RequestBody(required=true) UpdateProvisioningRecordCommand command ) {
		ProvisioningRecord entity = null;

		entity = service.updateProvisioningRecord(command);
		LOGGER.info( "Successfully updated ProvisioningRecord with Id " + command.getProvisioningRecordId()  );

		return entity;
	}
 
    /**
     * Handles deleting a ProvisioningRecord entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteProvisioningRecordCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted ProvisioningRecord with Id " + command.getProvisioningRecordId()  );
	}
	
    /**
     * Handles loading a ProvisioningRecord using a UUID
     * @param		UUID uuid 
     * @return		ProvisioningRecord
     */    
    @GetMapping("/get")
    public ProvisioningRecord get( @RequestParam(required=true) UUID uuid ) {
    	ProvisioningRecord entity = service.getProvisioningRecord( new ProvisioningRecordFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded ProvisioningRecord with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all ProvisioningRecord business objects
     * @return		List<ProvisioningRecord>
     */
    @GetMapping("/")
    public List<ProvisioningRecord> getAll() {
    	List<ProvisioningRecord> provisioningRecordList = null;

		provisioningRecordList = service.getAllProvisioningRecord();
		LOGGER.info( "successfully loaded all ProvisioningRecords" );

        return provisioningRecordList;
                            
    }

	/**
	 * Handles loading all Device} business objects
	 * @return		List<ProvisioningRecord>

    @GetMapping("/Device")
    public List<ProvisioningRecord> Device(UUID parentId) {
		List<ProvisioningRecord> provisioningRecordList = load(parentId).getDevice;
		return provisioningRecordList;
	}
	 */
    /**
     * save Device on ProvisioningRecord
     * @param		command AssignDeviceToProvisioningRecordCommand
     */     
	@PutMapping("/assignDevice")
	public void assignDevice( @RequestBody AssignDeviceToProvisioningRecordCommand command ) {
		service.assignDevice( command );
		LOGGER.info( "Successfully assigned Device with Id " + command.getProvisioningRecordId()  );
	}

    /**
     * unassign Device on ProvisioningRecord
     * @param		 command UnAssignDeviceFromProvisioningRecordCommand
     */     
	@PutMapping("/unassignDevice")
	public void unAssignDevice( @RequestBody(required=true)  UnAssignDeviceFromProvisioningRecordCommand command ) {
		service.unAssignDevice( command );
		LOGGER.info( "Successfully unassigned Device with Id " + command.getProvisioningRecordId()  );
	}
	
	/**
	 * Handles loading all Certificate} business objects
	 * @return		List<ProvisioningRecord>

    @GetMapping("/Certificate")
    public List<ProvisioningRecord> Certificate(UUID parentId) {
		List<ProvisioningRecord> provisioningRecordList = load(parentId).getCertificate;
		return provisioningRecordList;
	}
	 */
    /**
     * save Certificate on ProvisioningRecord
     * @param		command AssignCertificateToProvisioningRecordCommand
     */     
	@PutMapping("/assignCertificate")
	public void assignCertificate( @RequestBody AssignCertificateToProvisioningRecordCommand command ) {
		service.assignCertificate( command );
		LOGGER.info( "Successfully assigned Certificate with Id " + command.getProvisioningRecordId()  );
	}

    /**
     * unassign Certificate on ProvisioningRecord
     * @param		 command UnAssignCertificateFromProvisioningRecordCommand
     */     
	@PutMapping("/unassignCertificate")
	public void unAssignCertificate( @RequestBody(required=true)  UnAssignCertificateFromProvisioningRecordCommand command ) {
		service.unAssignCertificate( command );
		LOGGER.info( "Successfully unassigned Certificate with Id " + command.getProvisioningRecordId()  );
	}
	
	/**
	 * Handles loading all Tenant} business objects
	 * @return		List<ProvisioningRecord>

    @GetMapping("/Tenant")
    public List<ProvisioningRecord> Tenant(UUID parentId) {
		List<ProvisioningRecord> provisioningRecordList = load(parentId).getTenant;
		return provisioningRecordList;
	}
	 */
    /**
     * save Tenant on ProvisioningRecord
     * @param		command AssignTenantToProvisioningRecordCommand
     */     
	@PutMapping("/assignTenant")
	public void assignTenant( @RequestBody AssignTenantToProvisioningRecordCommand command ) {
		service.assignTenant( command );
		LOGGER.info( "Successfully assigned Tenant with Id " + command.getProvisioningRecordId()  );
	}

    /**
     * unassign Tenant on ProvisioningRecord
     * @param		 command UnAssignTenantFromProvisioningRecordCommand
     */     
	@PutMapping("/unassignTenant")
	public void unAssignTenant( @RequestBody(required=true)  UnAssignTenantFromProvisioningRecordCommand command ) {
		service.unAssignTenant( command );
		LOGGER.info( "Successfully unassigned Tenant with Id " + command.getProvisioningRecordId()  );
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected ProvisioningRecord provisioningRecord = null;
	protected ProvisioningRecordService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(ProvisioningRecordRestController.class.getName());
    
}
