
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Insurance Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * ServiceProviderRestController as REST API
 *
 * <p>Exposes REST endpoints for the ServiceProvider entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/12/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Insurance Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core insurance product, underwriting, policy, billing, claims, and reinsurance capabilities.</td></tr>
 *          <tr><td>industry</td><td>Insurance</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	ServiceProviderService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateServiceProviderCommand</li>
 *      <li></li>UpdateServiceProviderCommand</li>
 *      <liDeleteServiceProviderCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/ServiceProvider")
public class ServiceProviderRestController extends BaseSpringRestController {

	public ServiceProviderRestController( ServiceProviderService service ) {
		this.service = service;
	}
    /**
     * Handles create a ServiceProvider.  if not key provided, calls create, otherwise calls save
     * @param		ServiceProvider	serviceProvider
     * @return		ServiceProvider 
     */
	@PostMapping("/create")
    public ServiceProvider create( @RequestBody(required=true) CreateServiceProviderCommand command ) {
    	ServiceProvider entity = null;

		entity = service.createServiceProvider( command );
		LOGGER.info( "Successfully created ServiceProvider with Id " + entity.getServiceProviderId()  );

		return entity;
    }

    /**
     * Handles updating a ServiceProvider.  if no key provided, calls create, otherwise calls save
     * @param		ServiceProvider serviceProvider
     * @return		ServiceProvider
     */
	@PutMapping("/update")
    public ServiceProvider update( @RequestBody(required=true) UpdateServiceProviderCommand command ) {
		ServiceProvider entity = null;

		entity = service.updateServiceProvider(command);
		LOGGER.info( "Successfully updated ServiceProvider with Id " + command.getServiceProviderId()  );

		return entity;
	}
 
    /**
     * Handles deleting a ServiceProvider entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteServiceProviderCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted ServiceProvider with Id " + command.getServiceProviderId()  );
	}
	
    /**
     * Handles loading a ServiceProvider using a UUID
     * @param		UUID uuid 
     * @return		ServiceProvider
     */    
    @GetMapping("/get")
    public ServiceProvider get( @RequestParam(required=true) UUID uuid ) {
    	ServiceProvider entity = service.getServiceProvider( new ServiceProviderFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded ServiceProvider with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all ServiceProvider business objects
     * @return		List<ServiceProvider>
     */
    @GetMapping("/")
    public List<ServiceProvider> getAll() {
    	List<ServiceProvider> serviceProviderList = null;

		serviceProviderList = service.getAllServiceProvider();
		LOGGER.info( "successfully loaded all ServiceProviders" );

        return serviceProviderList;
                            
    }


	/**
	 * Handles loading all Claims} business objects
	 * @return		List<ServiceProvider>

    @GetMapping("/Claims")
    public List<ServiceProvider> Claims(UUID parentId) {
		List<ServiceProvider> serviceProviderList = load(parentId).getClaims;
		return serviceProviderList;
	}

    /**
     * save Claims on ServiceProvider
     * @param		command AssignClaimsToServiceProviderCommand
     */     
	@PutMapping("/addToClaims")
	public void addToClaims( @RequestBody(required=true) AssignClaimsToServiceProviderCommand command ) {
		service.addToClaims( command );
		LOGGER.info( "Successfully added Claims with Id " + command.getServiceProviderId()  );
	}

    /**
     * remove Claims on ServiceProvider
     * @param		command RemoveClaimsFromServiceProviderCommand
     */     	
	@PutMapping("/removeFromClaims")
	public void removeFromClaims( 	@RequestBody(required=true) RemoveClaimsFromServiceProviderCommand command )
	{		
		service.removeFromClaims( command );
		LOGGER.info( "Successfully removed Claims with Id " + command.getServiceProviderId()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected ServiceProvider serviceProvider = null;
	protected ServiceProviderService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(ServiceProviderRestController.class.getName());
    
}
