/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 2.5
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.globalbank.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.globalbank.api.*;
import com.globalbank.service.*;
import com.globalbank.entity.*;
import com.globalbank.exception.*;

/**
 * BankRestController as REST API
 *
 * <p>Exposes REST endpoints for the Bank entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 2.5</td></tr>
 *          <tr><td>published</td><td>09/12/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	BankService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateBankCommand</li>
 *      <li></li>UpdateBankCommand</li>
 *      <liDeleteBankCommand</li>
 *      </ul>
 *
 * <p>@author your_name_here</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Bank")
public class BankRestController extends BaseSpringRestController {

	public BankRestController( BankService service ) {
		this.service = service;
	}
    /**
     * Handles create a Bank.  if not key provided, calls create, otherwise calls save
     * @param		Bank	bank
     * @return		Bank 
     */
	@PostMapping("/create")
    public Bank create( @RequestBody(required=true) CreateBankCommand command ) {
    	Bank entity = null;

		entity = service.createBank( command );
		LOGGER.info( "Successfully created Bank with Id " + entity.getBankId()  );

		return entity;
    }

    /**
     * Handles updating a Bank.  if no key provided, calls create, otherwise calls save
     * @param		Bank bank
     * @return		Bank
     */
	@PutMapping("/update")
    public Bank update( @RequestBody(required=true) UpdateBankCommand command ) {
		Bank entity = null;

		entity = service.updateBank(command);
		LOGGER.info( "Successfully updated Bank with Id " + command.getBankId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Bank entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteBankCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Bank with Id " + command.getBankId()  );
	}
	
    /**
     * Handles loading a Bank using a UUID
     * @param		UUID uuid 
     * @return		Bank
     */    
    @GetMapping("/load")
    public Bank load( @RequestParam(required=true) UUID uuid ) {
    	Bank entity = service.getBank( new BankFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded Bank with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all Bank business objects
     * @return		List<Bank>
     */
    @GetMapping("/")
    public List<Bank> loadAll() {                
    	List<Bank> bankList = null;

		bankList = service.getAllBank();
		LOGGER.info( "successfully loaded all Banks" );

        return bankList;
                            
    }


	/**
	 * Handles loading all Branches} business objects
	 * @return		List<Bank>

    @GetMapping("/Branches")
    public List<Bank> Branches(UUID parentId) {
		List<Bank> bankList = load(parentId).getBranches;
		return bankList;
	}

    /**
     * save Branches on Bank
     * @param		command AssignBranchesToBankCommand
     */     
	@PutMapping("/addToBranches")
	public void addToBranches( @RequestBody(required=true) AssignBranchesToBankCommand command ) {
		service.addToBranches( command );
		LOGGER.info( "Successfully added Branches with Id " + command.getBankId()  );
	}

    /**
     * remove Branches on Bank
     * @param		command RemoveBranchesFromBankCommand
     */     	
	@PutMapping("/removeFromBranches")
	public void removeFromBranches( 	@RequestBody(required=true) RemoveBranchesFromBankCommand command )
	{		
		service.removeFromBranches( command );
		LOGGER.info( "Successfully removed Branches with Id " + command.getBankId()  );
	}

	/**
	 * Handles loading all Products} business objects
	 * @return		List<Bank>

    @GetMapping("/Products")
    public List<Bank> Products(UUID parentId) {
		List<Bank> bankList = load(parentId).getProducts;
		return bankList;
	}

    /**
     * save Products on Bank
     * @param		command AssignProductsToBankCommand
     */     
	@PutMapping("/addToProducts")
	public void addToProducts( @RequestBody(required=true) AssignProductsToBankCommand command ) {
		service.addToProducts( command );
		LOGGER.info( "Successfully added Products with Id " + command.getBankId()  );
	}

    /**
     * remove Products on Bank
     * @param		command RemoveProductsFromBankCommand
     */     	
	@PutMapping("/removeFromProducts")
	public void removeFromProducts( 	@RequestBody(required=true) RemoveProductsFromBankCommand command )
	{		
		service.removeFromProducts( command );
		LOGGER.info( "Successfully removed Products with Id " + command.getBankId()  );
	}

	/**
	 * Handles loading all Customers} business objects
	 * @return		List<Bank>

    @GetMapping("/Customers")
    public List<Bank> Customers(UUID parentId) {
		List<Bank> bankList = load(parentId).getCustomers;
		return bankList;
	}

    /**
     * save Customers on Bank
     * @param		command AssignCustomersToBankCommand
     */     
	@PutMapping("/addToCustomers")
	public void addToCustomers( @RequestBody(required=true) AssignCustomersToBankCommand command ) {
		service.addToCustomers( command );
		LOGGER.info( "Successfully added Customers with Id " + command.getBankId()  );
	}

    /**
     * remove Customers on Bank
     * @param		command RemoveCustomersFromBankCommand
     */     	
	@PutMapping("/removeFromCustomers")
	public void removeFromCustomers( 	@RequestBody(required=true) RemoveCustomersFromBankCommand command )
	{		
		service.removeFromCustomers( command );
		LOGGER.info( "Successfully removed Customers with Id " + command.getBankId()  );
	}

	/**
	 * Handles loading all Accounts} business objects
	 * @return		List<Bank>

    @GetMapping("/Accounts")
    public List<Bank> Accounts(UUID parentId) {
		List<Bank> bankList = load(parentId).getAccounts;
		return bankList;
	}

    /**
     * save Accounts on Bank
     * @param		command AssignAccountsToBankCommand
     */     
	@PutMapping("/addToAccounts")
	public void addToAccounts( @RequestBody(required=true) AssignAccountsToBankCommand command ) {
		service.addToAccounts( command );
		LOGGER.info( "Successfully added Accounts with Id " + command.getBankId()  );
	}

    /**
     * remove Accounts on Bank
     * @param		command RemoveAccountsFromBankCommand
     */     	
	@PutMapping("/removeFromAccounts")
	public void removeFromAccounts( 	@RequestBody(required=true) RemoveAccountsFromBankCommand command )
	{		
		service.removeFromAccounts( command );
		LOGGER.info( "Successfully removed Accounts with Id " + command.getBankId()  );
	}

	/**
	 * Handles loading all PaymentCards} business objects
	 * @return		List<Bank>

    @GetMapping("/PaymentCards")
    public List<Bank> PaymentCards(UUID parentId) {
		List<Bank> bankList = load(parentId).getPaymentCards;
		return bankList;
	}

    /**
     * save PaymentCards on Bank
     * @param		command AssignPaymentCardsToBankCommand
     */     
	@PutMapping("/addToPaymentCards")
	public void addToPaymentCards( @RequestBody(required=true) AssignPaymentCardsToBankCommand command ) {
		service.addToPaymentCards( command );
		LOGGER.info( "Successfully added PaymentCards with Id " + command.getBankId()  );
	}

    /**
     * remove PaymentCards on Bank
     * @param		command RemovePaymentCardsFromBankCommand
     */     	
	@PutMapping("/removeFromPaymentCards")
	public void removeFromPaymentCards( 	@RequestBody(required=true) RemovePaymentCardsFromBankCommand command )
	{		
		service.removeFromPaymentCards( command );
		LOGGER.info( "Successfully removed PaymentCards with Id " + command.getBankId()  );
	}

	/**
	 * Handles loading all LoanAccounts} business objects
	 * @return		List<Bank>

    @GetMapping("/LoanAccounts")
    public List<Bank> LoanAccounts(UUID parentId) {
		List<Bank> bankList = load(parentId).getLoanAccounts;
		return bankList;
	}

    /**
     * save LoanAccounts on Bank
     * @param		command AssignLoanAccountsToBankCommand
     */     
	@PutMapping("/addToLoanAccounts")
	public void addToLoanAccounts( @RequestBody(required=true) AssignLoanAccountsToBankCommand command ) {
		service.addToLoanAccounts( command );
		LOGGER.info( "Successfully added LoanAccounts with Id " + command.getBankId()  );
	}

    /**
     * remove LoanAccounts on Bank
     * @param		command RemoveLoanAccountsFromBankCommand
     */     	
	@PutMapping("/removeFromLoanAccounts")
	public void removeFromLoanAccounts( 	@RequestBody(required=true) RemoveLoanAccountsFromBankCommand command )
	{		
		service.removeFromLoanAccounts( command );
		LOGGER.info( "Successfully removed LoanAccounts with Id " + command.getBankId()  );
	}

	/**
	 * Handles loading all ExchangeRates} business objects
	 * @return		List<Bank>

    @GetMapping("/ExchangeRates")
    public List<Bank> ExchangeRates(UUID parentId) {
		List<Bank> bankList = load(parentId).getExchangeRates;
		return bankList;
	}

    /**
     * save ExchangeRates on Bank
     * @param		command AssignExchangeRatesToBankCommand
     */     
	@PutMapping("/addToExchangeRates")
	public void addToExchangeRates( @RequestBody(required=true) AssignExchangeRatesToBankCommand command ) {
		service.addToExchangeRates( command );
		LOGGER.info( "Successfully added ExchangeRates with Id " + command.getBankId()  );
	}

    /**
     * remove ExchangeRates on Bank
     * @param		command RemoveExchangeRatesFromBankCommand
     */     	
	@PutMapping("/removeFromExchangeRates")
	public void removeFromExchangeRates( 	@RequestBody(required=true) RemoveExchangeRatesFromBankCommand command )
	{		
		service.removeFromExchangeRates( command );
		LOGGER.info( "Successfully removed ExchangeRates with Id " + command.getBankId()  );
	}

	/**
	 * Handles loading all Consents} business objects
	 * @return		List<Bank>

    @GetMapping("/Consents")
    public List<Bank> Consents(UUID parentId) {
		List<Bank> bankList = load(parentId).getConsents;
		return bankList;
	}

    /**
     * save Consents on Bank
     * @param		command AssignConsentsToBankCommand
     */     
	@PutMapping("/addToConsents")
	public void addToConsents( @RequestBody(required=true) AssignConsentsToBankCommand command ) {
		service.addToConsents( command );
		LOGGER.info( "Successfully added Consents with Id " + command.getBankId()  );
	}

    /**
     * remove Consents on Bank
     * @param		command RemoveConsentsFromBankCommand
     */     	
	@PutMapping("/removeFromConsents")
	public void removeFromConsents( 	@RequestBody(required=true) RemoveConsentsFromBankCommand command )
	{		
		service.removeFromConsents( command );
		LOGGER.info( "Successfully removed Consents with Id " + command.getBankId()  );
	}

	/**
	 * Handles loading all ThirdPartyProviders} business objects
	 * @return		List<Bank>

    @GetMapping("/ThirdPartyProviders")
    public List<Bank> ThirdPartyProviders(UUID parentId) {
		List<Bank> bankList = load(parentId).getThirdPartyProviders;
		return bankList;
	}

    /**
     * save ThirdPartyProviders on Bank
     * @param		command AssignThirdPartyProvidersToBankCommand
     */     
	@PutMapping("/addToThirdPartyProviders")
	public void addToThirdPartyProviders( @RequestBody(required=true) AssignThirdPartyProvidersToBankCommand command ) {
		service.addToThirdPartyProviders( command );
		LOGGER.info( "Successfully added ThirdPartyProviders with Id " + command.getBankId()  );
	}

    /**
     * remove ThirdPartyProviders on Bank
     * @param		command RemoveThirdPartyProvidersFromBankCommand
     */     	
	@PutMapping("/removeFromThirdPartyProviders")
	public void removeFromThirdPartyProviders( 	@RequestBody(required=true) RemoveThirdPartyProvidersFromBankCommand command )
	{		
		service.removeFromThirdPartyProviders( command );
		LOGGER.info( "Successfully removed ThirdPartyProviders with Id " + command.getBankId()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Bank bank = null;
	protected BankService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(BankRestController.class.getName());
    
}
