/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.globalbank.controller.command;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.globalbank.api.*;
import com.globalbank.service.*;
import com.globalbank.entity.*;
import com.globalbank.exception.*;
import com.globalbank.projector.*;

import com.globalbank.controller.*;

/**
 * <h2>ExchangeRateCommandRestController as REST API</h2>
 * <p>
 * Implements Spring Controller command CQRS processing for entity ExchangeRate.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/12/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	ExchangeRateService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateExchangeRateCommand</li>
 *      <li>UpdateExchangeRateCommand</li>
 *      <liDeleteExchangeRateCommand</li>
 *      </ul>
 *
 * <p>@author your_name_here</p>
 */

@CrossOrigin
@RestController
@RequestMapping("/ExchangeRateCommand")
public class ExchangeRateCommandRestController extends BaseSpringRestController {

	public ExchangeRateCommandRestController( ExchangeRateService service ) {
		this.service = service;
	}
	
    /**
     * Handles create a ExchangeRate.
     * @param		ExchangeRate	exchangeRate
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateExchangeRateCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {
			completableFuture = service.createExchangeRate( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a ExchangeRate.  if no key provided, calls create, otherwise calls save
     * @param		ExchangeRate exchangeRate
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateExchangeRateCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateExchangeRateCommand
			// -----------------------------------------------
			completableFuture = service.updateExchangeRate(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "ExchangeRateController:update() - successfully update ExchangeRate - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a ExchangeRate entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestParam(required=true) UUID exchangeRateId  ) {
    	CompletableFuture<Void> completableFuture = null;
		DeleteExchangeRateCommand command = new DeleteExchangeRateCommand( exchangeRateId );

    	try {
        	completableFuture = service.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted ExchangeRate with key " + command.getExchangeRateId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	

    /**
     * save Bank on ExchangeRate
     * @param		command AssignBankToExchangeRateCommand
     */     
	@PutMapping("/assignBank")
	public void assignBank( @RequestBody AssignBankToExchangeRateCommand command ) {
		try {
			service.assignBank( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Bank", exc );
        }
	}

    /**
     * unassign Bank on ExchangeRate
     * @param		 command UnAssignBankFromExchangeRateCommand
     */     
	@PutMapping("/unAssignBank")
	public void unAssignBank( @RequestBody(required=true)  UnAssignBankFromExchangeRateCommand command ) {
		try {
			service.unAssignBank( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Bank", exc );
		}
	}
	

    /**
     * save FxTrades on ExchangeRate
     * @param		command AssignFxTradesToExchangeRateCommand
     */     
	@PutMapping("/addToFxTrades")
	public void addToFxTrades( @RequestBody(required=true) AssignFxTradesToExchangeRateCommand command ) {
		try {
			service.addToFxTrades( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set FxTrades", exc );
		}
	}

    /**
     * remove FxTrades on ExchangeRate
     * @param		command RemoveFxTradesFromExchangeRateCommand
     */     	
	@PutMapping("/removeFromFxTrades")
	public void removeFromFxTrades( 	@RequestBody(required=true) RemoveFxTradesFromExchangeRateCommand command )
	{		
		try {
			service.removeFromFxTrades( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set FxTrades", exc );
		}
	}


//************************************************************************    
// Attributes
//************************************************************************
    protected ExchangeRate exchangeRate = null;
	protected ExchangeRateService service = null;
    private static final Logger LOGGER = Logger.getLogger(ExchangeRateCommandRestController.class.getName());
    
}
