/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.globalbank.controller.command;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.globalbank.api.*;
import com.globalbank.service.*;
import com.globalbank.entity.*;
import com.globalbank.exception.*;
import com.globalbank.projector.*;

import com.globalbank.controller.*;

/**
 * <h2>LoanAccountCommandRestController as REST API</h2>
 * <p>
 * Implements Spring Controller command CQRS processing for entity LoanAccount.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/12/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	LoanAccountService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateLoanAccountCommand</li>
 *      <li>UpdateLoanAccountCommand</li>
 *      <liDeleteLoanAccountCommand</li>
 *      </ul>
 *
 * <p>@author your_name_here</p>
 */

@CrossOrigin
@RestController
@RequestMapping("/LoanAccountCommand")
public class LoanAccountCommandRestController extends BaseSpringRestController {

	public LoanAccountCommandRestController( LoanAccountService service ) {
		this.service = service;
	}
	
    /**
     * Handles create a LoanAccount.
     * @param		LoanAccount	loanAccount
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateLoanAccountCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {
			completableFuture = service.createLoanAccount( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a LoanAccount.  if no key provided, calls create, otherwise calls save
     * @param		LoanAccount loanAccount
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateLoanAccountCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateLoanAccountCommand
			// -----------------------------------------------
			completableFuture = service.updateLoanAccount(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "LoanAccountController:update() - successfully update LoanAccount - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a LoanAccount entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestParam(required=true) UUID loanAccountId  ) {
    	CompletableFuture<Void> completableFuture = null;
		DeleteLoanAccountCommand command = new DeleteLoanAccountCommand( loanAccountId );

    	try {
        	completableFuture = service.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted LoanAccount with key " + command.getLoanAccountId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	

    /**
     * save Bank on LoanAccount
     * @param		command AssignBankToLoanAccountCommand
     */     
	@PutMapping("/assignBank")
	public void assignBank( @RequestBody AssignBankToLoanAccountCommand command ) {
		try {
			service.assignBank( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Bank", exc );
        }
	}

    /**
     * unassign Bank on LoanAccount
     * @param		 command UnAssignBankFromLoanAccountCommand
     */     
	@PutMapping("/unAssignBank")
	public void unAssignBank( @RequestBody(required=true)  UnAssignBankFromLoanAccountCommand command ) {
		try {
			service.unAssignBank( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Bank", exc );
		}
	}
	
    /**
     * save Branch on LoanAccount
     * @param		command AssignBranchToLoanAccountCommand
     */     
	@PutMapping("/assignBranch")
	public void assignBranch( @RequestBody AssignBranchToLoanAccountCommand command ) {
		try {
			service.assignBranch( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Branch", exc );
        }
	}

    /**
     * unassign Branch on LoanAccount
     * @param		 command UnAssignBranchFromLoanAccountCommand
     */     
	@PutMapping("/unAssignBranch")
	public void unAssignBranch( @RequestBody(required=true)  UnAssignBranchFromLoanAccountCommand command ) {
		try {
			service.unAssignBranch( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Branch", exc );
		}
	}
	
    /**
     * save Product on LoanAccount
     * @param		command AssignProductToLoanAccountCommand
     */     
	@PutMapping("/assignProduct")
	public void assignProduct( @RequestBody AssignProductToLoanAccountCommand command ) {
		try {
			service.assignProduct( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Product", exc );
        }
	}

    /**
     * unassign Product on LoanAccount
     * @param		 command UnAssignProductFromLoanAccountCommand
     */     
	@PutMapping("/unAssignProduct")
	public void unAssignProduct( @RequestBody(required=true)  UnAssignProductFromLoanAccountCommand command ) {
		try {
			service.unAssignProduct( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Product", exc );
		}
	}
	

    /**
     * save Borrowers on LoanAccount
     * @param		command AssignBorrowersToLoanAccountCommand
     */     
	@PutMapping("/addToBorrowers")
	public void addToBorrowers( @RequestBody(required=true) AssignBorrowersToLoanAccountCommand command ) {
		try {
			service.addToBorrowers( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Borrowers", exc );
		}
	}

    /**
     * remove Borrowers on LoanAccount
     * @param		command RemoveBorrowersFromLoanAccountCommand
     */     	
	@PutMapping("/removeFromBorrowers")
	public void removeFromBorrowers( 	@RequestBody(required=true) RemoveBorrowersFromLoanAccountCommand command )
	{		
		try {
			service.removeFromBorrowers( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Borrowers", exc );
		}
	}

    /**
     * save RepaymentSchedule on LoanAccount
     * @param		command AssignRepaymentScheduleToLoanAccountCommand
     */     
	@PutMapping("/addToRepaymentSchedule")
	public void addToRepaymentSchedule( @RequestBody(required=true) AssignRepaymentScheduleToLoanAccountCommand command ) {
		try {
			service.addToRepaymentSchedule( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set RepaymentSchedule", exc );
		}
	}

    /**
     * remove RepaymentSchedule on LoanAccount
     * @param		command RemoveRepaymentScheduleFromLoanAccountCommand
     */     	
	@PutMapping("/removeFromRepaymentSchedule")
	public void removeFromRepaymentSchedule( 	@RequestBody(required=true) RemoveRepaymentScheduleFromLoanAccountCommand command )
	{		
		try {
			service.removeFromRepaymentSchedule( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set RepaymentSchedule", exc );
		}
	}

    /**
     * save Payments on LoanAccount
     * @param		command AssignPaymentsToLoanAccountCommand
     */     
	@PutMapping("/addToPayments")
	public void addToPayments( @RequestBody(required=true) AssignPaymentsToLoanAccountCommand command ) {
		try {
			service.addToPayments( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Payments", exc );
		}
	}

    /**
     * remove Payments on LoanAccount
     * @param		command RemovePaymentsFromLoanAccountCommand
     */     	
	@PutMapping("/removeFromPayments")
	public void removeFromPayments( 	@RequestBody(required=true) RemovePaymentsFromLoanAccountCommand command )
	{		
		try {
			service.removeFromPayments( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Payments", exc );
		}
	}

    /**
     * save Collateral on LoanAccount
     * @param		command AssignCollateralToLoanAccountCommand
     */     
	@PutMapping("/addToCollateral")
	public void addToCollateral( @RequestBody(required=true) AssignCollateralToLoanAccountCommand command ) {
		try {
			service.addToCollateral( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Collateral", exc );
		}
	}

    /**
     * remove Collateral on LoanAccount
     * @param		command RemoveCollateralFromLoanAccountCommand
     */     	
	@PutMapping("/removeFromCollateral")
	public void removeFromCollateral( 	@RequestBody(required=true) RemoveCollateralFromLoanAccountCommand command )
	{		
		try {
			service.removeFromCollateral( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Collateral", exc );
		}
	}

    /**
     * save FeeCharges on LoanAccount
     * @param		command AssignFeeChargesToLoanAccountCommand
     */     
	@PutMapping("/addToFeeCharges")
	public void addToFeeCharges( @RequestBody(required=true) AssignFeeChargesToLoanAccountCommand command ) {
		try {
			service.addToFeeCharges( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set FeeCharges", exc );
		}
	}

    /**
     * remove FeeCharges on LoanAccount
     * @param		command RemoveFeeChargesFromLoanAccountCommand
     */     	
	@PutMapping("/removeFromFeeCharges")
	public void removeFromFeeCharges( 	@RequestBody(required=true) RemoveFeeChargesFromLoanAccountCommand command )
	{		
		try {
			service.removeFromFeeCharges( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set FeeCharges", exc );
		}
	}


//************************************************************************    
// Attributes
//************************************************************************
    protected LoanAccount loanAccount = null;
	protected LoanAccountService service = null;
    private static final Logger LOGGER = Logger.getLogger(LoanAccountCommandRestController.class.getName());
    
}
