
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller.query;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.projector.*;

import com.harbormaster.controller.*;
/**
 * <h2>DeviceGroupQueryRestController as REST API</h2>
 * <p>
 * Implements Spring Controller query CQRS processing for entity DeviceGroup.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	DeviceGroupService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateDeviceGroupCommand</li>
 *      <li></li>UpdateDeviceGroupCommand</li>
 *      <liDeleteDeviceGroupCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@CrossOrigin
@RestController
@RequestMapping("/DeviceGroupQuery")
public class DeviceGroupQueryRestController extends BaseSpringRestController {
	
	public DeviceGroupQueryRestController( DeviceGroupService service ) {
        this.service = service;
    }
    
    /**
     * Handles loading a DeviceGroup using a UUID
     * @param		UUID deviceGroupId
     * @return		DeviceGroup
     */    
    @GetMapping("/load")
    public DeviceGroup load( @RequestParam(required=true) UUID deviceGroupId ) {
    	DeviceGroup entity = null;

    	try {  
    		entity = service.getDeviceGroup( new DeviceGroupFetchOneSummary( deviceGroupId ) );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load DeviceGroup using Id " + deviceGroupId );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all DeviceGroup business objects
     * @return		Set<DeviceGroup>
     */
    @GetMapping("/")
    public List<DeviceGroup> loadAll() {                
    	List<DeviceGroup> deviceGroupList = null;
        
    	try {
            // load the DeviceGroup
            deviceGroupList = service.getAllDeviceGroup();
            
            if ( deviceGroupList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all DeviceGroups" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all DeviceGroups ", exc );
        	return null;
        }

        return deviceGroupList;
                            
    }



//************************************************************************    
// Attributes
//************************************************************************
    protected DeviceGroup deviceGroup = null;
    protected DeviceGroupService service = null;
    private static final Logger LOGGER = Logger.getLogger(DeviceGroupQueryRestController.class.getName());
    
}
