
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller.query;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.projector.*;

import com.harbormaster.controller.*;
/**
 * <h2>UsageRecordQueryRestController as REST API</h2>
 * <p>
 * Implements Spring Controller query CQRS processing for entity UsageRecord.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	UsageRecordService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateUsageRecordCommand</li>
 *      <li></li>UpdateUsageRecordCommand</li>
 *      <liDeleteUsageRecordCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@CrossOrigin
@RestController
@RequestMapping("/UsageRecordQuery")
public class UsageRecordQueryRestController extends BaseSpringRestController {
	
	public UsageRecordQueryRestController( UsageRecordService service ) {
        this.service = service;
    }
    
    /**
     * Handles loading a UsageRecord using a UUID
     * @param		UUID usageRecordId
     * @return		UsageRecord
     */    
    @GetMapping("/load")
    public UsageRecord load( @RequestParam(required=true) UUID usageRecordId ) {
    	UsageRecord entity = null;

    	try {  
    		entity = service.getUsageRecord( new UsageRecordFetchOneSummary( usageRecordId ) );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load UsageRecord using Id " + usageRecordId );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all UsageRecord business objects
     * @return		Set<UsageRecord>
     */
    @GetMapping("/")
    public List<UsageRecord> loadAll() {                
    	List<UsageRecord> usageRecordList = null;
        
    	try {
            // load the UsageRecord
            usageRecordList = service.getAllUsageRecord();
            
            if ( usageRecordList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all UsageRecords" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all UsageRecords ", exc );
        	return null;
        }

        return usageRecordList;
                            
    }



//************************************************************************    
// Attributes
//************************************************************************
    protected UsageRecord usageRecord = null;
    protected UsageRecordService service = null;
    private static final Logger LOGGER = Logger.getLogger(UsageRecordQueryRestController.class.getName());
    
}
