
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * Analytics Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace analyticsonaspdotnet.Domain;

/// <summary>
/// DashboardStatus enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum DashboardStatus
{
    Draft=1,Live=2,Archived=3
}

/// <summary>
/// Extension of capabilities for the DashboardStatus enum
/// </summary>
public static class DashboardStatusExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<DashboardStatus> GetValues()
    {
        return Enum.GetValues<DashboardStatus>().ToList();
    }

    public static DashboardStatus GetDefaultValue()
    {
        return Enum.GetValues<DashboardStatus>().First();
    }

    public static DashboardStatus WhichOne(string name)
    {
        if (Enum.TryParse<DashboardStatus>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



