
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * Analytics Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace analyticsonaspdotnet.Domain;

/// <summary>
/// SubjectType enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum SubjectType
{
    User=1,Group=2,Service=3
}

/// <summary>
/// Extension of capabilities for the SubjectType enum
/// </summary>
public static class SubjectTypeExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<SubjectType> GetValues()
    {
        return Enum.GetValues<SubjectType>().ToList();
    }

    public static SubjectType GetDefaultValue()
    {
        return Enum.GetValues<SubjectType>().First();
    }

    public static SubjectType WhichOne(string name)
    {
        if (Enum.TryParse<SubjectType>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



