
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * HCIDL Governance Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace governanceonaspdotnet.Domain;

/// <summary>
/// LegalHoldStatus enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum LegalHoldStatus
{
    Active=1,Released=2,Superseded=3
}

/// <summary>
/// Extension of capabilities for the LegalHoldStatus enum
/// </summary>
public static class LegalHoldStatusExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<LegalHoldStatus> GetValues()
    {
        return Enum.GetValues<LegalHoldStatus>().ToList();
    }

    public static LegalHoldStatus GetDefaultValue()
    {
        return Enum.GetValues<LegalHoldStatus>().First();
    }

    public static LegalHoldStatus WhichOne(string name)
    {
        if (Enum.TryParse<LegalHoldStatus>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



