
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * HCIDL Governance Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace governanceonaspdotnet.Domain;

/// <summary>
/// RecordType enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum RecordType
{
    PolicyRecord=1,ContractRecord=2,FinancialRecord=3,HRRecord=4,CustomerRecord=5,TechnicalRecord=6,AuditRecord=7,LegalRecord=8
}

/// <summary>
/// Extension of capabilities for the RecordType enum
/// </summary>
public static class RecordTypeExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<RecordType> GetValues()
    {
        return Enum.GetValues<RecordType>().ToList();
    }

    public static RecordType GetDefaultValue()
    {
        return Enum.GetValues<RecordType>().First();
    }

    public static RecordType WhichOne(string name)
    {
        if (Enum.TryParse<RecordType>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



