
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * HCIDL Governance Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace governanceonaspdotnet.Domain;

/// <summary>
/// RetentionTrigger enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum RetentionTrigger
{
    CreationDate=1,LastModified=2,Termination=3,ContractEnd=4,EventCompletion=5,FiscalYearEnd=6
}

/// <summary>
/// Extension of capabilities for the RetentionTrigger enum
/// </summary>
public static class RetentionTriggerExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<RetentionTrigger> GetValues()
    {
        return Enum.GetValues<RetentionTrigger>().ToList();
    }

    public static RetentionTrigger GetDefaultValue()
    {
        return Enum.GetValues<RetentionTrigger>().First();
    }

    public static RetentionTrigger WhichOne(string name)
    {
        if (Enum.TryParse<RetentionTrigger>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



