
package com.harbormaster.aggregate;
import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.axonframework.commandhandling.CommandHandler;
import org.axonframework.modelling.command.AggregateMember;
import org.axonframework.eventsourcing.EventSourcingHandler;
import org.axonframework.modelling.command.AggregateIdentifier;
import static org.axonframework.modelling.command.AggregateLifecycle.apply;
import org.axonframework.spring.stereotype.Aggregate;
import org.springframework.context.annotation.Profile;

/**
 * <h2>AlertRuleAggregate</h2>
 * <p>
 * The AlertRule aggregate is the authoritative consistency boundary for all
 * branch-related operations. It validates incoming commands, enforces
 * business rules, maintains the integrity of the AlertRule domain, and emits
 * immutable domain events representing state changes.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateAlertRuleCommand</li>
 *      <li>UpdateAlertRuleCommand</li>
 *      <li>DeleteAlertRuleCommand</li>
 *      </ul>
 *
 * <h3>Associations</h3>
 * <ul>
 *       <li>AssignTenantToAlertRuleCommand</li>
 *       <li>UnAssignTenantFromAlertRuleCommand</li>
 *  </ul>
 *  <ul>
 *       <li>AssignStreamsToAlertRuleCommand</li>
 *       <li>RemoveStreamsFromAlertRuleCommand</li>
 *   </ul>
 *
 * <p>
 * @author Harbormaster Dev Team
 * </p>
 *       <li>AssignAlertsToAlertRuleCommand</li>
 *       <li>RemoveAlertsFromAlertRuleCommand</li>
 *   </ul>
 *
 * <p>
 * @author Harbormaster Dev Team
 * </p>
 *
 *
 * <h3>Events Emitted</h3>
 *      <ul>
 *      <li>CreateAlertRuleEvent</li>
 *      <li>UpdateAlertRuleEvent</li>
 *      <li>DeleteAlertRuleEvent</li>
   *       <li>AssignTenantToAlertRuleEvent</li>
 *       <li>UnAssignTenantFromAlertRuleEvent</li>
   *       <li>AssignStreamsToAlertRuleEvent</li>
 *       <li>RemoveStreamsFromAlertRuleEvent</li>
  *       <li>AssignAlertsToAlertRuleEvent</li>
 *       <li>RemoveAlertsFromAlertRuleEvent</li>
  *        </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Aggregate
public class AlertRuleAggregate {  

	// -----------------------------------------
	// Axon requires an empty constructor
    // -----------------------------------------
    public AlertRuleAggregate() {
    }

	// ----------------------------------------------
	// intrinsic command handlers
	// ----------------------------------------------
    @CommandHandler
    public AlertRuleAggregate(CreateAlertRuleCommand command) throws Exception {
    	LOGGER.info( "Handling command CreateAlertRuleCommand" );
    	CreateAlertRuleEvent event = new CreateAlertRuleEvent(command.getAlertRuleId(), command.getName(), command.getExpression(), command.getSeverity());
    	
        apply(event);
    }

    @CommandHandler
    public void handle(UpdateAlertRuleCommand command) throws Exception {
    	LOGGER.info( "handling command UpdateAlertRuleCommand" );
    	UpdateAlertRuleEvent event = new UpdateAlertRuleEvent(command.getAlertRuleId(), command.getName(), command.getExpression(), command.getTenant(), command.getStreams(), command.getAlerts(), command.getSeverity());        
    	
        apply(event);
    }

    @CommandHandler
    public void handle(DeleteAlertRuleCommand command) throws Exception {
    	LOGGER.info( "Handling command DeleteAlertRuleCommand" );
        apply(new DeleteAlertRuleEvent(command.getAlertRuleId()));
    }

	// ----------------------------------------------
	// association command handlers
	// ----------------------------------------------

    // single association commands
    @CommandHandler
    public void handle(AssignTenantToAlertRuleCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignTenantToAlertRuleCommand" );
    	
    	if (  tenant != null && tenant.getTenantId() == command.getAssignment().getTenantId() )
    		throw new ProcessingException( "Tenant already assigned with id " + command.getAssignment().getTenantId() );  
    		
        apply(new AssignTenantToAlertRuleEvent(command.getAlertRuleId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignTenantFromAlertRuleCommand command) throws Exception {
    	LOGGER.info( "Handling command UnAssignTenantFromAlertRuleCommand" );

    	if (  tenant == null )
    		throw new ProcessingException( "Tenant already has nothing assigned." );  

    	apply(new UnAssignTenantFromAlertRuleEvent(command.getAlertRuleId()));
    }

    // multiple association commands
    @CommandHandler
    public void handle(AssignStreamsToAlertRuleCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignStreamsToAlertRuleCommand" );
    	
    	if ( streams.contains( command.getAddTo() ) )
    		throw new ProcessingException( "Streams already contains an entity with id " + command.getAddTo().getTelemetryStreamId() );

    	apply(new AssignStreamsToAlertRuleEvent(command.getAlertRuleId(), command.getAddTo()));
    }

    @CommandHandler
    public void handle(RemoveStreamsFromAlertRuleCommand command) throws Exception {
    	LOGGER.info( "Handling command RemoveStreamsFromAlertRuleCommand" );
    	
    	if ( !streams.contains( command.getRemoveFrom() ) )
    		throw new ProcessingException( "Streams does not contain an entity with id " + command.getRemoveFrom().getTelemetryStreamId() );

        apply(new RemoveStreamsFromAlertRuleEvent(command.getAlertRuleId(), command.getRemoveFrom()));
    }
    @CommandHandler
    public void handle(AssignAlertsToAlertRuleCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignAlertsToAlertRuleCommand" );
    	
    	if ( alerts.contains( command.getAddTo() ) )
    		throw new ProcessingException( "Alerts already contains an entity with id " + command.getAddTo().getAlertId() );

    	apply(new AssignAlertsToAlertRuleEvent(command.getAlertRuleId(), command.getAddTo()));
    }

    @CommandHandler
    public void handle(RemoveAlertsFromAlertRuleCommand command) throws Exception {
    	LOGGER.info( "Handling command RemoveAlertsFromAlertRuleCommand" );
    	
    	if ( !alerts.contains( command.getRemoveFrom() ) )
    		throw new ProcessingException( "Alerts does not contain an entity with id " + command.getRemoveFrom().getAlertId() );

        apply(new RemoveAlertsFromAlertRuleEvent(command.getAlertRuleId(), command.getRemoveFrom()));
    }

	// ----------------------------------------------
	// intrinsic event source handlers
	// ----------------------------------------------
    @EventSourcingHandler
    void on(CreateAlertRuleEvent event) {	
    	LOGGER.info( "Event sourcing CreateAlertRuleEvent" );
    	this.alertRuleId = event.getAlertRuleId();
        this.name = event.getName();
        this.expression = event.getExpression();
        this.severity = event.getSeverity();
    }
    
    @EventSourcingHandler
    void on(UpdateAlertRuleEvent event) {
    	LOGGER.info( "Event sourcing classObject.getUpdateEventAlias()}" );
        this.name = event.getName();
        this.expression = event.getExpression();
        this.tenant = event.getTenant();
        this.streams = event.getStreams();
        this.alerts = event.getAlerts();
        this.severity = event.getSeverity();
    }   

	// ----------------------------------------------
	// association event source handlers
	// ----------------------------------------------
	// single associations
    @EventSourcingHandler
    void on(AssignTenantToAlertRuleEvent event ) {	
    	LOGGER.info( "Event sourcing AssignTenantToAlertRuleEvent" );
    	this.tenant = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignTenantFromAlertRuleEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignTenantFromAlertRuleEvent" );
		this.tenant = null;
	}

	// multiple associations
    @EventSourcingHandler
    void on(AssignStreamsToAlertRuleEvent event ) {
    	LOGGER.info( "Event sourcing AssignStreamsToAlertRuleEvent" );
    	this.streams.add( event.getAddTo() );
    }

	@EventSourcingHandler
	void on(RemoveStreamsFromAlertRuleEvent event ) {	
		LOGGER.info( "Event sourcing RemoveStreamsFromAlertRuleEvent" );
		this.streams.remove( event.getRemoveFrom() );
	}
	
	// multiple associations
    @EventSourcingHandler
    void on(AssignAlertsToAlertRuleEvent event ) {
    	LOGGER.info( "Event sourcing AssignAlertsToAlertRuleEvent" );
    	this.alerts.add( event.getAddTo() );
    }

	@EventSourcingHandler
	void on(RemoveAlertsFromAlertRuleEvent event ) {	
		LOGGER.info( "Event sourcing RemoveAlertsFromAlertRuleEvent" );
		this.alerts.remove( event.getRemoveFrom() );
	}
	

    // ------------------------------------------
    // attributes
    // ------------------------------------------
	
    @AggregateIdentifier
    private UUID alertRuleId;
    
    private String name;
    private String expression;
    private AlertSeverity severity;
    private Tenant tenant = null;
    private Set<TelemetryStream> streams = new HashSet<>();
    private Set<Alert> alerts = new HashSet<>();

    private static final Logger LOGGER 	= Logger.getLogger(AlertRuleAggregate.class.getName());
}
