
package com.harbormaster.aggregate;
import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.axonframework.commandhandling.CommandHandler;
import org.axonframework.modelling.command.AggregateMember;
import org.axonframework.eventsourcing.EventSourcingHandler;
import org.axonframework.modelling.command.AggregateIdentifier;
import static org.axonframework.modelling.command.AggregateLifecycle.apply;
import org.axonframework.spring.stereotype.Aggregate;
import org.springframework.context.annotation.Profile;

/**
 * <h2>TwinTemplateAggregate</h2>
 * <p>
 * The TwinTemplate aggregate is the authoritative consistency boundary for all
 * branch-related operations. It validates incoming commands, enforces
 * business rules, maintains the integrity of the TwinTemplate domain, and emits
 * immutable domain events representing state changes.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateTwinTemplateCommand</li>
 *      <li>UpdateTwinTemplateCommand</li>
 *      <li>DeleteTwinTemplateCommand</li>
 *      </ul>
 *
 * <h3>Associations</h3>
 * <ul>
 *  </ul>
 *  <ul>
 *       <li>AssignDeviceModelsToTwinTemplateCommand</li>
 *       <li>RemoveDeviceModelsFromTwinTemplateCommand</li>
 *   </ul>
 *
 * <p>
 * @author Harbormaster Dev Team
 * </p>
 *
 *
 * <h3>Events Emitted</h3>
 *      <ul>
 *      <li>CreateTwinTemplateEvent</li>
 *      <li>UpdateTwinTemplateEvent</li>
 *      <li>DeleteTwinTemplateEvent</li>
    *       <li>AssignDeviceModelsToTwinTemplateEvent</li>
 *       <li>RemoveDeviceModelsFromTwinTemplateEvent</li>
  *        </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Aggregate
public class TwinTemplateAggregate {  

	// -----------------------------------------
	// Axon requires an empty constructor
    // -----------------------------------------
    public TwinTemplateAggregate() {
    }

	// ----------------------------------------------
	// intrinsic command handlers
	// ----------------------------------------------
    @CommandHandler
    public TwinTemplateAggregate(CreateTwinTemplateCommand command) throws Exception {
    	LOGGER.info( "Handling command CreateTwinTemplateCommand" );
    	CreateTwinTemplateEvent event = new CreateTwinTemplateEvent(command.getTwinTemplateId(), command.getName(), command.getSchemaUri(), command.getVersion());
    	
        apply(event);
    }

    @CommandHandler
    public void handle(UpdateTwinTemplateCommand command) throws Exception {
    	LOGGER.info( "handling command UpdateTwinTemplateCommand" );
    	UpdateTwinTemplateEvent event = new UpdateTwinTemplateEvent(command.getTwinTemplateId(), command.getName(), command.getSchemaUri(), command.getVersion(), command.getDeviceModels());        
    	
        apply(event);
    }

    @CommandHandler
    public void handle(DeleteTwinTemplateCommand command) throws Exception {
    	LOGGER.info( "Handling command DeleteTwinTemplateCommand" );
        apply(new DeleteTwinTemplateEvent(command.getTwinTemplateId()));
    }

	// ----------------------------------------------
	// association command handlers
	// ----------------------------------------------

    // single association commands

    // multiple association commands
    @CommandHandler
    public void handle(AssignDeviceModelsToTwinTemplateCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignDeviceModelsToTwinTemplateCommand" );
    	
    	if ( deviceModels.contains( command.getAddTo() ) )
    		throw new ProcessingException( "DeviceModels already contains an entity with id " + command.getAddTo().getDeviceModelId() );

    	apply(new AssignDeviceModelsToTwinTemplateEvent(command.getTwinTemplateId(), command.getAddTo()));
    }

    @CommandHandler
    public void handle(RemoveDeviceModelsFromTwinTemplateCommand command) throws Exception {
    	LOGGER.info( "Handling command RemoveDeviceModelsFromTwinTemplateCommand" );
    	
    	if ( !deviceModels.contains( command.getRemoveFrom() ) )
    		throw new ProcessingException( "DeviceModels does not contain an entity with id " + command.getRemoveFrom().getDeviceModelId() );

        apply(new RemoveDeviceModelsFromTwinTemplateEvent(command.getTwinTemplateId(), command.getRemoveFrom()));
    }

	// ----------------------------------------------
	// intrinsic event source handlers
	// ----------------------------------------------
    @EventSourcingHandler
    void on(CreateTwinTemplateEvent event) {	
    	LOGGER.info( "Event sourcing CreateTwinTemplateEvent" );
    	this.twinTemplateId = event.getTwinTemplateId();
        this.name = event.getName();
        this.schemaUri = event.getSchemaUri();
        this.version = event.getVersion();
    }
    
    @EventSourcingHandler
    void on(UpdateTwinTemplateEvent event) {
    	LOGGER.info( "Event sourcing classObject.getUpdateEventAlias()}" );
        this.name = event.getName();
        this.schemaUri = event.getSchemaUri();
        this.version = event.getVersion();
        this.deviceModels = event.getDeviceModels();
    }   

	// ----------------------------------------------
	// association event source handlers
	// ----------------------------------------------

	// multiple associations
    @EventSourcingHandler
    void on(AssignDeviceModelsToTwinTemplateEvent event ) {
    	LOGGER.info( "Event sourcing AssignDeviceModelsToTwinTemplateEvent" );
    	this.deviceModels.add( event.getAddTo() );
    }

	@EventSourcingHandler
	void on(RemoveDeviceModelsFromTwinTemplateEvent event ) {	
		LOGGER.info( "Event sourcing RemoveDeviceModelsFromTwinTemplateEvent" );
		this.deviceModels.remove( event.getRemoveFrom() );
	}
	

    // ------------------------------------------
    // attributes
    // ------------------------------------------
	
    @AggregateIdentifier
    private UUID twinTemplateId;
    
    private String name;
    private Uri schemaUri;
    private String version;
    private Set<DeviceModel> deviceModels = new HashSet<>();

    private static final Logger LOGGER 	= Logger.getLogger(TwinTemplateAggregate.class.getName());
}
