
/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * HCIDL Inventory Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace inventoryonaspdotnet.Domain;

/// <summary>
/// RotationMethod enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum RotationMethod
{
    FIFO=1,LIFO=2,FEFO=3
}

/// <summary>
/// Extension of capabilities for the RotationMethod enum
/// </summary>
public static class RotationMethodExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<RotationMethod> GetValues()
    {
        return Enum.GetValues<RotationMethod>().ToList();
    }

    public static RotationMethod GetDefaultValue()
    {
        return Enum.GetValues<RotationMethod>().First();
    }

    public static RotationMethod WhichOne(string name)
    {
        if (Enum.TryParse<RotationMethod>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



