name: Cloud Only

on:
  workflow_dispatch:
    inputs:
      repository:
        description: App repo owner/name
        required: true
        default: Harbormaster-AI/banking-on-springboot
        type: string
      branch:
        description: App branch
        required: true
        default: master
        type: string
      appName:
        required: true
        default: bankingOnSpringboot
        type: string
      gitHubToken:
        required: true
        type: string
      certificationIdentifier:
        required: true
        default: test-banking-cloud-only
        type: string
      runner:
        required: false
        default: ubuntu-latest
        type: string
      awsRegion:
        required: false
        default: us-east-2
        type: string
      resultUrl:
        required: false
        default: http://localhost:3000
        type: string
      actionToCall:
        required: false
        default: updateSystemVerificationProgress
        type: string

jobs:
  cloud:
    uses: ./.github/workflows/cloud-verification.yml
    secrets: inherit
    with:
      runner: ${{ inputs.runner }}
      repository: ${{ inputs.repository }}
      branch: ${{ inputs.branch }}
      gitHubToken: ${{ inputs.gitHubToken }}
      appName: ${{ inputs.appName }}
      certificationIdentifier: ${{ inputs.certificationIdentifier }}
      resultUrl: ${{ inputs.resultUrl }}
      actionToCall: ${{ inputs.actionToCall }}
      dockerOrg: theharbormaster
      dockerRepository: banking-on-springboot
      dockerTag: latest
      awsRegion: ${{ inputs.awsRegion }}