name: #appName GitHub Actions CI

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1' # The Go version to download (if necessary) and use.


      run: cd terraform && chmod 777 terraform.sh && ./terraform.sh install
