/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;

import org.axonframework.commandhandling.gateway.CommandGateway;
import org.axonframework.queryhandling.QueryGateway;
import org.axonframework.queryhandling.QueryUpdateEmitter;
import org.axonframework.messaging.responsetypes.ResponseTypes;
import org.springframework.stereotype.Service;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.validator.*;

/**
 *
 * <h2>MessagingEndpoint business service</h2>
 *
 * <p>
 * This class implements the Service design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of MessagingEndpoint related services in the case of a MessagingEndpoint business related service failing.</li>
 * <li>Exposes a simpler, uniform MessagingEndpoint interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill MessagingEndpoint business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class MessagingEndpointService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public MessagingEndpointService()  {
	}

	@Override
	public void setApplicationContext(ApplicationContext ctx) throws BeansException {
		super.setApplicationContext(ctx);

		queryGateway 		= ctx.getBean(QueryGateway.class);
		commandGateway 		= ctx.getBean(CommandGateway.class);
		queryUpdateEmitter  = ctx.getBean(QueryUpdateEmitter.class);
		validator			= ctx.getBean(MessagingEndpointValidator.class);
	}


   /**
	* MessagingEndpoint Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	MessagingEndpointService
	*/
	public static MessagingEndpointService getMessagingEndpointInstance() {
		return( new MessagingEndpointService() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		CompletableFuture<UUID>
    */
	public CompletableFuture<UUID> createMessagingEndpoint( CreateMessagingEndpointCommand command )
    throws ProcessingException, IllegalArgumentException {

		CompletableFuture<UUID> completableFuture = null;
				
		try {
			// --------------------------------------
        	// assign identity now if none
        	// -------------------------------------- 
			if ( command.getMessagingEndpointId() == null )
				command.setMessagingEndpointId( UUID.randomUUID() );
				
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	validator.validate( command );    

    		// ---------------------------------------
    		// issue the CreateMessagingEndpointCommand - by convention the future return value for a create command
        	// that is handled by the constructor of an aggregate will return the UUID 
    		// ---------------------------------------
        	completableFuture = commandGateway.send( command );
        	
			LOGGER.log( Level.INFO, "return from Command Gateway for CreateMessagingEndpointCommand of MessagingEndpoint is " + command );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create MessagingEndpoint - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return completableFuture;
    }

   /**
    * Update the provided command.
    * @param		command UpdateMessagingEndpointCommand
    * @return		CompletableFuture<Void>
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    */
    public CompletableFuture<Void> updateMessagingEndpoint( UpdateMessagingEndpointCommand command ) 
    throws ProcessingException, IllegalArgumentException {
    	CompletableFuture<Void> completableFuture = null;
    	
    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	validator.validate( command );    

        	// --------------------------------------
        	// issue the UpdateMessagingEndpointCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save MessagingEndpoint - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        
    	return completableFuture;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteMessagingEndpointCommand
    * @return		CompletableFuture<Void>
    * @exception 	ProcessingException
    */
    public CompletableFuture<Void> delete( DeleteMessagingEndpointCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
    	
    	CompletableFuture<Void> completableFuture = null;
    	
        try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	validator.validate( command );    
        	
        	// --------------------------------------
        	// issue the DeleteMessagingEndpointCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete MessagingEndpoint using Id = "  + command.getMessagingEndpointId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
        
        return completableFuture;
    }

    /**
     * Method to retrieve the MessagingEndpoint via MessagingEndpointFetchOneSummary
     * @param 	summary MessagingEndpointFetchOneSummary 
     * @return 	MessagingEndpointFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public MessagingEndpoint getMessagingEndpoint( MessagingEndpointFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "MessagingEndpointFetchOneSummary arg cannot be null" );
    	
    	MessagingEndpoint entity = null;
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	validator.validate( summary );    
        	
        	// --------------------------------------
        	// use queryGateway to send request to Find a MessagingEndpoint
        	// --------------------------------------
        	CompletableFuture<MessagingEndpoint> futureEntity = queryGateway.query(new FindMessagingEndpointQuery( new LoadMessagingEndpointFilter( summary.getMessagingEndpointId() ) ), ResponseTypes.instanceOf(MessagingEndpoint.class));
        	
        	entity = futureEntity.get();
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate MessagingEndpoint with id " + summary.getMessagingEndpointId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all MessagingEndpoints
     *
     * @return 	List<MessagingEndpoint> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<MessagingEndpoint> getAllMessagingEndpoint() 
    throws ProcessingException {
        List<MessagingEndpoint> list = null;

        try {
        	CompletableFuture<List<MessagingEndpoint>> futureList = queryGateway.query(new FindAllMessagingEndpointQuery(), ResponseTypes.multipleInstancesOf(MessagingEndpoint.class));
        	
        	list = futureList.get();
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all MessagingEndpoint";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Tenant on MessagingEndpoint
     * @param		command AssignTenantToMessagingEndpointCommand	
     * @exception	ProcessingException
     */     
	public void assignTenant( AssignTenantToMessagingEndpointCommand command ) throws ProcessingException {

		// --------------------------------------------
		// load the parent
		// --------------------------------------------
		load( command.getMessagingEndpointId() );
		
		TenantService childDelegate 	= TenantService.getTenantInstance();
		MessagingEndpointService parentDelegate = MessagingEndpointService.getMessagingEndpointInstance();			
		UUID childId = command.getAssignment().getTenantId();
		Tenant child = null;
		
		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );

		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Tenant using id " + childId;
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Tenant on MessagingEndpoint
     * @param		command UnAssignTenantFromMessagingEndpointCommand
     * @exception	ProcessingException
     */     
	public void unAssignTenant( UnAssignTenantFromMessagingEndpointCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    
	
	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Tenant on MessagingEndpoint";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	

    /**
     * add TelemetryStream to Streams 
     * @param		command AssignStreamsToMessagingEndpointCommand
     * @exception	ProcessingException
     */     
	public void addToStreams( AssignStreamsToMessagingEndpointCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getMessagingEndpointId() );

		TelemetryStreamService childDelegate 	= TelemetryStreamService.getTelemetryStreamInstance();
		MessagingEndpointService parentDelegate = MessagingEndpointService.getMessagingEndpointInstance();		
		UUID childId = command.getAddTo().getTelemetryStreamId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a TelemetryStream as Streams to MessagingEndpoint" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove TelemetryStream from Streams
     * @param		command RemoveStreamsFromMessagingEndpointCommand
     * @exception	ProcessingException
     */     	
	public void removeFromStreams( RemoveStreamsFromMessagingEndpointCommand command ) throws ProcessingException {		
		
		TelemetryStreamService childDelegate 	= TelemetryStreamService.getTelemetryStreamInstance();
		UUID childId = command.getRemoveFrom().getTelemetryStreamId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}



	/**
	 * Internal helper method to load the root 
	 * 
	 * @param		id	UUID
	 * @return		MessagingEndpoint
	 */
	protected MessagingEndpoint load( UUID id ) throws ProcessingException {
		messagingEndpoint = MessagingEndpointService.getMessagingEndpointInstance().getMessagingEndpoint( new MessagingEndpointFetchOneSummary(id) );	
		return messagingEndpoint;
	}


//************************************************************************
// Attributes
//************************************************************************
	private QueryGateway queryGateway;
	private CommandGateway commandGateway;
	private QueryUpdateEmitter queryUpdateEmitter;
	private MessagingEndpointValidator validator;
	private MessagingEndpoint messagingEndpoint 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(MessagingEndpointService.class.getName());
    
}
