/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Insurance Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */

package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>ReinsuranceAgreement business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of ReinsuranceAgreement related services in the case of a ReinsuranceAgreement business related service failing.</li>
 * <li>Exposes a simpler, uniform ReinsuranceAgreement interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill ReinsuranceAgreement business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Insurance Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core insurance product, underwriting, policy, billing, claims, and reinsurance capabilities.</td></tr>
 *          <tr><td>industry</td><td>Insurance</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class ReinsuranceAgreementService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public ReinsuranceAgreementService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new ReinsuranceAgreementEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(ReinsuranceAgreementRepository.class) );
		this.validator		= applicationContext.getBean(ReinsuranceAgreementValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		ReinsuranceAgreement
	 */
		public ReinsuranceAgreement createReinsuranceAgreement( CreateReinsuranceAgreementCommand command ) {

		ReinsuranceAgreement entity = new ReinsuranceAgreement();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setReinsuranceAgreementId( command.getReinsuranceAgreementId() );
            entity.setAgreementNumber( command.getAgreementNumber() );
            entity.setEffectivePeriod( command.getEffectivePeriod() );
            entity.setRetention( command.getRetention() );
            entity.setLimit( command.getLimit() );
            entity.setCessionPercentage( command.getCessionPercentage() );
            entity.setReinsuranceType( command.getReinsuranceType() );
            entity.setTreatyType( command.getTreatyType() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of ReinsuranceAgreement {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateReinsuranceAgreementCommand
	 * @return		ReinsuranceAgreement
	 */
	public ReinsuranceAgreement updateReinsuranceAgreement( UpdateReinsuranceAgreementCommand command ) {

		ReinsuranceAgreement entity = new ReinsuranceAgreement();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setReinsuranceAgreementId( command.getReinsuranceAgreementId() );
            entity.setAgreementNumber( command.getAgreementNumber() );
            entity.setEffectivePeriod( command.getEffectivePeriod() );
            entity.setRetention( command.getRetention() );
            entity.setLimit( command.getLimit() );
            entity.setCessionPercentage( command.getCessionPercentage() );
            entity.setInsurer( command.getInsurer() );
            entity.setPolicies( command.getPolicies() );
            entity.setReinsuranceType( command.getReinsuranceType() );
            entity.setTreatyType( command.getTreatyType() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of ReinsuranceAgreement {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteReinsuranceAgreementCommand
	 */
	public void delete( DeleteReinsuranceAgreementCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getReinsuranceAgreementId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of ReinsuranceAgreement {0} ", id );

	}

	/**
	 * Method to retrieve the ReinsuranceAgreement via ReinsuranceAgreementFetchOneSummary
	 * @param 	summary ReinsuranceAgreementFetchOneSummary
	 * @return 	ReinsuranceAgreementFetchOneResponse
	 */
	public ReinsuranceAgreement getReinsuranceAgreement( ReinsuranceAgreementFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "ReinsuranceAgreementFetchOneSummary arg cannot be null" );

		ReinsuranceAgreement entity = null;
		UUID id = summary.getReinsuranceAgreementId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a ReinsuranceAgreement using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all ReinsuranceAgreements
	 *
	 * @return 	List<ReinsuranceAgreement>
	 */
    public List<ReinsuranceAgreement> getAllReinsuranceAgreement() {
		List<ReinsuranceAgreement> list = projector.findAll( new FindAllReinsuranceAgreementQuery() );
		return list;
	}

	/**
	 * assign Insurer on ReinsuranceAgreement
	 * @param		command AssignInsurerToReinsuranceAgreementCommand
	 */
	public void assignInsurer( AssignInsurerToReinsuranceAgreementCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignInsurer(command.getChildId(), command.getAssignment());

	}

	/**
	 * unAssign Insurer on ReinsuranceAgreement
	 * @param		command UnAssignInsurerFromReinsuranceAgreementCommand
	 */
	public void unAssignInsurer( UnAssignInsurerFromReinsuranceAgreementCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignInsurer(command.getChildId());
	}
	

	/**
	 * add Policy to Policies
	 * @param		command AssignPoliciesToReinsuranceAgreementCommand
	 */
	public void addToPolicies( AssignPoliciesToReinsuranceAgreementCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToPolicies(command.getParentId(), command.getChildIds());
	}

	/**
	 * remove Policy from Policies
	 * @param		command RemovePoliciesFromReinsuranceAgreementCommand
	 */
	public void removeFromPolicies( RemovePoliciesFromReinsuranceAgreementCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromPolicies(command.getParentId(), command.getChildIds());
	}




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final ReinsuranceAgreementEntityProjector projector;
	private final ReinsuranceAgreementValidator validator;
	private ReinsuranceAgreement reinsuranceAgreement 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(ReinsuranceAgreementService.class);
}
