/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;

import org.axonframework.commandhandling.gateway.CommandGateway;
import org.axonframework.queryhandling.QueryGateway;
import org.axonframework.queryhandling.QueryUpdateEmitter;
import org.axonframework.messaging.responsetypes.ResponseTypes;
import org.springframework.stereotype.Service;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.validator.*;

/**
 *
 * <h2>Site business service</h2>
 *
 * <p>
 * This class implements the Service design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Site related services in the case of a Site business related service failing.</li>
 * <li>Exposes a simpler, uniform Site interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Site business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class SiteService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public SiteService()  {
	}

	@Override
	public void setApplicationContext(ApplicationContext ctx) throws BeansException {
		super.setApplicationContext(ctx);

		queryGateway 		= ctx.getBean(QueryGateway.class);
		commandGateway 		= ctx.getBean(CommandGateway.class);
		queryUpdateEmitter  = ctx.getBean(QueryUpdateEmitter.class);
		validator			= ctx.getBean(SiteValidator.class);
	}


   /**
	* Site Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	SiteService
	*/
	public static SiteService getSiteInstance() {
		return( new SiteService() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		CompletableFuture<UUID>
    */
	public CompletableFuture<UUID> createSite( CreateSiteCommand command )
    throws ProcessingException, IllegalArgumentException {

		CompletableFuture<UUID> completableFuture = null;
				
		try {
			// --------------------------------------
        	// assign identity now if none
        	// -------------------------------------- 
			if ( command.getSiteId() == null )
				command.setSiteId( UUID.randomUUID() );
				
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	validator.validate( command );    

    		// ---------------------------------------
    		// issue the CreateSiteCommand - by convention the future return value for a create command
        	// that is handled by the constructor of an aggregate will return the UUID 
    		// ---------------------------------------
        	completableFuture = commandGateway.send( command );
        	
			LOGGER.log( Level.INFO, "return from Command Gateway for CreateSiteCommand of Site is " + command );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create Site - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return completableFuture;
    }

   /**
    * Update the provided command.
    * @param		command UpdateSiteCommand
    * @return		CompletableFuture<Void>
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    */
    public CompletableFuture<Void> updateSite( UpdateSiteCommand command ) 
    throws ProcessingException, IllegalArgumentException {
    	CompletableFuture<Void> completableFuture = null;
    	
    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	validator.validate( command );    

        	// --------------------------------------
        	// issue the UpdateSiteCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save Site - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        
    	return completableFuture;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteSiteCommand
    * @return		CompletableFuture<Void>
    * @exception 	ProcessingException
    */
    public CompletableFuture<Void> delete( DeleteSiteCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
    	
    	CompletableFuture<Void> completableFuture = null;
    	
        try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	validator.validate( command );    
        	
        	// --------------------------------------
        	// issue the DeleteSiteCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete Site using Id = "  + command.getSiteId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
        
        return completableFuture;
    }

    /**
     * Method to retrieve the Site via SiteFetchOneSummary
     * @param 	summary SiteFetchOneSummary 
     * @return 	SiteFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public Site getSite( SiteFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "SiteFetchOneSummary arg cannot be null" );
    	
    	Site entity = null;
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	validator.validate( summary );    
        	
        	// --------------------------------------
        	// use queryGateway to send request to Find a Site
        	// --------------------------------------
        	CompletableFuture<Site> futureEntity = queryGateway.query(new FindSiteQuery( new LoadSiteFilter( summary.getSiteId() ) ), ResponseTypes.instanceOf(Site.class));
        	
        	entity = futureEntity.get();
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate Site with id " + summary.getSiteId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all Sites
     *
     * @return 	List<Site> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<Site> getAllSite() 
    throws ProcessingException {
        List<Site> list = null;

        try {
        	CompletableFuture<List<Site>> futureList = queryGateway.query(new FindAllSiteQuery(), ResponseTypes.multipleInstancesOf(Site.class));
        	
        	list = futureList.get();
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all Site";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Tenant on Site
     * @param		command AssignTenantToSiteCommand	
     * @exception	ProcessingException
     */     
	public void assignTenant( AssignTenantToSiteCommand command ) throws ProcessingException {

		// --------------------------------------------
		// load the parent
		// --------------------------------------------
		load( command.getSiteId() );
		
		TenantService childDelegate 	= TenantService.getTenantInstance();
		SiteService parentDelegate = SiteService.getSiteInstance();			
		UUID childId = command.getAssignment().getTenantId();
		Tenant child = null;
		
		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );

		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Tenant using id " + childId;
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Tenant on Site
     * @param		command UnAssignTenantFromSiteCommand
     * @exception	ProcessingException
     */     
	public void unAssignTenant( UnAssignTenantFromSiteCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    
	
	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Tenant on Site";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	

    /**
     * add Building to Buildings 
     * @param		command AssignBuildingsToSiteCommand
     * @exception	ProcessingException
     */     
	public void addToBuildings( AssignBuildingsToSiteCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getSiteId() );

		BuildingService childDelegate 	= BuildingService.getBuildingInstance();
		SiteService parentDelegate = SiteService.getSiteInstance();		
		UUID childId = command.getAddTo().getBuildingId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Building as Buildings to Site" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Building from Buildings
     * @param		command RemoveBuildingsFromSiteCommand
     * @exception	ProcessingException
     */     	
	public void removeFromBuildings( RemoveBuildingsFromSiteCommand command ) throws ProcessingException {		
		
		BuildingService childDelegate 	= BuildingService.getBuildingInstance();
		UUID childId = command.getRemoveFrom().getBuildingId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add IoTDevice to Devices 
     * @param		command AssignDevicesToSiteCommand
     * @exception	ProcessingException
     */     
	public void addToDevices( AssignDevicesToSiteCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getSiteId() );

		IoTDeviceService childDelegate 	= IoTDeviceService.getIoTDeviceInstance();
		SiteService parentDelegate = SiteService.getSiteInstance();		
		UUID childId = command.getAddTo().getIoTDeviceId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a IoTDevice as Devices to Site" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove IoTDevice from Devices
     * @param		command RemoveDevicesFromSiteCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDevices( RemoveDevicesFromSiteCommand command ) throws ProcessingException {		
		
		IoTDeviceService childDelegate 	= IoTDeviceService.getIoTDeviceInstance();
		UUID childId = command.getRemoveFrom().getIoTDeviceId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Gateway to Gateways 
     * @param		command AssignGatewaysToSiteCommand
     * @exception	ProcessingException
     */     
	public void addToGateways( AssignGatewaysToSiteCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getSiteId() );

		GatewayService childDelegate 	= GatewayService.getGatewayInstance();
		SiteService parentDelegate = SiteService.getSiteInstance();		
		UUID childId = command.getAddTo().getGatewayId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Gateway as Gateways to Site" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Gateway from Gateways
     * @param		command RemoveGatewaysFromSiteCommand
     * @exception	ProcessingException
     */     	
	public void removeFromGateways( RemoveGatewaysFromSiteCommand command ) throws ProcessingException {		
		
		GatewayService childDelegate 	= GatewayService.getGatewayInstance();
		UUID childId = command.getRemoveFrom().getGatewayId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}



	/**
	 * Internal helper method to load the root 
	 * 
	 * @param		id	UUID
	 * @return		Site
	 */
	protected Site load( UUID id ) throws ProcessingException {
		site = SiteService.getSiteInstance().getSite( new SiteFetchOneSummary(id) );	
		return site;
	}


//************************************************************************
// Attributes
//************************************************************************
	private QueryGateway queryGateway;
	private CommandGateway commandGateway;
	private QueryUpdateEmitter queryUpdateEmitter;
	private SiteValidator validator;
	private Site site 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(SiteService.class.getName());
    
}
