/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;

import org.axonframework.commandhandling.gateway.CommandGateway;
import org.axonframework.queryhandling.QueryGateway;
import org.axonframework.queryhandling.QueryUpdateEmitter;
import org.axonframework.messaging.responsetypes.ResponseTypes;
import org.springframework.stereotype.Service;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.validator.*;

/**
 *
 * <h2>SoftwareUpdateExecution business service</h2>
 *
 * <p>
 * This class implements the Service design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of SoftwareUpdateExecution related services in the case of a SoftwareUpdateExecution business related service failing.</li>
 * <li>Exposes a simpler, uniform SoftwareUpdateExecution interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill SoftwareUpdateExecution business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class SoftwareUpdateExecutionService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public SoftwareUpdateExecutionService()  {
	}

	@Override
	public void setApplicationContext(ApplicationContext ctx) throws BeansException {
		super.setApplicationContext(ctx);

		queryGateway 		= ctx.getBean(QueryGateway.class);
		commandGateway 		= ctx.getBean(CommandGateway.class);
		queryUpdateEmitter  = ctx.getBean(QueryUpdateEmitter.class);
		validator			= ctx.getBean(SoftwareUpdateExecutionValidator.class);
	}


   /**
	* SoftwareUpdateExecution Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	SoftwareUpdateExecutionService
	*/
	public static SoftwareUpdateExecutionService getSoftwareUpdateExecutionInstance() {
		return( new SoftwareUpdateExecutionService() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		CompletableFuture<UUID>
    */
	public CompletableFuture<UUID> createSoftwareUpdateExecution( CreateSoftwareUpdateExecutionCommand command )
    throws ProcessingException, IllegalArgumentException {

		CompletableFuture<UUID> completableFuture = null;
				
		try {
			// --------------------------------------
        	// assign identity now if none
        	// -------------------------------------- 
			if ( command.getSoftwareUpdateExecutionId() == null )
				command.setSoftwareUpdateExecutionId( UUID.randomUUID() );
				
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	validator.validate( command );    

    		// ---------------------------------------
    		// issue the CreateSoftwareUpdateExecutionCommand - by convention the future return value for a create command
        	// that is handled by the constructor of an aggregate will return the UUID 
    		// ---------------------------------------
        	completableFuture = commandGateway.send( command );
        	
			LOGGER.log( Level.INFO, "return from Command Gateway for CreateSoftwareUpdateExecutionCommand of SoftwareUpdateExecution is " + command );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create SoftwareUpdateExecution - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return completableFuture;
    }

   /**
    * Update the provided command.
    * @param		command UpdateSoftwareUpdateExecutionCommand
    * @return		CompletableFuture<Void>
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    */
    public CompletableFuture<Void> updateSoftwareUpdateExecution( UpdateSoftwareUpdateExecutionCommand command ) 
    throws ProcessingException, IllegalArgumentException {
    	CompletableFuture<Void> completableFuture = null;
    	
    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	validator.validate( command );    

        	// --------------------------------------
        	// issue the UpdateSoftwareUpdateExecutionCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save SoftwareUpdateExecution - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        
    	return completableFuture;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteSoftwareUpdateExecutionCommand
    * @return		CompletableFuture<Void>
    * @exception 	ProcessingException
    */
    public CompletableFuture<Void> delete( DeleteSoftwareUpdateExecutionCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
    	
    	CompletableFuture<Void> completableFuture = null;
    	
        try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	validator.validate( command );    
        	
        	// --------------------------------------
        	// issue the DeleteSoftwareUpdateExecutionCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete SoftwareUpdateExecution using Id = "  + command.getSoftwareUpdateExecutionId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
        
        return completableFuture;
    }

    /**
     * Method to retrieve the SoftwareUpdateExecution via SoftwareUpdateExecutionFetchOneSummary
     * @param 	summary SoftwareUpdateExecutionFetchOneSummary 
     * @return 	SoftwareUpdateExecutionFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public SoftwareUpdateExecution getSoftwareUpdateExecution( SoftwareUpdateExecutionFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "SoftwareUpdateExecutionFetchOneSummary arg cannot be null" );
    	
    	SoftwareUpdateExecution entity = null;
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	validator.validate( summary );    
        	
        	// --------------------------------------
        	// use queryGateway to send request to Find a SoftwareUpdateExecution
        	// --------------------------------------
        	CompletableFuture<SoftwareUpdateExecution> futureEntity = queryGateway.query(new FindSoftwareUpdateExecutionQuery( new LoadSoftwareUpdateExecutionFilter( summary.getSoftwareUpdateExecutionId() ) ), ResponseTypes.instanceOf(SoftwareUpdateExecution.class));
        	
        	entity = futureEntity.get();
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate SoftwareUpdateExecution with id " + summary.getSoftwareUpdateExecutionId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all SoftwareUpdateExecutions
     *
     * @return 	List<SoftwareUpdateExecution> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<SoftwareUpdateExecution> getAllSoftwareUpdateExecution() 
    throws ProcessingException {
        List<SoftwareUpdateExecution> list = null;

        try {
        	CompletableFuture<List<SoftwareUpdateExecution>> futureList = queryGateway.query(new FindAllSoftwareUpdateExecutionQuery(), ResponseTypes.multipleInstancesOf(SoftwareUpdateExecution.class));
        	
        	list = futureList.get();
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all SoftwareUpdateExecution";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Campaign on SoftwareUpdateExecution
     * @param		command AssignCampaignToSoftwareUpdateExecutionCommand	
     * @exception	ProcessingException
     */     
	public void assignCampaign( AssignCampaignToSoftwareUpdateExecutionCommand command ) throws ProcessingException {

		// --------------------------------------------
		// load the parent
		// --------------------------------------------
		load( command.getSoftwareUpdateExecutionId() );
		
		SoftwareUpdateCampaignService childDelegate 	= SoftwareUpdateCampaignService.getSoftwareUpdateCampaignInstance();
		SoftwareUpdateExecutionService parentDelegate = SoftwareUpdateExecutionService.getSoftwareUpdateExecutionInstance();			
		UUID childId = command.getAssignment().getSoftwareUpdateCampaignId();
		SoftwareUpdateCampaign child = null;
		
		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );

		}
        catch( Throwable exc ) {
			final String msg = "Failed to get SoftwareUpdateCampaign using id " + childId;
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Campaign on SoftwareUpdateExecution
     * @param		command UnAssignCampaignFromSoftwareUpdateExecutionCommand
     * @exception	ProcessingException
     */     
	public void unAssignCampaign( UnAssignCampaignFromSoftwareUpdateExecutionCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    
	
	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Campaign on SoftwareUpdateExecution";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign Device on SoftwareUpdateExecution
     * @param		command AssignDeviceToSoftwareUpdateExecutionCommand	
     * @exception	ProcessingException
     */     
	public void assignDevice( AssignDeviceToSoftwareUpdateExecutionCommand command ) throws ProcessingException {

		// --------------------------------------------
		// load the parent
		// --------------------------------------------
		load( command.getSoftwareUpdateExecutionId() );
		
		IoTDeviceService childDelegate 	= IoTDeviceService.getIoTDeviceInstance();
		SoftwareUpdateExecutionService parentDelegate = SoftwareUpdateExecutionService.getSoftwareUpdateExecutionInstance();			
		UUID childId = command.getAssignment().getIoTDeviceId();
		IoTDevice child = null;
		
		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );

		}
        catch( Throwable exc ) {
			final String msg = "Failed to get IoTDevice using id " + childId;
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Device on SoftwareUpdateExecution
     * @param		command UnAssignDeviceFromSoftwareUpdateExecutionCommand
     * @exception	ProcessingException
     */     
	public void unAssignDevice( UnAssignDeviceFromSoftwareUpdateExecutionCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    
	
	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Device on SoftwareUpdateExecution";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	



	/**
	 * Internal helper method to load the root 
	 * 
	 * @param		id	UUID
	 * @return		SoftwareUpdateExecution
	 */
	protected SoftwareUpdateExecution load( UUID id ) throws ProcessingException {
		softwareUpdateExecution = SoftwareUpdateExecutionService.getSoftwareUpdateExecutionInstance().getSoftwareUpdateExecution( new SoftwareUpdateExecutionFetchOneSummary(id) );	
		return softwareUpdateExecution;
	}


//************************************************************************
// Attributes
//************************************************************************
	private QueryGateway queryGateway;
	private CommandGateway commandGateway;
	private QueryUpdateEmitter queryUpdateEmitter;
	private SoftwareUpdateExecutionValidator validator;
	private SoftwareUpdateExecution softwareUpdateExecution 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(SoftwareUpdateExecutionService.class.getName());
    
}
