/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;

import org.axonframework.commandhandling.gateway.CommandGateway;
import org.axonframework.queryhandling.QueryGateway;
import org.axonframework.queryhandling.QueryUpdateEmitter;
import org.axonframework.messaging.responsetypes.ResponseTypes;
import org.springframework.stereotype.Service;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.validator.*;

/**
 *
 * <h2>Tenant business service</h2>
 *
 * <p>
 * This class implements the Service design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Tenant related services in the case of a Tenant business related service failing.</li>
 * <li>Exposes a simpler, uniform Tenant interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Tenant business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/14/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>IoT Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core IoT device, connectivity, telemetry, twin, command, security, and operations capabilities.</td></tr>
 *          <tr><td>industry</td><td>Internet of Things</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class TenantService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public TenantService()  {
	}

	@Override
	public void setApplicationContext(ApplicationContext ctx) throws BeansException {
		super.setApplicationContext(ctx);

		queryGateway 		= ctx.getBean(QueryGateway.class);
		commandGateway 		= ctx.getBean(CommandGateway.class);
		queryUpdateEmitter  = ctx.getBean(QueryUpdateEmitter.class);
		validator			= ctx.getBean(TenantValidator.class);
	}


   /**
	* Tenant Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	TenantService
	*/
	public static TenantService getTenantInstance() {
		return( new TenantService() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		CompletableFuture<UUID>
    */
	public CompletableFuture<UUID> createTenant( CreateTenantCommand command )
    throws ProcessingException, IllegalArgumentException {

		CompletableFuture<UUID> completableFuture = null;
				
		try {
			// --------------------------------------
        	// assign identity now if none
        	// -------------------------------------- 
			if ( command.getTenantId() == null )
				command.setTenantId( UUID.randomUUID() );
				
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	validator.validate( command );    

    		// ---------------------------------------
    		// issue the CreateTenantCommand - by convention the future return value for a create command
        	// that is handled by the constructor of an aggregate will return the UUID 
    		// ---------------------------------------
        	completableFuture = commandGateway.send( command );
        	
			LOGGER.log( Level.INFO, "return from Command Gateway for CreateTenantCommand of Tenant is " + command );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create Tenant - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return completableFuture;
    }

   /**
    * Update the provided command.
    * @param		command UpdateTenantCommand
    * @return		CompletableFuture<Void>
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    */
    public CompletableFuture<Void> updateTenant( UpdateTenantCommand command ) 
    throws ProcessingException, IllegalArgumentException {
    	CompletableFuture<Void> completableFuture = null;
    	
    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	validator.validate( command );    

        	// --------------------------------------
        	// issue the UpdateTenantCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save Tenant - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        
    	return completableFuture;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteTenantCommand
    * @return		CompletableFuture<Void>
    * @exception 	ProcessingException
    */
    public CompletableFuture<Void> delete( DeleteTenantCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
    	
    	CompletableFuture<Void> completableFuture = null;
    	
        try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	validator.validate( command );    
        	
        	// --------------------------------------
        	// issue the DeleteTenantCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete Tenant using Id = "  + command.getTenantId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
        
        return completableFuture;
    }

    /**
     * Method to retrieve the Tenant via TenantFetchOneSummary
     * @param 	summary TenantFetchOneSummary 
     * @return 	TenantFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public Tenant getTenant( TenantFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "TenantFetchOneSummary arg cannot be null" );
    	
    	Tenant entity = null;
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	validator.validate( summary );    
        	
        	// --------------------------------------
        	// use queryGateway to send request to Find a Tenant
        	// --------------------------------------
        	CompletableFuture<Tenant> futureEntity = queryGateway.query(new FindTenantQuery( new LoadTenantFilter( summary.getTenantId() ) ), ResponseTypes.instanceOf(Tenant.class));
        	
        	entity = futureEntity.get();
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate Tenant with id " + summary.getTenantId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all Tenants
     *
     * @return 	List<Tenant> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<Tenant> getAllTenant() 
    throws ProcessingException {
        List<Tenant> list = null;

        try {
        	CompletableFuture<List<Tenant>> futureList = queryGateway.query(new FindAllTenantQuery(), ResponseTypes.multipleInstancesOf(Tenant.class));
        	
        	list = futureList.get();
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all Tenant";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }


    /**
     * add Site to Sites 
     * @param		command AssignSitesToTenantCommand
     * @exception	ProcessingException
     */     
	public void addToSites( AssignSitesToTenantCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getTenantId() );

		SiteService childDelegate 	= SiteService.getSiteInstance();
		TenantService parentDelegate = TenantService.getTenantInstance();		
		UUID childId = command.getAddTo().getSiteId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Site as Sites to Tenant" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Site from Sites
     * @param		command RemoveSitesFromTenantCommand
     * @exception	ProcessingException
     */     	
	public void removeFromSites( RemoveSitesFromTenantCommand command ) throws ProcessingException {		
		
		SiteService childDelegate 	= SiteService.getSiteInstance();
		UUID childId = command.getRemoveFrom().getSiteId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add TenantUser to Users 
     * @param		command AssignUsersToTenantCommand
     * @exception	ProcessingException
     */     
	public void addToUsers( AssignUsersToTenantCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getTenantId() );

		TenantUserService childDelegate 	= TenantUserService.getTenantUserInstance();
		TenantService parentDelegate = TenantService.getTenantInstance();		
		UUID childId = command.getAddTo().getTenantUserId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a TenantUser as Users to Tenant" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove TenantUser from Users
     * @param		command RemoveUsersFromTenantCommand
     * @exception	ProcessingException
     */     	
	public void removeFromUsers( RemoveUsersFromTenantCommand command ) throws ProcessingException {		
		
		TenantUserService childDelegate 	= TenantUserService.getTenantUserInstance();
		UUID childId = command.getRemoveFrom().getTenantUserId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add IoTDevice to Devices 
     * @param		command AssignDevicesToTenantCommand
     * @exception	ProcessingException
     */     
	public void addToDevices( AssignDevicesToTenantCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getTenantId() );

		IoTDeviceService childDelegate 	= IoTDeviceService.getIoTDeviceInstance();
		TenantService parentDelegate = TenantService.getTenantInstance();		
		UUID childId = command.getAddTo().getIoTDeviceId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a IoTDevice as Devices to Tenant" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove IoTDevice from Devices
     * @param		command RemoveDevicesFromTenantCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDevices( RemoveDevicesFromTenantCommand command ) throws ProcessingException {		
		
		IoTDeviceService childDelegate 	= IoTDeviceService.getIoTDeviceInstance();
		UUID childId = command.getRemoveFrom().getIoTDeviceId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add DataRetentionPolicy to DataRetentionPolicies 
     * @param		command AssignDataRetentionPoliciesToTenantCommand
     * @exception	ProcessingException
     */     
	public void addToDataRetentionPolicies( AssignDataRetentionPoliciesToTenantCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getTenantId() );

		DataRetentionPolicyService childDelegate 	= DataRetentionPolicyService.getDataRetentionPolicyInstance();
		TenantService parentDelegate = TenantService.getTenantInstance();		
		UUID childId = command.getAddTo().getDataRetentionPolicyId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DataRetentionPolicy as DataRetentionPolicies to Tenant" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DataRetentionPolicy from DataRetentionPolicies
     * @param		command RemoveDataRetentionPoliciesFromTenantCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDataRetentionPolicies( RemoveDataRetentionPoliciesFromTenantCommand command ) throws ProcessingException {		
		
		DataRetentionPolicyService childDelegate 	= DataRetentionPolicyService.getDataRetentionPolicyInstance();
		UUID childId = command.getRemoveFrom().getDataRetentionPolicyId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add ConnectivityPlan to ConnectivityPlans 
     * @param		command AssignConnectivityPlansToTenantCommand
     * @exception	ProcessingException
     */     
	public void addToConnectivityPlans( AssignConnectivityPlansToTenantCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getTenantId() );

		ConnectivityPlanService childDelegate 	= ConnectivityPlanService.getConnectivityPlanInstance();
		TenantService parentDelegate = TenantService.getTenantInstance();		
		UUID childId = command.getAddTo().getConnectivityPlanId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a ConnectivityPlan as ConnectivityPlans to Tenant" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove ConnectivityPlan from ConnectivityPlans
     * @param		command RemoveConnectivityPlansFromTenantCommand
     * @exception	ProcessingException
     */     	
	public void removeFromConnectivityPlans( RemoveConnectivityPlansFromTenantCommand command ) throws ProcessingException {		
		
		ConnectivityPlanService childDelegate 	= ConnectivityPlanService.getConnectivityPlanInstance();
		UUID childId = command.getRemoveFrom().getConnectivityPlanId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add SimCard to SimCards 
     * @param		command AssignSimCardsToTenantCommand
     * @exception	ProcessingException
     */     
	public void addToSimCards( AssignSimCardsToTenantCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getTenantId() );

		SimCardService childDelegate 	= SimCardService.getSimCardInstance();
		TenantService parentDelegate = TenantService.getTenantInstance();		
		UUID childId = command.getAddTo().getSimCardId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a SimCard as SimCards to Tenant" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove SimCard from SimCards
     * @param		command RemoveSimCardsFromTenantCommand
     * @exception	ProcessingException
     */     	
	public void removeFromSimCards( RemoveSimCardsFromTenantCommand command ) throws ProcessingException {		
		
		SimCardService childDelegate 	= SimCardService.getSimCardInstance();
		UUID childId = command.getRemoveFrom().getSimCardId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add MessagingEndpoint to MessagingEndpoints 
     * @param		command AssignMessagingEndpointsToTenantCommand
     * @exception	ProcessingException
     */     
	public void addToMessagingEndpoints( AssignMessagingEndpointsToTenantCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getTenantId() );

		MessagingEndpointService childDelegate 	= MessagingEndpointService.getMessagingEndpointInstance();
		TenantService parentDelegate = TenantService.getTenantInstance();		
		UUID childId = command.getAddTo().getMessagingEndpointId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a MessagingEndpoint as MessagingEndpoints to Tenant" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove MessagingEndpoint from MessagingEndpoints
     * @param		command RemoveMessagingEndpointsFromTenantCommand
     * @exception	ProcessingException
     */     	
	public void removeFromMessagingEndpoints( RemoveMessagingEndpointsFromTenantCommand command ) throws ProcessingException {		
		
		MessagingEndpointService childDelegate 	= MessagingEndpointService.getMessagingEndpointInstance();
		UUID childId = command.getRemoveFrom().getMessagingEndpointId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add AccessPolicy to AccessPolicies 
     * @param		command AssignAccessPoliciesToTenantCommand
     * @exception	ProcessingException
     */     
	public void addToAccessPolicies( AssignAccessPoliciesToTenantCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getTenantId() );

		AccessPolicyService childDelegate 	= AccessPolicyService.getAccessPolicyInstance();
		TenantService parentDelegate = TenantService.getTenantInstance();		
		UUID childId = command.getAddTo().getAccessPolicyId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a AccessPolicy as AccessPolicies to Tenant" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove AccessPolicy from AccessPolicies
     * @param		command RemoveAccessPoliciesFromTenantCommand
     * @exception	ProcessingException
     */     	
	public void removeFromAccessPolicies( RemoveAccessPoliciesFromTenantCommand command ) throws ProcessingException {		
		
		AccessPolicyService childDelegate 	= AccessPolicyService.getAccessPolicyInstance();
		UUID childId = command.getRemoveFrom().getAccessPolicyId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add DeviceGroup to DeviceGroups 
     * @param		command AssignDeviceGroupsToTenantCommand
     * @exception	ProcessingException
     */     
	public void addToDeviceGroups( AssignDeviceGroupsToTenantCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getTenantId() );

		DeviceGroupService childDelegate 	= DeviceGroupService.getDeviceGroupInstance();
		TenantService parentDelegate = TenantService.getTenantInstance();		
		UUID childId = command.getAddTo().getDeviceGroupId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a DeviceGroup as DeviceGroups to Tenant" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove DeviceGroup from DeviceGroups
     * @param		command RemoveDeviceGroupsFromTenantCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDeviceGroups( RemoveDeviceGroupsFromTenantCommand command ) throws ProcessingException {		
		
		DeviceGroupService childDelegate 	= DeviceGroupService.getDeviceGroupInstance();
		UUID childId = command.getRemoveFrom().getDeviceGroupId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add AlertRule to AlertRules 
     * @param		command AssignAlertRulesToTenantCommand
     * @exception	ProcessingException
     */     
	public void addToAlertRules( AssignAlertRulesToTenantCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getTenantId() );

		AlertRuleService childDelegate 	= AlertRuleService.getAlertRuleInstance();
		TenantService parentDelegate = TenantService.getTenantInstance();		
		UUID childId = command.getAddTo().getAlertRuleId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a AlertRule as AlertRules to Tenant" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove AlertRule from AlertRules
     * @param		command RemoveAlertRulesFromTenantCommand
     * @exception	ProcessingException
     */     	
	public void removeFromAlertRules( RemoveAlertRulesFromTenantCommand command ) throws ProcessingException {		
		
		AlertRuleService childDelegate 	= AlertRuleService.getAlertRuleInstance();
		UUID childId = command.getRemoveFrom().getAlertRuleId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add MaintenanceTicket to MaintenanceTickets 
     * @param		command AssignMaintenanceTicketsToTenantCommand
     * @exception	ProcessingException
     */     
	public void addToMaintenanceTickets( AssignMaintenanceTicketsToTenantCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getTenantId() );

		MaintenanceTicketService childDelegate 	= MaintenanceTicketService.getMaintenanceTicketInstance();
		TenantService parentDelegate = TenantService.getTenantInstance();		
		UUID childId = command.getAddTo().getMaintenanceTicketId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a MaintenanceTicket as MaintenanceTickets to Tenant" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove MaintenanceTicket from MaintenanceTickets
     * @param		command RemoveMaintenanceTicketsFromTenantCommand
     * @exception	ProcessingException
     */     	
	public void removeFromMaintenanceTickets( RemoveMaintenanceTicketsFromTenantCommand command ) throws ProcessingException {		
		
		MaintenanceTicketService childDelegate 	= MaintenanceTicketService.getMaintenanceTicketInstance();
		UUID childId = command.getRemoveFrom().getMaintenanceTicketId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add UsageRecord to UsageRecords 
     * @param		command AssignUsageRecordsToTenantCommand
     * @exception	ProcessingException
     */     
	public void addToUsageRecords( AssignUsageRecordsToTenantCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getTenantId() );

		UsageRecordService childDelegate 	= UsageRecordService.getUsageRecordInstance();
		TenantService parentDelegate = TenantService.getTenantInstance();		
		UUID childId = command.getAddTo().getUsageRecordId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a UsageRecord as UsageRecords to Tenant" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove UsageRecord from UsageRecords
     * @param		command RemoveUsageRecordsFromTenantCommand
     * @exception	ProcessingException
     */     	
	public void removeFromUsageRecords( RemoveUsageRecordsFromTenantCommand command ) throws ProcessingException {		
		
		UsageRecordService childDelegate 	= UsageRecordService.getUsageRecordInstance();
		UUID childId = command.getRemoveFrom().getUsageRecordId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}



	/**
	 * Internal helper method to load the root 
	 * 
	 * @param		id	UUID
	 * @return		Tenant
	 */
	protected Tenant load( UUID id ) throws ProcessingException {
		tenant = TenantService.getTenantInstance().getTenant( new TenantFetchOneSummary(id) );	
		return tenant;
	}


//************************************************************************
// Attributes
//************************************************************************
	private QueryGateway queryGateway;
	private CommandGateway commandGateway;
	private QueryUpdateEmitter queryUpdateEmitter;
	private TenantValidator validator;
	private Tenant tenant 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(TenantService.class.getName());
    
}
